### ISSUE TITLE
Consistency check mixes geometric and logical coordinates

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#15]
The lines

https://github.com/itpplasma/libneo/blob/d55908cc0b827707874e5ffea7e6ad500869a2b8/src/magfie/field_divB0.f90#L254

compare stretched coordinates to minimum and maximum bounds in geometric coordinates. It leads to wrong behavior near domain boundaries.

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still live, and reproduced. The two lines the issue points at are byte-identical to the original import (`f0cbd25` "Original version of field_divB0"); `git log -L 236,242:src/magfie/field_divB0.f90` shows only whitespace/comment churn since (`45ba266` "Remove commented code and empty comment lines"). Nothing has superseded them: `field_eq` is still the EFIT equilibrium evaluator for `efit_to_boozer`, `bdivfree` and `geoflux_field`, and libneo is gated on SIMPLE, NEO-2, MEPHIT, KAMEL and rabe (`ci/downstreams`), with NEO-RT report-only.

## Purpose

`field_eq` is the axisymmetric equilibrium evaluator that feeds the Boozer files consumed by NEO-2 and NEO-RT, the divergence-free reconstruction in `src/magfie/bdivfree.f90`, and the geometric-flux chart in `src/magfie/geoflux_field.f90`. Its entire out-of-domain policy is one silent `max`/`min` pair. Because the caller path `field` hands it *stretched* coordinates while other callers hand it *geometric* ones, the same bound means two different things depending on who called, and in neither case is the result reported. The practical damage is at the plasma edge: the returned `B` and the returned `dB/dR, dB/dZ` stop being consistent with each other exactly where edge orbits, field-line tracing and the SOL band live.

## Current state

`field` stretches first, then evaluates (`src/magfie/field_divB0.f90:70-77`):

```fortran
  call stretch_coords(r,z,rm,zm)

  if(iequil.eq.0) then
    call set_zero(Br,Bp,Bz,dBrdR,dBrdp,dBrdZ,   &
                  dBpdR,dBpdp,dBpdZ,dBzdR,dBzdp,dBzdZ)
  else
    call field_eq(rm,p,zm,Br,Bp,Bz,dBrdR,dBrdp,dBrdZ   &
               ,dBpdR,dBpdp,dBpdZ,dBzdR,dBzdp,dBzdZ)
```

`field_eq` then clamps whatever it received to the EQDSK box (`src/magfie/field_divB0.f90:238-245`):

```fortran
  rrr=max(rad(1),min(rad(nrad),r))
  zzz=max(zet(1),min(zet(nzet),z))

  call spline(nrad,nzet,rad,zet,hrad,hzet,icp,splpsi,ipoint,rrr,zzz, &
                psif,dpsidr,dpsidz,d2psidr2,d2psidrdz,d2psidz2,ierr)

  Brad = -dpsidz/rrr
  Bzet =  dpsidr/rrr
```

Three distinct defects are packed into these two lines.

1. **Mixed coordinate spaces.** `rad`/`zet` are the geometric EQDSK grid built in `set_eqcoords` (`src/magfie/field_divB0.f90:509-530`, grid loops at `:522` and `:527`) from `r1`, `xdim`, `zmid`, `zdim`, converted to cm at `:195-196`. Through `field` the incoming `r` is `rm`, the image of the soft-clamp map `rho -> rho_c + delta*atan2(rho-rho_c, delta)` (`src/magfie/field_divB0.f90:907-911`, `delta = 1.0_dp` cm at `:822`). Through `efit_to_boozer` (`src/efit_to_boozer/rhs.f90:30`, `app/efit_to_boozer.f90:133`), `src/magfie/geoflux_field.f90:54` and `src/magfie/bdivfree.f90:1676` the incoming `r` is the raw geometric coordinate. Same bound, two meanings.

2. **The clamp is not a domain check and never reports.** `ierr` is passed to `spline` and then discarded; and `spline` itself is a dead contract — its header says `ierr = 1 - point out of the domain` (`src/magfie/spline5_RZ.f90:115`) but `:129` unconditionally sets `ierr=0`, having already clamped its own cell indices at `:123` and `:127`. So index safety is already handled inside `spline`; the `max`/`min` in `field_eq` adds nothing but a silent physics substitution.

3. **`B` and `dB` become mutually inconsistent.** Once clamped, `Brad`, `Bzet`, `Bphi` are constant along the clamped direction, but the returned `dBrdR`, `dBzdR`, `dBpdR` are the boundary-cell derivatives and are non-zero. Consumers that use the returned Jacobian (`field_fourier_derivs`, the guiding-center RHS, any `div B` check) get a Jacobian that is not the Jacobian of the field they were handed. Related: `src/magfie/bdivfree.f90` stretches all six finite-difference offset points (`stretch_coords` at `:1599, 1610, 1625, 1636, 1653, 1664`, each followed by `rrr=rm; zzz=zm`) but calls `field_eq(r,phi,z,...)` unstretched for the centre point at `:1676` — the same mixing, in a different file.

**There is no run-time consistency check between the convex wall and the EQDSK box, and the shipped fixtures do not satisfy containment.** `test/resources/input_efit_file.dat` line 2 has `xdim=1.92, zdim=3.008, rzero=1.65, r1=0.75, zmid=0.0`, so the box is `R in [75, 267] cm`, `Z in [-150.4, 150.4] cm` (printed verbatim by the driver below). `test/resources/convexwall.dat` is the 5-point rectangle `R in [10, 160] cm`, `Z in [-130, 140] cm`. The wall reaches 65 cm to the *left* of the box. Every point with `R < 75` cm is passed through `stretch_coords` unchanged (it is inside the wall, so the map is the identity) and then silently relocated to `R = 75` cm by `field_eq`. `test/python/field_divB0.inp` is exactly this non-contained pair (`gfile = ../resources/input_efit_file.dat`, `convexfile = ../resources/convexwall.dat`, `ipert = 0`, `iequil = 1`).

### Prior claim of this comment that did not survive checking

An earlier revision asserted the returned `dBpdR` at `R = 70` cm is `~ -fpol/75**2`. That is wrong: `psihat <= 1` there, so the `fpol_prime*dpsidr/(psi_sep*rrr)` term at `:266` dominates and the measured value is ~4.7x larger. The measured numbers below replace it.

## Reproduction / evidence

`field_eq` and `stretch_coords` are public in `field_sub`, so the MRE can call them directly and skip the `ipert` plumbing. Save as `test/source/mre_field_eq_box.f90`:

```fortran
program mre_field_eq_box
    use libneo_kinds, only: dp
    use field_sub, only: read_field_input, field_eq, stretch_coords
    use field_eq_mod, only: rad, zet, nrad, nzet
    implicit none

    real(dp) :: Bp0, Bpm, Bpp, dBpdR_ret, dBpdR_fd, rm, zm
    real(dp), parameter :: d = 1.0e-3_dp
    real(dp), parameter :: r_probe = 70.0_dp

    call read_field_input('field_divB0.inp')

    call eval(r_probe, Bp0, dBpdR_ret)
    print '(a,2(1x,f12.4))', 'EQDSK box R range (cm):', rad(1), rad(nrad)
    print '(a,2(1x,f12.4))', 'EQDSK box Z range (cm):', zet(1), zet(nzet)

    call stretch_coords(r_probe, 0.0_dp, rm, zm)
    print '(a,2(1x,f12.4))', 'stretch_coords(70,0) ->', rm, zm

    call eval(r_probe - d, Bpm, dBpdR_fd)
    call eval(r_probe + d, Bpp, dBpdR_fd)
    call eval(r_probe, Bp0, dBpdR_ret)
    dBpdR_fd = 0.5_dp*(Bpp - Bpm)/d

    print '(a,1x,es16.8)', 'Bp        =', Bp0
    print '(a,1x,es16.8)', 'dBpdR ret =', dBpdR_ret
    print '(a,1x,es16.8)', 'dBpdR fd  =', dBpdR_fd

contains

    subroutine eval(rr, bphi, dbpdr)
        real(dp), intent(in) :: rr
        real(dp), intent(out) :: bphi, dbpdr
        real(dp) :: a(12)
        call field_eq(rr, 0.0_dp, 0.0_dp, a(1), a(2), a(3), a(4), a(5), a(6), &
                      a(7), a(8), a(9), a(10), a(11), a(12))
        bphi = a(2)
        dbpdr = a(7)
    end subroutine eval

end program mre_field_eq_box
```

Every dummy argument of `field_eq` gets its own storage: Fortran forbids aliasing two `intent(out)` dummies to the same actual, and forbids passing an array section to a scalar dummy.

Standalone build (no full CMake configure needed; this is the exact recipe that produced the numbers below — run it in a scratch directory, not in the checkout):

```bash
SRC=/path/to/libneo/src
WORK=$(mktemp -d) && cd "$WORK"
cp $SRC/util/libneo_kinds.f90 $SRC/util/math_constants.f90 $SRC/spl_three_to_five.f90 .
cp $SRC/magfie/{field_eq_mod,input_files,field_c_mod,field_mod,inthecore_mod,\
spline5_RZ,field_divB0,amn_mod,theta_rz_mod,extract_fluxcoord_mod,period_mod,\
bdivfree_mod,bdivfree,field_mesh3d,magfield_mod,polylag_3}.f90 .
cp /path/to/libneo/test/source/mre_field_eq_box.f90 .
gfortran -ffree-line-length-none -fopenmp -c \
  libneo_kinds.f90 math_constants.f90 input_files.f90 field_eq_mod.f90 \
  field_mod.f90 field_c_mod.f90 inthecore_mod.f90 amn_mod.f90 theta_rz_mod.f90 \
  extract_fluxcoord_mod.f90 period_mod.f90 magfield_mod.f90 bdivfree_mod.f90 \
  spl_three_to_five.f90 spline5_RZ.f90 polylag_3.f90 field_mesh3d.f90 \
  field_divB0.f90 bdivfree.f90
gfortran -ffree-line-length-none -fopenmp -o mre.x mre_field_eq_box.f90 *.o
# run where field_divB0.inp resolves its relative ../resources/ paths
mkdir -p run/work && cp /path/to/libneo/test/python/field_divB0.inp run/work/
mkdir -p run/resources && cp /path/to/libneo/test/resources/{input_efit_file,convexwall}.dat run/resources/
cd run/work && "$WORK"/mre.x
```

Measured output (gfortran, `fe3f76e`):

```
EQDSK box R range (cm):      75.0000     267.0000
EQDSK box Z range (cm):    -150.4000     150.4000
stretch_coords(70,0) ->      70.0000       0.0000
Bp        =  -1.76620056E+05
dBpdR ret =   1.10193539E+04
dBpdR fd  =   0.00000000E+00
```

`stretch_coords` is the identity at `(70, 0)` — the point is inside the wall — yet the field is frozen at the `R = 75` cm boundary column while a large derivative is still returned. Sweeping R with the same driver:

| R (cm) | `Bp` (G) | returned `dBpdR` | central-difference `dBpdR` | rel. error |
|---|---|---|---|---|
| 70 (left of box) | -1.766201e5 | 1.101935e4 | 0.0 | 1.0 |
| 100 | -4.690337e4 | 1.461056e3 | 1.461056e3 | 1.6e-9 |
| 170 | -2.416040e4 | 1.421992e2 | 1.421992e2 | 4.2e-11 |
| 260 | -2.166538e6 | -1.910593e5 | -1.910593e5 | 5.4e-10 |
| 280 (right of box) | -3.865449e6 | -3.001156e5 | 0.0 | 1.0 |

This is the load-bearing measurement: **inside the box the returned derivative already agrees with the central difference to 1e-9 or better**, so the 1e-6 tolerance in the acceptance criteria is achievable and the failure outside the box is entirely the clamp's doing, not spline noise.

Second, cheaper check with no Fortran — the containment arithmetic:

```bash
python3 -c "import numpy as np; a=np.loadtxt('test/resources/convexwall.dat'); print(a[:,0].min(), a[:,0].max())"
# -> 10.0 160.0, against a box starting at 75.0 cm
```

## The reporting channel: do not reuse `ierrfield` naively

`field_eq_mod::ierrfield` (`src/magfie/field_eq_mod.f90:10`, `threadprivate` at `:36`) is **not unused**. `field_eq` never writes it, but `src/magfie/magfie_cyl.f90:41-50` does, and it *overwrites* the flag unconditionally right after every `field` call:

```fortran
  CALL field(x(1),x(2),x(3),br,bf,bz,BRR,BRF,BRZ,BFR,BFF,BFZ,BZR,BZF,BZZ)

  if(allow_sol) then
    ierrfield=0
  else if((psif-psi_axis)/(psi_sep-psi_axis).gt.1d0) then
    print *,'magfie: point is outside separatrix, (R,Z) = ',x(1),x(3)
    ierrfield=1
  else
    ierrfield=0
  endif
```

`ierrfield` there means "outside the separatrix", gated by `allow_sol`. If `field_eq` sets `ierrfield = 1` for an out-of-box point, `magfie_cyl` clears it on the very next lines and the new signal is lost on the whole `magfie` path. Introduce a **separate** flag `ierr_box` in `field_eq_mod` for the box test, and — if the `magfie` path should also surface it — change `magfie_cyl` to combine rather than assign. Do not silently repurpose `ierrfield`.

## Behaviour (BDD)

```gherkin
Scenario: convex wall not contained in the EQDSK box is reported at init
  Given field_divB0.inp names gfile=../resources/input_efit_file.dat
    and convexfile=../resources/convexwall.dat
  When the first call to field_eq triggers its initialisation block
  Then exactly one warning naming both files and both bounding boxes is written,
    reporting wall R_min = 10.0 cm below box R_min = 75.0 cm
  And when field_eq_mod::strict_domain is .true., the run stops

Scenario: point inside the wall but outside the box is flagged, not silently moved
  Given the fixture pair above and strict_domain = .false.
  When field_eq(70.0, 0.0, 0.0, ...) is called (cm, inside the wall, outside the box)
  Then field_eq_mod::ierr_box == 1 on return, read on the calling thread
  And field_eq(170.0, 0.0, 0.0, ...) leaves ierr_box == 0
  And field_eq_mod::ierrfield is untouched by field_eq

Scenario: in-box derivatives already agree and must keep agreeing
  Given consistent_continuation = .false. (the default)
  When field_eq is evaluated at R in {100.0, 170.0, 260.0} cm, Z = 0,
    and at those points +/- 1e-3 cm in R
  Then the central difference of Bp matches the returned dBpdR
    to a relative tolerance of 1e-6
    (measured today: 1.6e-9, 4.2e-11, 5.4e-10)

Scenario: returned derivatives are the derivatives of the returned field outside the box
  Given consistent_continuation = .true.
  And a query point at least 1e-2 cm away from any box face,
    so the +/- 1e-3 cm stencil does not straddle the boundary
  When field_eq is evaluated at R in {70.0, 280.0} cm, Z = 0,
    and at those points +/- 1e-3 cm in R
  Then the central difference of Bp matches the returned dBpdR
    to a relative tolerance of 1e-6
    (today both central differences are exactly 0.0 while the returned
     values are 1.101935e4 and -3.001156e5)

Scenario: toroidal field keeps its 1/R fall-off outside the box
  Given use_fpol = .true. and consistent_continuation = .true.
  When field_eq is called at R = 280 cm and at the box edge R = 267 cm, Z = 0
  Then Bphi(280)*280.0 equals Bphi(267)*267.0 to 1e-12 relative
    (i.e. R*B_phi is the constant vacuum value outside the box,
     rather than B_phi being frozen at its R = 267 cm value)

Scenario: existing in-box behaviour is bit-for-bit unchanged
  Given consistent_continuation = .false.
  And any point strictly inside both the wall and the EQDSK box
  When field_eq is called before and after this change
  Then Br, Bphi, Bz and all nine derivatives are identical
```

## Implementation plan

1. `src/magfie/field_eq_mod.f90` — add module state next to the existing `allow_sol` (`:17`): `logical :: strict_domain = .false.`, `logical :: consistent_continuation = .false.`, `logical :: box_wall_checked = .false.`, `integer :: ierr_box = 0`, and `real(dp) :: rad_min, rad_max, zet_min, zet_max`. Add `ierr_box` to the `threadprivate` list at `:36`. Reset `box_wall_checked` and `ierr_box` in `reset_field_eq_state` (`:40-59`), which already exists and already clears `icall_eq`.
2. `src/magfie/field_divB0.f90` — at the end of the first-call block (after `call s2dcut(...)` at `:225`, and after the cm conversion at `:195-196`) store `rad_min = rad(1)`, `rad_max = rad(nrad)`, `zet_min = zet(1)`, `zet_max = zet(nzet)`.
3. `src/magfie/field_divB0.f90` — expose the convex-wall extent. `stretch_coords` keeps `rad_w`, `zet_w`, `delta` and its lazy-init guard as local `save` variables (`icall` at `:813`, arrays at `:819-822`), and there is **no reset path for that guard** — `reset_field_eq_state` does not touch it, which is why `test_stretch_coords.f90` spawns a subprocess to test a second wall. So hoist those variables and the lazy-init block into a new `src/magfie/convex_wall_mod.f90` (add it to `src/magfie/CMakeLists.txt` beside `field_divB0.f90` at `:11`), give it a `reset_convex_wall()` entry point, and leave `stretch_coords` as a thin consumer. Expose `wall_bounding_box(r_lo, r_hi, z_lo, z_hi)` returning `[minval(rad_w), maxval(rad_w)]` and `[minval(zet_w), maxval(zet_w)]` inflated by `delta*pi/2` — the supremum of the soft-clamp displacement, since `atan2(x, delta) -> pi/2` as `x -> inf` in `:908`.
4. `src/magfie/field_divB0.f90` — add `subroutine check_wall_within_eq_box()` and call it once from `field_eq` after step 2, guarded by `box_wall_checked`. It compares the two boxes and writes one warning line naming `gfile`, `convexfile` and the offending bound; with `strict_domain = .true.` it `error stop`s. **This is the consistency check the issue title asks for: performed once, between two objects that live in the same geometric coordinates, instead of per evaluation on a stretched coordinate.**
5. `src/magfie/field_divB0.f90:238-239` — replace the bare `max`/`min` with an explicit, reporting clamp writing `ierr_box` (not `ierrfield`, see above):
   ```fortran
   rrr = max(rad_min, min(rad_max, r))
   zzz = max(zet_min, min(zet_max, z))
   if (rrr /= r .or. zzz /= z) then
     ierr_box = 1
     if (strict_domain) error stop 'field_eq: point outside EQDSK box'
   else
     ierr_box = 0
   end if
   ```
6. `src/magfie/field_divB0.f90:244-272` — behind `consistent_continuation`, make the returned field and derivatives mutually consistent when clamped. Take `psif` and its derivatives from the spline at the clamped point, but use the **true** `r` in the explicit `1/R` factors, and zero the psi-derivative contributions along any clamped direction:
   - `Bphi = fpol/r`, `dBpdR = fpol_prime*dpsidr/(psi_sep*r) - fpol/r**2` with `dpsidr = 0` when `rrr /= r` — this makes the vacuum continuation `R*B_phi = const` exact outside the box rather than frozen;
   - `Brad = -dpsidz/r`, `Bzet = dpsidr/r`, with `dpsidr`/`d2psidr2`/`d2psidrdz` set to zero if `rrr /= r` and `dpsidz`/`d2psidz2`/`d2psidrdz` set to zero if `zzz /= z`.
   Default `.false.` so no golden record moves; flip only after the downstream gate passes.
7. `src/magfie/bdivfree.f90:1676` — fix the centre-point call in `field_fourier_derivs` to use stretched coordinates like the six offset calls, or (better) stretch once outside the difference stencil. Note the `inthecore` and `field_fourier` calls at `:1678-1680` take the same raw `(r, z)` and must move with it.
8. `test/field/test_field_eq_domain.f90` (new) — a `program` following the `test/field/test_stretch_coords.f90` idiom (`util_for_test` `print_test`/`print_ok`/`print_fail` + `error stop`), covering the scenarios above. Reuse `test/resources/`; the shipped fixture pair already violates containment, which makes scenario 1 free. Because both `field_eq` and `stretch_coords` initialise once per process, drive `consistent_continuation` by setting the module variable between `reset_field_eq_state()` calls, or split into two `add_test` invocations of the same executable with an argument, as `test_stretch_coords` does with `--empty`.
9. `test/field/CMakeLists.txt` — register it beside `test_stretch_coords` (`:59-63`, linking `neo magfie util_for_test`) and add `test_field_eq_domain` to the `set_tests_properties(... PROPERTIES LABELS "field")` list at `:66-77`.
10. `test/field/test_stretch_coords.f90` — extend `test_stretch_coords_large_file` with an assertion that `wall_bounding_box` returns the analytic extent of the 150-point wall generated at `:63-70`.
11. Downstream ordering: nothing needs to change in the sibling repos for the default-off path. `.github/workflows/downstream-gate.yml` reads `ci/downstreams` and dispatches SIMPLE (`main.yml`), NEO-2 (`unit-tests.yml`), MEPHIT (`main.yml`), KAMEL (`ci.yml`) and rabe (`test.yml`) as blocking, plus NEO-RT (`test.yml`) report-only. Check that no golden record depends on the current clamped derivatives before flipping `consistent_continuation` on.

## Acceptance criteria

- [ ] `make && cd build && ctest --output-on-failure -L field` passes, including the new `test_field_eq_domain`. (`make` runs `cmake --preset default` then `cmake --build --preset default`; see `Makefile:24-27`.)
- [ ] Full `ctest` is green, with no change in `test/source/test_geoflux.f90`, `test/source/test_boozer_converter_vs_simple.f90` or any `efit_to_boozer` golden output while `consistent_continuation = .false.`.
- [ ] With `consistent_continuation = .false.`: central-difference vs returned `dBpdR`, `dBrdR`, `dBzdR`, `dBrdZ`, `dBzdZ` agree to relative `1e-6` at 100 points sampled strictly inside the box and at least `1e-2` cm from any face. (Baseline measured today at R = 100/170/260 cm: 1.6e-9 / 4.2e-11 / 5.4e-10 — this criterion passes before the change and must keep passing.)
- [ ] With `consistent_continuation = .true.`: the same agreement holds at 20 points sampled 5-20 cm beyond each box face. (Today these fail with relative error 1.0, because the central difference is identically 0.)
- [ ] `ierr_box == 1` after `field_eq` at `R = 70` cm with the `test/resources` fixture pair; `ierr_box == 0` at `R = 170` cm; `ierrfield` is unchanged by `field_eq` in both cases.
- [ ] Running the existing tests emits exactly one warning about the non-contained fixture wall, naming both files.
- [ ] `.github/workflows/downstream-gate.yml` green for SIMPLE, NEO-2, MEPHIT, KAMEL, rabe.

## References

- Sauter, Medvedev, *Tokamak coordinate conventions: COCOS*, Comput. Phys. Commun. **184** (2013) 293-302 — the tokamak coordinate/sign conventions and the EQDSK g-file layout whose box header (`xdim, zdim, rzero, r1, zmid` in libneo's naming) `read_eqfile1` parses at `:405` and `set_eqcoords` turns into the `rad`/`zet` grid.
- Albert, Kasilov, Kernbichler, *Symplectic integration with non-canonical quadrature for guiding-center orbits in magnetic confinement devices*, J. Comput. Phys. **403** (2020) 109065 — the guiding-centre RHS consumes the field Jacobian directly, which is why a Jacobian inconsistent with the returned field (defect 3) is not a cosmetic problem.
- No specific literature reference is needed for the clamp policy itself. Whether other orbit-following codes return an error code instead of clamping was **not** verified for this comment; do not cite one without checking the source. The in-repo justification is sufficient: `spline` already documents `ierr = 1 - point out of the domain` at `src/magfie/spline5_RZ.f90:115` and then never sets it.
- The convex-wall soft-clamp `rho -> rho_c + delta*atan2(...)` has no specific literature reference; it is an implementation detail internal to `field_divB0`.

## Scope and risk

One PR is feasible (~150 lines of source plus one test file), but it is cleanly splittable and probably should be: (a) the one-time wall/box containment check plus `ierr_box` reporting — safe, default-on, no numerical change; (b) the consistent continuation of field and derivatives outside the box — behaviour-changing, must ship default-off behind `consistent_continuation` and be flipped only after the downstream gate is green. The risk in (b) is that `efit_to_boozer` field-line integration and MEPHIT's `bdivfree` path currently rely, perhaps accidentally, on the frozen-boundary values; the golden records in `test/source/test_boozer_converter_vs_simple.f90` are the tripwire. Step 3's `convex_wall_mod` extraction is the largest mechanical change and could be split off first as a pure refactor with no behaviour change.

Related issues: `itpplasma/NEO-RT#53` and `itpplasma/libneo#302` were referenced during triage as related-but-distinct. Their current content was **not** re-read for this comment — confirm before relying on either.
