### ISSUE TITLE
Replace pfile format by mgrid format

### ISSUE THREAD

**Issue by pazathoth** [itpplasma/libneo#19]
[bdivfree](../tree/main/src/magfie/bdivfree.f90) uses a custom format in its `pfile` in `field_c` for the (vacuum) perturbation field, which is similar but not identical to the `mgrid` format. The latter is used by VMEC and supports coil groups, so it would be the preferred alternative. Writing a parser is somewhat more involved than plain reading of arrays and should be done in conjunction with [coil_tools](../tree/main/src/magfie/coil_tools.f90).

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still relevant, but the ground has shifted substantially since 2024-01: the mgrid parser the issue asks for **now exists** (`src/field/mgrid.f90`, added in `e25f854`, "neo_spline_field: mgrid netCDF field format (B, A=curl A, cylindrical + cartesian)"). What is still missing is exactly the two ends the issue named — `field_c` still reads the Nemov plaintext `pfile`, and `coil_tools`/`vacfield` still only *writes* that plaintext format. So this is a wiring job now, not a parser-writing job, and the spec below is scoped accordingly.

## Purpose

`field_c` is the vacuum/perturbation-field entry point reached through `field_divB0.inp`. Its on-disk input is an undocumented, unit-less, ASCII grid dump with hard-coded array shapes for three of its four variants. It cannot carry coil-group structure, so a scan over RMP coil-current combinations requires re-running Biot-Savart per combination instead of re-summing stored per-group fields with new currents — which is precisely what `mgrid_mode = 'R'` exists for in makegrid/VMEC. Consolidating on mgrid also removes a bespoke format from the org's I/O surface and makes libneo's vacuum fields directly consumable by VMEC free-boundary runs and the STELLOPT-family tools that read mgrid (BEAMS3D, FIELDLINES).

`icftype = 4` must keep working. The gated downstream `MEPHIT` genuinely exercises this reader: `MEPHIT/data/field_divB0.inp` has `ipert = 1` (line 1), `icftype = 4` (line 6) and a real `pfile` (line 8, `'./DATA_ASDEX_MESH3D_30835/field.dat'`). `KAMEL/PreProc/fourier/inp/field_divB0.inp:6` and `NEO-RT/POTATO/RUN/field_divB0.inp:6` also carry `icftype = 4`, but both have `ipert = 0` and an empty / `'unused'` `pfile`, so they pin the default value without exercising `read_field4`. Either way the change must be **additive**.

## Current state

**The consumer side.** `read_field_input` (`src/magfie/field_divB0.f90:15-45`) reads `icftype` from line 6 and `pfile` from line 8 of `field_divB0.inp`. `field_c` (`src/magfie/field_divB0.f90:582-647`) dispatches on `icftype` with *hard-coded grid sizes* for types 1-3:

```fortran
    if(icftype.eq.1) then
      nr=129
      np=37
      nz=129
    elseif(icftype.eq.2) then
...
    elseif(icftype.eq.4) then
      call read_sizes(nr,np,nz)
    else
      print *,'field_c: unknown coil file type'
      stop
```

`icftype = 4` is read by `read_field4` (`src/magfie/field_divB0.f90:1250-1276`): four header lines (`nr np nz`, `rmin rmax`, `pmin pmax`, `zmin zmax`) then `nr*np*nz` triples of `Br,Bp,Bz`, list-directed. No units, no coil groups, no metadata. `icftype < 4` goes to `read_field2` (`:1178`) instead. After reading, `field_c:629` calls `vector_potentials(...)` from `src/magfie/bdivfree.f90:2`, and evaluation goes through `field_divfree` (`src/magfie/bdivfree.f90:314`).

**The producer side.** `write_Bvac_nemov` (`src/magfie/coil_tools.f90:822-855`) writes exactly that format, after `biot_savart_sum_coils` (`:345-398`) has already collapsed all coils into one array:

```fortran
      write (fid, '(4(i0, :, 1x))') nR, nphi + 1, nZ, 1
      write (fid, '(2(es24.16e3, :, 1x))') Rmin, Rmax
      write (fid, '(2(es24.16e3, :, 1x))') 0d0, 2d0*pi
      write (fid, '(2(es24.16e3, :, 1x))') Zmin, Zmax
```

`vacfield.f90:119-129` is the `field_type == 'sum'` branch that drives it.

**Units.** `coil_tools` works in **CGS**: grid metadata is written with `'... in cm'` (`coil_tools.f90:695`, `:880-886`), and `vacfield.f90:66` sets `prefactor = current_si_to_cgs / c`. `src/field` is CGS too — `src/field/biotsavart.f90:5` uses `clight = 2.99792458d10` (cm/s). `read_field4` applies no unit conversion; `read_field1` (`:770-772`) and `read_field2` (`:1208-1210`) multiply by `1.d4` (T→G). Standard makegrid mgrid files from STELLOPT are in **SI (Tesla, metres)**, so a file of external origin is the unit hazard, not the libneo-internal path.

**What already exists.** `src/field/mgrid.f90` (module `neo_mgrid`) provides `read_mgrid` (`:34`), `write_mgrid` (`:121`), `is_mgrid_file` (`:209`), covered by `test/field/test_mgrid.f90` (registered at `test/field/CMakeLists.txt:47-58`).

- `read_mgrid` already **sums coil groups** with `raw_coil_cur` scaling in `'R'` mode (`sum_groups`, `mgrid.f90:243`; called at `:78-79`) and appends the wrap plane at `2*pi/nfp`.
- Multi-group **reading** in `'R'` mode is **already tested**: `test_raw_multigroup` (`test/field/test_mgrid.f90:176-200`) builds a two-group file by hand via `build_raw_mgrid` (`:348-394`) and asserts the scaled sum to `1e-12`. Do not re-add this test.
- `write_mgrid` is **single-group only**: `nf90_def_dim(ncid, 'external_coil_groups', 1, d_grp)` (`mgrid.f90:168`), `put_int(ncid, 'nextcur', 1)` (`:190`), `mode_c = 'S'` (`:197`), `raw_coil_cur` written as `[1.0_dp]`. There is therefore **no write-side multi-group round trip** anywhere.
- The Python side already writes arbitrary numbers of groups: `python/libneo/mgrid.py:144-177` emits `br_kkk/bp_kkk/bz_kkk` for `kgroup` in range, and `python/libneo/coils.py:184` `to_mgrid_metadata()` produces `(coil_group, raw_coil_cur)`.
- `read_mgrid` performs **no unit conversion** and exposes no units attribute, so its output is in whatever units the file holds.

**CMake is already in place.** `mgrid.f90` is a source of the `neo_field` library (`src/field/CMakeLists.txt:11-22`). `neo` PUBLIC-links `neo_field` (`CMakeLists.txt:372-388`), and `magfie` links `neo` (`src/magfie/CMakeLists.txt:26-27`). So `magfie` already reaches `neo_mgrid` transitively, `magfie` already links NetCDF explicitly (`src/magfie/CMakeLists.txt:38-45`), and there is **no cycle** — `neo_field` depends only on `field_base`, `interpolate`, `neo_polylag` and NetCDF, never on `magfie`. No CMake change is needed for step 6.

## Reproduction / evidence

There is no bug to reproduce; this is a format-replacement request. Build and baseline:

```bash
cd /path/to/libneo
make                       # wraps: cmake --preset default && cmake --build --preset default
cd build && ctest --output-on-failure          # record the baseline pass list
ctest -R "test_mgrid|coil_tools|tilted_coil" --output-on-failure
```

End-to-end demonstration once implemented. Use the **Nemov** coil format — it is what `vacfield.x` accepts (`vacfield.f90:150-167` lists AUG, GPEC, Nemov; there is no STELLOPT `coils.*` reader in `vacfield`) and it already carries a per-coil index. `coils_write_nemov` (`coil_tools.f90:185-203`) shows the exact layout: a header count, then `X Y Z current kc` per vertex, with a `current = 0.0` sentinel line closing each coil `kc`.

```bash
# coils.test — two coils, hence two groups; columns: X Y Z current kc
# line 1 is the total vertex count (sum over coils of nseg + 1)

cd build
./vacfield.x Nemov 1 coils.test mgrid ../tools/vacfield_AUG.in vacfield_test.nc currents.dat
./vacfield.x Nemov 1 coils.test sum   ../tools/vacfield_AUG.in field_test.dat  currents.dat
```

Then assert, in the new test rather than by hand:

1. `read_mgrid('vacfield_test.nc', ...)` returns `nfp` as written and a mesh whose summed field matches the `write_Bvac_nemov` array from the `sum` run, for the same currents, to `1e-12` relative.
2. Point `pfile` in a copy of `test/python/field_divB0.inp` (line 8) at `vacfield_test.nc` and set line 6 to the new `icftype`; `field_c` must return the same `Brad,Bphi,Bzet` as with `field_test.dat` and `icftype = 4`, to `1e-10` relative.

## Behaviour (BDD)

```gherkin
Scenario: field_c reads an mgrid file
  Given field_divB0.inp line 6 contains icftype = 5
  And field_divB0.inp line 8 names an existing NetCDF file "vacfield_test.nc"
  When field_c(rrr, ppp, zzz, ...) is called for the first time
  Then read_mgrid is used instead of read_field4
  And nr, np, nz, rmin, rmax, pmin, pmax, zmin, zmax in field_c_mod are set from the file
  And pmin = 0, pmax = 2*pi after unrolling nfp field periods

Scenario: mgrid and Nemov plaintext give the same field
  Given the same Nemov coil file and the same &coil_field grid namelist
  When vacfield.x is run once with field_format "sum" and once with "mgrid"
  And field_c is evaluated at 100 fixed points inside the grid box
  Then max relative deviation of (Brad, Bphi, Bzet) is below 1.0e-10

Scenario: write_mgrid stores coil groups separately
  Given two field_mesh_t buffers g1 and g2 and group names ["upper", "lower"]
  When write_mgrid is called with mgrid_mode = "R" and raw_coil_cur = [2.0, 3.0]
  Then the file has nextcur = 2 and external_coil_groups = 2
  And it contains variables br_001, bp_001, bz_001, br_002, bp_002, bz_002
  And read_mgrid on that file returns 2*g1 + 3*g2 to 1.0e-13

Scenario: current rescaling needs no new Biot-Savart run
  Given the file written by the previous scenario
  When raw_coil_cur is overwritten with [1.0, -1.0] and read_mgrid is called again
  Then the returned field equals g1 - g2 to 1.0e-13

Scenario: a foreign SI mgrid file is not silently misread
  Given an mgrid file with no "units" global attribute
  When field_c reads it with icftype = 5
  Then the field is treated as SI and converted to Gauss and cm before vector_potentials
  And a file carrying units = "CGS" is passed through unscaled

Scenario: existing inputs keep working
  Given MEPHIT/data/field_divB0.inp with icftype = 4 and a plaintext field.dat
  When field_c is called
  Then read_field4 is still used and results are unchanged from the current code
```

## Implementation plan

1. **`src/field/mgrid.f90`** — extend `write_mgrid` (`:121`) to multiple groups. Keep the existing signature working: add optional `group_names(:)`, an optional array-valued field argument (or a rank-4 buffer), optional `mgrid_mode`, optional `raw_coil_cur`. When the multi-group arguments are present, set `external_coil_groups` and `nextcur` to `size(group_names)` (replacing the hard-coded `1` at `:168` and `:190`), write the supplied `mgrid_mode` instead of `'S'` (`:197`) and the supplied `raw_coil_cur` instead of `[1.0_dp]`, and emit `br_kkk/bp_kkk/bz_kkk` per group through the existing `def_group` (`:267`) / `put_group` (`:280`) helpers with `group_var_name` (`:374`). The single-group path must stay byte-compatible so `test/field/test_mgrid.f90` and `create_spline_field_from_netcdf` (`src/field/field.f90:112-131`) are untouched.
2. **`src/field/mgrid.f90`** — add an optional `units` global attribute on write, and return it from `read_mgrid` (`:34`) as an optional `character(len=*), intent(out) :: units`, defaulting to `'SI'` when the attribute is absent (standard makegrid output is Tesla/metre). Do **not** convert inside `read_mgrid`; leave conversion to the caller so existing `neo_field` consumers are unaffected.
3. **`src/magfie/coil_tools.f90`** — add `biot_savart_sum_coil_groups(coils, Ic, group_index, Rmin, ..., Bvac_grp)` returning `Bvac(3, nZ, nphi, nR, ngroup)`, factored out of `biot_savart_sum_coils` (`:345-398`) so both share the inner kernel. Add `write_Bvac_mgrid(filename, Rmin, Rmax, Zmin, Zmax, Bvac_grp, group_names, currents, nfp, mgrid_mode)` next to `write_Bvac_nemov` (`:822`), building a `field_mesh_t` per group and calling `write_mgrid`. Export both in the `public` list (`coil_tools.f90:10-19`). Do **not** delete or change `write_Bvac_nemov`.
4. **`src/magfie/coil_tools.f90`** — decide the group mapping. `coils_read_nemov` (`:205-247`) already returns one `coil_t` per coil index `kc`, so the default mapping is one coil = one group and no reader change is required; `coils_read_AUG` (`:156`) and `coils_read_GPEC` (`:277`) likewise map one file / one filament to one group. If a coarser grouping is wanted, add an optional `group_index(:)` argument to `biot_savart_sum_coil_groups` defaulting to `[(k, k = 1, size(coils))]` — do not change the reader signatures, which downstream code calls.
5. **`src/magfie/vacfield.f90`** — add a `field_type == 'mgrid'` branch alongside `'sum'` (`:119-129`) that calls the new routines; add `nfp` and `mgrid_mode` to the `/coil_field/` namelist (`:19-20`) with defaults `nfp = 1`, `mgrid_mode = 'S'`; extend `usage()` (`:150-167`) to document `'mgrid'` and its NetCDF output. Add the new keys to `tools/vacfield_AUG.in`.
6. **`src/magfie/field_divB0.f90`** — add `icftype = 5` to the `field_c` dispatch (`:597-621`), before the `else`/`stop` arm. The branch: `use neo_mgrid, only: read_mgrid`, read into a `field_mesh_t`, unroll the single stored field period into the full `[0, 2*pi]` range that `vector_potentials` expects (repeat `nfp` times; set `pmin = 0`, `pmax = 2*pi`), convert to Gauss/cm when the file's `units` is `'SI'` or absent, fill `nr, np, nz, rmin, ...` in `field_c_mod` (`src/magfie/field_c_mod.f90:8-10`), then hand `Br, Bp, Bz` to `vector_potentials` (`:629`) unchanged. Optionally auto-detect via `is_mgrid_file` (`mgrid.f90:209`) so a `.nc` `pfile` works without changing `icftype`; keep an explicit `icftype` authoritative. **No CMake change is required** — see "CMake is already in place" above; verify by building rather than by pre-emptively editing `src/magfie/CMakeLists.txt`.
7. **`test/field/test_mgrid.f90`** — add `test_write_multigroup` (register the call next to the existing `call test_raw_multigroup` at `:13`). Write two groups through the **new** `write_mgrid` path with `mgrid_mode = 'R'` and `raw_coil_cur = [2.0_dp, 3.0_dp]`, read back with `read_mgrid`, assert the sum equals `2*g1 + 3*g2` to `1e-13`. This is the write-side counterpart of `test_raw_multigroup` (`:176-200`), which already covers reading and must be left alone.
8. **New `test/magfie/test_field_c_mgrid.f90`** — build an analytic field on a coarse grid (e.g. `B = (0, B0*R0/R, 0)` in Gauss/cm), write it through `write_mgrid`, generate a `field_divB0.inp` pointing at it with `icftype = 5` on line 6 and the `.nc` path on line 8, call `read_field_input` then `field_c`, and compare against the analytic value to `1e-8` relative. Register in `test/magfie/CMakeLists.txt` with `add_executable` / `target_link_libraries` / `add_test`, following the `tilted_coil_fourier_modes.x` pattern (`test/magfie/CMakeLists.txt:21-27`).
9. **Downstream** — this is additive, so no downstream change is required. Once MEPHIT is happy with `icftype = 5`, `MEPHIT/data/field_divB0.inp` and `MEPHIT/test/field_divB0.inp` can be migrated in a follow-up PR in that repo; the `downstream-gate` workflow (`.github/workflows/downstream-gate.yml`, gated set in `ci/downstreams`) will catch regressions.

## Acceptance criteria

- [ ] `make && cd build && ctest --output-on-failure` passes with no failures that were not already failing at `fe3f76e`.
- [ ] `ctest -R test_mgrid` passes and now includes a **write-side** multi-group case: `write_mgrid` with `mgrid_mode = 'R'` and two groups produces a file with `nextcur = 2`, `external_coil_groups = 2` and the six variables `br_001..bz_002`, which `read_mgrid` sums correctly. (`test_raw_multigroup` already covers the read side and must still pass.)
- [ ] `ctest -R test_field_c_mgrid` passes; `field_c` with `icftype = 5` matches the analytic reference to `1e-8` relative.
- [ ] `vacfield.x` run twice on the same Nemov coil file and the same grid namelist, once with `field_format = mgrid` and once with `sum`, yields fields agreeing to `1e-12` relative for the same currents.
- [ ] `icftype = 1..4` paths are untouched: `git diff` shows no change to `read_field1`, `read_field2`, `read_field4`, `read_sizes`, or the `icftype <= 4` arms of `field_c`, and `test/python` field tests still pass.
- [ ] `ctest -R "tilted_coil"` still passes (all three tests: `tilted_coil_generate_geometry`, `tilted_coil_fourier_modes`, `tilted_coil_field_validation`).
- [ ] The `downstream-gate` workflow is green for the blocking rows in `ci/downstreams` (SIMPLE, NEO-2, MEPHIT, KAMEL, rabe; NEO-RT is report-only).

## References

- mgrid/makegrid is the STELLOPT/VMEC vacuum-field format; the `mgrid_mode` `'R'`/`'S'` distinction and the per-group `br_kkk/bp_kkk/bz_kkk` variables follow that specification, which VMEC free-boundary, BEAMS3D and FIELDLINES all consume. The libneo-side description of the schema is in the module header at `src/field/mgrid.f90:1-20`.
- VMEC reference: Hirshman & Whitson, "Steepest-descent moment method for three-dimensional magnetohydrodynamic equilibria", *Phys. Fluids* **26**, 3553 (1983), doi:10.1063/1.864116. The free-boundary vacuum-field coupling that `mgrid` feeds: Hirshman, van Rij & Merkel, "Three-dimensional free boundary calculations using a spectral Green's function method", *Comput. Phys. Commun.* **43**, 143 (1986), doi:10.1016/0010-4655(86)90058-5.
- The divergence-free reconstruction from a gridded `B` via `vector_potentials` / `field_divfree` in `src/magfie/bdivfree.f90` is libneo's own. The alternative already supported by `read_mgrid` — store `A` and spline `B = curl A` — is documented at `src/field/mgrid.f90:11-20`. No specific literature reference; this is an implementation detail internal to the code.
- Unit handling (SI in standard makegrid output vs. CGS throughout `coil_tools`, `field_divB0` and `src/field/biotsavart.f90`) is an implementation detail internal to the code; no literature reference.

## Scope and risk

One PR is feasible but tight; splitting into (a) multi-group `write_mgrid` + `vacfield` mgrid output and (b) the `icftype = 5` consumer path in `field_c` gives two reviewable, independently testable PRs, and (a) is a prerequisite for (b).

The main risk is the SI/CGS boundary: a makegrid-produced file is in Tesla and metres while everything on the `field_divB0` side is Gauss and cm, so a dropped `units` attribute is silently wrong by `1e4` in `B` and `1e2` in the grid coordinates. Make the default explicit and assert it in the new test. A second, smaller risk is `write_mgrid`'s backward compatibility — `create_spline_field_from_netcdf` (`src/field/field.f90:112-131`) and `test_roundtrip_b_cyl` (`test/field/test_mgrid.f90:144-173`) both depend on the current single-group output.

Related but distinct: itpplasma/libneo#302 ("g-file convention checks only on the geqdsk_tools path; field_divB0 readers are unvalidated") touches the same reader family and would compose well with this work.
