### ISSUE TITLE
Integrate, document and test VMEC interfaces

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#2]
Created a feature branch, see https://github.com/itpplasma/libneo/tree/vmec and https://github.com/itpplasma/libneo/compare/master...vmec . This feature depends on NetCDF, which I suggest to make a required dependency together with HDF5, since we use the latter for data storage anyway, and both are standard in most environments.

@micheder in case you change or document something in the VMEC interface code, please commit it here, so we will finally have a central place where the interface resides.

Up to now, four files have been added:
```
src/canonical_coordinates_mod.f90
src/nctools_module.f90
src/spline_vmec_data.f90
src/vmecinm_m.f90
```

The `canonical_coordinates_mod.f90` comes from SIMPLE and additionally contains transformation to canonical flux coordinates but also "usual" magnetic field routines for VMEC fields.

### Unification
**Goal: Maintain a single up-to-date version of VMEC field routines in libneo for all codes**
*Non-Goal: Do changes that break compatibility with legacy codes or risk new bugs*

At least the following codes use VMEC input routines:
* https://github.com/itpplasma/GORILLA
* https://github.com/itpplasma/SIMPLE

There has been two important changes in the SIMPLE variant that should be included everywhere:
1) https://github.com/itpplasma/SIMPLE/commit/2e8a410ffc27174778cda1b540d9309a985bbe46 corrects the interpolation of lambda that is added to the poloidal VMEC angle to get the one for symmetry flux coordinates (aka PEST1, see Callen/d'haeseleer p.122). It is given on half-mesh radial points in the VMEC output. **This affects comparisons to old results from codes that used the wrong interpolation**
2) https://github.com/itpplasma/SIMPLE/commit/ac7bcb67a47dd9809dd4c21270ff59492dbc2dac from Matt Landreman supports non-stellarator symmetric equilibria. This is crucial for perturbed tokamak equilibria.

### Testing
**Goal: Have automated unit tests for consistency and against official STELLOPT/libstell routines**
*Non-Goal: Replace our routines by libstell routines. Ours are better :P*

* An example how to test magnetic field components and their derivatives can be found [here](https://github.com/itpplasma/SIMPLE/blob/master/SRC/test_magfie.f90). The idea is to compare computed field derivatives against finite differences with some "meaningful" step size. This is however for other (canonical flux coordinate) field routines so needs to be completely rewritten.
* A draft how to compare our fields against libstell ones is [here](https://github.com/itpplasma/SIMPLE/blob/collisions/SRC/test_vmec.f90)
* An example how to do unit tests in pfunit and GitHub actions for automation is in [Daniel's Bachelor thesis](https://github.com/itpplasma/libneo/files/8478989/Bachelorarbeit_FORTRAN_FINAL.pdf) and implemented in https://github.com/itpplasma/GORILLA .

### Documentation
**Goal: Write API (function headers, doxygen) and user docs (latex? doxygen?) for VMEC routines**
*Non-Goal: Long and detailed docs. Those should rather be referred to VMECwiki*

### Comments
* `magfie.f90` contains magnetic field routines (high-level in group standard)
* `spline_vmec_data.f90` contains code to generate and evaluate splines for VMEC `R, Z, lambda` and field routine `vmec_field` (low-level)
* `splint_vmec_data` evaluates splines in given point. (even lower level)
* 

### TODO
* [ ] Stop writing empty NetCDF file if not existant
* [ ] Test `magfie_vmec` derivatives against finite differences `da/dx ~= (a(x+dx)-a(x-dx))/(2*dx))`
* [ ] Test `vmec_field` derivatives against finite differences
* [ ] Test fields against libstell fields. Extend `test_vmec.f90` towards automated testing. Use sum of absolute value differences and set threshold parameter. 
* [ ] Test `splint_vmec_data` derivatives as lowest level function
* [ ] Automate with pfUnit (see Daniel's bachelor work)
* [ ] Generate coverage (see Daniel's bachelor work)
* [ ] Create GitHub actions (see Daniel's bachelor work)

* [x] Think about relative error in case the reference becomes zero. -> `function relerr`
* [x] Rico: Check how to diff against reformatted code -> `man diff` -> `diff -bB` or else `diff -w`
* [ ] Add `intent(in)` or `intent(out)` wherever possible to arguments
* [ ] Find out from Patrick Lainer how to treat intent of array arguments to be filled with data

* [ ] Add Doxygen documentation wherever possible

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Seven years on, most of this umbrella has landed. The integration and unification goals are done; the CI goal is done; the derivative-testing goals are **not**. Below is an audit of each checklist item against current `main`, then a spec for the part that is still genuinely missing.

**Status audit**

| Original item | Status at `fe3f76e` |
|---|---|
| Files live centrally in libneo | Done — `src/vmec_support/{spline_vmec_data,vmecinm_m,new_vmec_allocation_stuff,canonical_coordinates_mod,vmec_field_tools}.f90`, wired via `src/vmec_support/CMakeLists.txt`. The old top-level paths (`src/spline_vmec_data.f90` etc.) still resolve because they are **symlinks** into `src/vmec_support/` and `src/nctools/`. |
| NetCDF a required dependency | Done — `cmake/BuildExternalDependencies.cmake` builds NetCDF-C 4.9.2 (`:140,144`) and NetCDF-Fortran 4.6.1 (`:186`) from source via `ExternalProject_Add` when not found. |
| SIMPLE fix 1: lambda half-mesh → full-mesh interpolation | Done — `src/vmec_support/vmecinm_m.f90:118-130`, incl. the one-sided extrapolation at `kparb` (`:126-130`) |
| SIMPLE fix 2 (Landreman): non-stellarator-symmetric `lasym` | Done — `src/vmec_support/vmecinm_m.f90:73-74` reads `lasym__logical__`; `:101-117` reads `rmns`/`zmnc`/`lmnc` and zeroes them otherwise |
| Stop writing an empty NetCDF file if not existent | Done — `nc_open` opens with `NF90_NOWRITE` only (`src/nctools/nctools_module.f90:760-771`), and that is what `vmecinm` calls (`src/vmec_support/vmecinm_m.f90:71`) |
| GitHub Actions automation | Done — `.github/workflows/main.yml`: GNU `Release`/`Debug` matrix (`:23-24`), `ctest --output-on-failure` (`:79`), pytest (`:100-101`), an ASCOT5 5.6.1 cross-check (`:103-115`), and a Sphinx docs job (`:132-151`) |
| pfUnit | Not adopted — `rg -i pfunit` over the repo returns **zero hits**. The de-facto idiom, visible in `test/source/*.f90` and `test/CMakeLists.txt`, is a plain `program test_*` that calls `error stop`, registered with `FAIL_REGULAR_EXPRESSION "STOP"`. Follow that; do not introduce pfUnit as part of this issue. (`CODING_STANDARD.md` says only "write tests before code" and "tests are located in folders `test`" — it does not mandate a framework either way.) |
| Coverage | Deliberately removed (`283efb7`, "ci: remove coverage workflow and build flags" — deletes `.github/workflows/test-coverage.yml`, the Codecov upload, and `ENABLE_COVERAGE`). Won't-do. |
| Test `splint_vmec_data` derivatives | **Partial** — only `test/source/test_splint_vmec_data_d3.f90` (d3 vs FD of d2). d1 and d2 are validated by nothing. |
| Test `vmec_field` derivatives | **Missing** — `rg -n 'vmec_field\(' test/` returns no hits |
| Test `magfie_vmec` derivatives | **Missing** — `rg -n magfie_vmec test/` returns no hits |
| Test against libstell fields | **Reframed** — `booz_xform` is the live reference now (`test/source/test_boozmn_reader.f90`, `booz-xform` in the `dev` extra at `pyproject.toml:26-27`), plus `test/source/test_boozer_converter_vs_simple.f90`. libstell is not a dependency of anything here; the only STELLOPT references left are a wout download URL in `tools/plot_chartmap_overlays.py` and prose in `doc/`. |

So the residual, and the only thing this issue should now track, is the **finite-difference validation ladder for the VMEC field routines**.

## Purpose

`magfie_vmec` and `vmec_field` are the bottom of the guiding-centre stack for stellarator runs in this family, and the Boozer converter and chartmap generators sit on `splint_vmec_data`. `magfie_vmec` returns `bder = ∇ln B`, `hcovar`, `hctrvr` and `hcurl` — the quantities that set the mirror force and the drift velocity. An error in any of them does not crash; it silently shifts trapped-particle boundaries and loss fractions. `test_splint_vmec_data_d3` validates third derivatives against the second, but the second and first derivatives themselves are unvalidated, so the whole ladder rests on an untested base. This issue closes that gap.

## Current state

### The spline ladder — `src/vmec_support/spline_vmec_data.f90` (module `spline_vmec_sub`)

- **`splint_vmec_data` (line 654)** — returns R, Z, λ and their nine first derivatives. Splines are stored in `rho_tor = sqrt(s)`; the s-chain-rule is applied at the **end** of the routine, lines 699-710:
  ```fortran
  if (rho_tor > 0.0d0) then
     dR_ds = 0.5d0*dR_ds/rho_tor
     dZ_ds = 0.5d0*dZ_ds/rho_tor
     dl_ds = 0.5d0*dl_ds/rho_tor
  else
     ! Magnetic axis (s=0): d/ds carries the 1/(2*sqrt(s)) coordinate
     ! singularity and is undefined here. [...]
     dR_ds = 0.0d0
     ...
  ```
  That `1/(2*sqrt(s))` factor is exactly the kind of thing an FD test catches and nothing currently does. Note the `s = 0` branch returns **zero** s-derivatives by design — do not place a test point at or near `s = 0`.
- **`splint_vmec_data_d2` (line 716)** — same outputs plus `d2R(6), d2Z(6), d2l(6)`, documented at `:722` as packed `(ss, st, sp, tt, tp, pp)`.
- **`splint_vmec_data_d3` (line 856)** — third derivatives; the only routine with a test.
- **`vmec_field` (line 988)** — thin composition, `splint_vmec_data` (`:1001`) then `compute_field_components` (`:1004`). **It does not return `bmod`** — see the formula in the verification recipe below.
- **`compute_field_components` (line 1013)** — the physics content, via `metric_tensor_symflux` (line 1038):
  ```fortran
  Bctrvr_vartheta = -dA_phi_ds/sqg
  Bctrvr_varphi = dA_theta_ds/sqg
  Bcovar_s = g(1, 2)*Bctrvr_vartheta + g(1, 3)*Bctrvr_varphi
  ```
- **`splint_iota` (line 1214)** — independent `aiota(s)` evaluation, usable as a cross-check.

### `src/magfie/magfie_vmec.f90` — read this before writing its test

`magfie_vmec` is a bare `subroutine` at line 2 (not in a module), spanning lines 2-167. It is a source of `magfie` (`src/magfie/CMakeLists.txt:25`) and is also compiled into the f2py `_magfie` Python extension (`CMakeLists.txt:527,538`).

**Critical for spec'ing its test: `magfie_vmec` has no analytic derivatives at all.** It computes `bder` by central-differencing `vmec_field` itself, with hardcoded steps at line 32:
```fortran
real(dp), parameter :: hs=1.d-3, ht=hs*TWOPI, hp=ht/5.d0
```
i.e. six `vmec_field` calls at `x ± h e_k` (lines 49, 63, 82, 96, 115, 129), assembled at lines 71, 104, 137, then normalised at line 153 (`bder = bder/bmod`). The auxiliary quantities `dht_ds, dhp_ds, dhs_dt, dhp_dt, dhs_dp, dht_dp` are built the same way and feed `hcurl` at lines **163-165**:
```fortran
hcurl(1)=(dhp_dt-dht_dp)/sqrtg
hcurl(2)=(dhs_dp-dhp_ds)/sqrtg
hcurl(3)=(dht_ds-dhs_dt)/sqrtg
```
The remaining outputs are at lines 150-162: `bmod` (`:150`), `sqrtg = sqg*cjac` with `cjac = 1+dl_dt` (`:151-152`), `hcovar` (`:157-159`), `hctrvr` (`:160-162`, with `hctrvr(1)` **assigned literal `0.d0`**).

**Consequence, and the main correction to the naive plan:** re-differencing `vmec_field` in a test and comparing against `bder` is *not an independent oracle* — it re-runs the production algorithm with a different step size. It can detect step-size sensitivity and non-smoothness, but it cannot detect a sign or transform error, because the same `vmec_field` output feeds both sides. Treat that check as a regression/convergence guard and get the real validation from the exact identities and the symmetry check below. The genuinely independent oracle for `bder` would be an analytic gradient built from `splint_vmec_data_d2`; that is a larger piece of work and is deliberately **out of scope** here (noted as a follow-up).

### Fixture

`test/scripts/setup_vmec_wout.py` downloads `wout_LandremanPaul2021_QA_reactorScale_lowres_reference.nc` from the hiddenSymmetries/simsopt `tests/test_files/` tree (`:17-20`), sha256-pinned (`:21`), to `<build test dir>/wout.nc` (`:64`). `test/CMakeLists.txt:365-369` registers it as the `setup_vmec_wout` fixture test. Reuse it — do not add a new fixture for the symmetric cases.

## Reproduction / evidence

There is no failing behaviour to reproduce; this is a coverage hole. Demonstrate it, then close it:

```bash
cd /path/to/libneo
make                                    # cmake --preset default && cmake --build --preset default
cd build && ctest -N | grep -i vmec
rg -n 'magfie_vmec|vmec_field\(' test/  # exits 1, no hits — this is the gap
```
The existing VMEC-touching tests are `test_vmec_modules`, `test_vmec_coordinate_system`, `test_vmec_from_cyl`, `test_splint_vmec_data_d3`, `test_vmec_chartmap_generator`, `test_chartmap_matches_vmec`, `test_chartmap_vmec_mapping` (`test/CMakeLists.txt:284,509,527,518,491,548,621`) — none of them calls `magfie_vmec` or `vmec_field`.

**Verification recipe for the new tests.** Work in the ctest working directory so `wout.nc` resolves; set `netcdffile = "wout.nc"` and call `spline_vmec_data` first, exactly as `test/source/test_splint_vmec_data_d3.f90:19-20` does. Reuse that test's evaluation points verbatim (`:22-24`), which are known-good interior points:

```fortran
stor = [0.3_dp, 0.5_dp, 0.6_dp, 0.7_dp]
tt   = [0.4_dp, 1.7_dp, 2.9_dp, 0.9_dp]
pp   = [0.2_dp, 0.9_dp, 1.6_dp, 2.4_dp]
```

`vmec_field` does not return the field modulus. Compute it the way `magfie_vmec:150` does:
```fortran
bmod = sqrt(Bctrvr_vartheta*Bcovar_vartheta + Bctrvr_varphi*Bcovar_varphi)
```
(valid because `B^s = 0`, so `B² = B_i B^i` reduces to these two terms).

Ranked by how much each check actually proves:

1. **Exact identity, no tolerance guesswork — the highest-value check.** `dot_product(hcovar, hctrvr) == 1` to `1e-12`, because `h_i h^i = B_i B^i / B² = 1`. This is non-trivial: `hcovar` and `hctrvr` are built through *different* λ-transform branches (`magfie_vmec:154-159` vs `:160-162`), so the identity only holds if the covariant and contravariant transforms of the VMEC→symmetry-flux angle change are mutually consistent. It catches a sign or `cjac` error in either branch immediately and needs no finite differences.
2. **Stellarator symmetry.** The pinned fixture is stellarator-symmetric, so `B(s, -θ, -φ) = B(s, θ, φ)`. Therefore `bder(1)` is even and `bder(2), bder(3)` are odd under `(θ,φ) → (-θ,-φ)`. This uses only `magfie_vmec` against itself, requires no analytic reference, and *does* catch sign errors — it is the closest thing to an independent check available at reasonable cost. (`lasym` is a local variable in `vmecinm_m.f90:56` and is not exported, so the test cannot query it; the property is asserted on the pinned fixture and the assertion itself is what would fail if the fixture were ever swapped for an asymmetric one.)
3. **`hctrvr(1) == 0` exactly** (`magfie_vmec:160`) — `B·∇s = 0` on a flux surface. This is a literal constant assignment, so it is a change-detector, not a physics check. Cheap; keep it, label it as such.
4. **FD regression/convergence guard.** `bder(k)` vs `(log B(x+h e_k) - log B(x-h e_k))/(2h)` recomputed from `vmec_field`. Not independent (see above). Gate loosely: production uses `hs=1e-3, ht≈6.28e-3, hp≈1.26e-3`, the test uses different steps, and the residual is dominated by the *difference* of two O(h²) truncation errors. `1e-3` relative with a `1e-6` absolute floor is the right order; do not tighten. Additionally assert Richardson behaviour — halving the test step must shrink the discrepancy toward the production-step truncation floor, not grow it — which does have real diagnostic power on spline smoothness.
5. **Jacobian consistency.** `sqrtg` from `magfie_vmec` equals `sqg*(1 + dl_dt)` from `vmec_field` at the same point to round-off — literally `magfie_vmec:151-152`. Change-detector; keep it as an assertion in the `vmec_field` test.

Note that checks 1-3 on `splint_vmec_data`'s d1 and d2 (comparing an analytic spline derivative against an FD of the interpolated value) **are** genuinely independent — the derivative comes from a separate spline evaluation, not from differencing. Those are the highest-value new tests in this issue.

## Behaviour (BDD)

```gherkin
Scenario: splint_vmec_data first derivatives match finite differences of R, Z, lambda
  Given build/test/wout.nc is present (fixture test setup_vmec_wout has run)
  And netcdffile = "wout.nc" and spline_vmec_data has been called
  When test_splint_vmec_data_d1.x evaluates splint_vmec_data at the four points
       (s, theta, varphi) = (0.3,0.4,0.2), (0.5,1.7,0.9), (0.6,2.9,1.6), (0.7,0.9,2.4)
       and central-differences R, Z, alam with hs=1e-4, ht=1e-3, hp=1e-3
  Then every one of dR_ds, dR_dt, dR_dp, dZ_ds, dZ_dt, dZ_dp, dl_ds, dl_dt, dl_dp
       agrees with its finite difference to relative 1e-4 with absolute floor 1e-7
  And the executable exits 0 without printing "STOP"

Scenario: splint_vmec_data_d2 matches finite differences of splint_vmec_data
  Given the same fixture and the same four evaluation points
  When test_splint_vmec_data_d2.x central-differences the nine first derivatives
       returned by splint_vmec_data and compares against d2R, d2Z, d2l
       packed (ss,st,sp,tt,tp,pp)
  Then each of the 18 components agrees to relative 5e-4 with absolute floor 1e-5
  And the mixed component d2*(2) is compared against BOTH finite-difference routes
       (d/ds of d*_dt and d/dt of d*_ds) at that same 5e-4 / 1e-5 gate
       # d2*(2) is one stored number, so the two routes cannot disagree with each
       # other more than each disagrees with it; do not assert a tighter
       # FD-vs-FD tolerance, it is not achievable at these step sizes

Scenario: magfie_vmec returns a mutually consistent unit vector along B
  Given build/test/wout.nc and netcdffile = "wout.nc"
  When magfie_vmec is called at x = (0.5, 1.7, 0.9)
  Then abs(dot_product(hcovar, hctrvr) - 1.0d0) < 1.0d-12
  And abs(hctrvr(1)) < 1.0d-14
  And bmod > 0
  And all of the above hold at all four evaluation points

Scenario: magfie_vmec respects stellarator symmetry of the pinned fixture
  Given build/test/wout.nc, whose equilibrium is stellarator-symmetric
  When magfie_vmec is called at (s, theta, varphi) and at (s, -theta, -varphi)
       for each of the four evaluation points
  Then bmod agrees between the two calls to relative 1e-10
  And bder(1) agrees to relative 1e-8
  And bder(2) and bder(3) agree with the negatives of their mirrored values
       to relative 1e-8 with absolute floor 1e-10

Scenario: magfie_vmec bder tracks the finite-difference logarithmic gradient
  Given build/test/wout.nc and the four evaluation points above
  When bmod is recomputed from vmec_field at x +/- h e_k as
       sqrt(Bctrvr_vartheta*Bcovar_vartheta + Bctrvr_varphi*Bcovar_varphi)
       with hs=1e-4, ht=1e-3, hp=1e-3
  Then bder(k) agrees with (log(bmod_plus) - log(bmod_minus))/(2*h_k)
       to relative 1e-3 with absolute floor 1e-6 for k = 1, 2, 3
  And repeating with the step halved does not increase the discrepancy
  # This is a regression and smoothness guard, not an independent oracle:
  # magfie_vmec computes bder by this same central difference of vmec_field.

Scenario: vmec_field reproduces the VMEC Jacobian and flux-surface constraint
  Given build/test/wout.nc
  When vmec_field is called at the four evaluation points
  Then sqg is nonzero and of one consistent sign across all four points
  And Bctrvr_vartheta*Bcovar_vartheta + Bctrvr_varphi*Bcovar_varphi > 0
  And the aiota returned matches splint_iota at the same s to relative 1e-12
  And magfie_vmec's sqrtg at the same point equals sqg*(1 + dl_dt) to relative 1e-12
```

## Implementation plan

1. **Create `test/source/test_splint_vmec_data_d1.f90`.** Model it directly on `test/source/test_splint_vmec_data_d3.f90` — same header comment style, same `netcdffile = "wout.nc"` / `call spline_vmec_data` preamble (`:19-20`), same evaluation-point arrays (`:22-24`), same `check_point` + `failed` accumulator structure (`:26-31`), same `error stop` on failure. `use spline_vmec_sub, only: spline_vmec_data, splint_vmec_data` and `use new_vmec_stuff_mod, only: netcdffile`. Central-difference R, Z, `alam` in each of s, θ, φ and compare against the nine returned first derivatives. Parameters `reltol = 1.0e-4_dp`, `floor = 1.0e-7_dp`, declared as `real(dp), parameter` at the top as at `test_splint_vmec_data_d3.f90:13`.
2. **Create `test/source/test_splint_vmec_data_d2.f90`.** Same shape, `use spline_vmec_sub, only: spline_vmec_data, splint_vmec_data, splint_vmec_data_d2`. Differentiate the first derivatives from `splint_vmec_data` and compare against the 6-component `d2R/d2Z/d2l` arrays, packed `(ss,st,sp,tt,tp,pp)` per `spline_vmec_data.f90:722`. `reltol = 5.0e-4_dp`, `floor = 1.0e-5_dp`.
3. **Create `test/source/test_vmec_field.f90`.** `use spline_vmec_sub, only: spline_vmec_data, vmec_field, splint_vmec_data, splint_iota`. Implement the last scenario. Compute `bmod` with the formula above; `vmec_field` does not return it.
4. **Create `test/source/test_magfie_vmec.f90`.** `magfie_vmec` is a bare `subroutine`, not in a module (`src/magfie/magfie_vmec.f90:2`), so declare an explicit `interface` block in the test program rather than a `use`. Its signature is `magfie_vmec(x, bmod, sqrtg, bder, hcovar, hctrvr, hcurl)` with `real(dp), intent(in) :: x(3)`, `intent(out) :: bmod, sqrtg` and `intent(out), dimension(3) :: bder, hcovar, hctrvr, hcurl` (`:34-41`). Set `netcdffile` and call `spline_vmec_data` first, as in step 1. Implement the unit-vector, stellarator-symmetry, and FD-guard scenarios.
5. **Wire all four into `test/CMakeLists.txt`**, copying the `test_splint_vmec_data_d3` block at lines 516-523 verbatim per test:
   ```cmake
   add_executable(test_magfie_vmec.x source/test_magfie_vmec.f90)
   target_link_libraries(test_magfie_vmec.x neo)
   add_test(NAME test_magfie_vmec
     COMMAND test_magfie_vmec.x)
   set_tests_properties(test_magfie_vmec PROPERTIES
     FAIL_REGULAR_EXPRESSION "STOP"
     WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
     DEPENDS setup_vmec_wout)
   ```
   The `test_magfie_vmec.x` target must additionally link the `magfie` library, since `magfie_vmec.f90` is a source of that target (`src/magfie/CMakeLists.txt:25`) and not of `neo`; add `magfie` to `target_link_libraries` for that one test and confirm at configure time. **No `LIBNEO_BUILD_NUMERICS` guard is needed:** `CMakeLists.txt:363-365` does an unconditional `return()` when that option is off, and `add_subdirectory(test)` is at `CMakeLists.txt:451`, i.e. after the return — the entire test tree is already excluded in a light-consumer configure.
6. **Out of scope, spin out as separate issues.** Do not bundle either of these:
   - *An asymmetric (`lasym = T`) fixture.* Nothing in CI currently exercises the `rmns`/`zmnc`/`lmnc` branch at `src/vmec_support/vmecinm_m.f90:101-108`; it is dead code under test. Adding it means finding and sha256-pinning a suitable public asymmetric `wout` (I have not confirmed one exists in the simsopt test-file tree — check before promising it), extending `validate_wout` in `test/scripts/setup_vmec_wout.py:32-35` beyond its current `nfp`-only check, and registering a second fixture test next to `test/CMakeLists.txt:365`. Note also that `lasym` is currently a local variable (`vmecinm_m.f90:56`) and would need exporting for a test to assert on it.
   - *An analytic gradient oracle for `bder`* built from `splint_vmec_data_d2`, which is the only way to make the `bder` check genuinely independent of the routine it tests.
7. **Test-only PR.** Do not modify anything under `src/` in this PR. If a new test fails, that is a real finding: open a separate bug and fix it separately, so the downstream gate failure is attributable. (Note: `src/spline_vmec_data.f90`, `src/vmecinm_m.f90`, `src/nctools_module.f90` and `src/canonical_coordinates_mod.f90` are symlinks to the real files under `src/vmec_support/` and `src/nctools/` — editing either path edits the same file.)

## Acceptance criteria

- [ ] `make && cd build && ctest --output-on-failure -R 'vmec'` passes with `test_splint_vmec_data_d1`, `test_splint_vmec_data_d2`, `test_vmec_field`, `test_magfie_vmec` all present and green.
- [ ] `rg -n 'magfie_vmec' test/` and `rg -n 'vmec_field\(' test/` each return at least one hit (both return zero today).
- [ ] `abs(dot_product(hcovar, hctrvr) - 1)` < 1e-12 and `abs(hctrvr(1))` < 1e-14 at all four evaluation points.
- [ ] The stellarator-symmetry assertions on `bmod` and `bder` pass at all four evaluation points.
- [ ] `bder` matches the finite-difference logarithmic gradient to relative 1e-3 / absolute floor 1e-6 in all three directions, and the discrepancy does not grow when the test step is halved.
- [ ] The `splint_vmec_data` d1 and d2 FD comparisons pass at their stated tolerances at all four points.
- [ ] Each new test declares its tolerances as named `real(dp), parameter` at the top of the program, as `test_splint_vmec_data_d3.f90:13` does — no magic numbers inline.
- [ ] No change to any file under `src/` in the same PR.
- [ ] Existing pinned tests unchanged and passing: `test_boozer_converter_vs_simple`, `test_splint_vmec_data_d3`, `test_chartmap_matches_vmec`, and the ASCOT5 cross-comparison in CI.

## Scope and risk

Steps 1-5 are one focused test-only PR: four new test programs plus CMake wiring. Risk to the library is zero; the cost is CI time, since each test re-splines the wout. The one real hazard is tolerance choice — `magfie_vmec` computes its own derivatives by central differences with hardcoded `hs = 1e-3` (`src/magfie/magfie_vmec.f90:32`), so `bder` carries its own truncation error and cannot be gated much tighter than ~1e-3 relative without changing the production routine, which is explicitly out of scope here.

The honest expected value of this work: the `splint_vmec_data` d1/d2 tests are genuine independent validation and are the reason to do this. The `magfie_vmec` tests are one strong consistency identity, one symmetry check, and two change-detectors — worth having, but they do not fully discharge the original TODO's intent of validating derivatives against an independent reference. Say so in the PR rather than overclaiming.

## Related work

`magfie_vmec` and the VMEC spline ladder are consumed by SIMPLE and GORILLA, and mirrored by the Python port in pyrabe; the asymmetric-fixture and analytic-oracle follow-ups from step 6 touch that same surface. Cross-references to specific sibling issue numbers are omitted here because they could not be verified against the checkout — link them by hand when filing the follow-ups.

## References

- S. P. Hirshman and J. C. Whitson, *Steepest-descent moment method for three-dimensional magnetohydrodynamic equilibria*, Phys. Fluids **26**, 3553 (1983) — the VMEC formulation, including the half-mesh storage of λ that fix (1) in the original issue text corrects.
- W. D. D'haeseleer, W. N. G. Hitchon, J. D. Callen, J. L. Shohet, *Flux Coordinates and Magnetic Field Structure*, Springer (1991) — symmetry-flux (PEST) coordinates and the `vartheta = theta + lambda` construction, p. 122 as cited in the issue.
- A. H. Boozer, *Plasma equilibrium with rational magnetic surfaces*, Phys. Fluids **24**, 1999 (1981) — the Boozer angles the downstream converter targets.
- M. Landreman and E. Paul, *Magnetic fields with precise quasisymmetry for plasma confinement*, Phys. Rev. Lett. **128**, 035001 (2022) — the QA configuration whose `wout` is the pinned test fixture (`test/scripts/setup_vmec_wout.py:17-21`).
- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Symplectic integration with non-canonical quadrature for guiding-center orbits in magnetic confinement devices*, J. Comput. Phys. **403**, 109065 (2020) — the SIMPLE guiding-centre stack that consumes `vmec_field`.
- **booz_xform** (hiddenSymmetries) is the reference implementation for the VMEC→Boozer transform and is already a `dev` dependency here (`pyproject.toml:26-27`).

Beyond the references above, the specific tolerances and step sizes in this spec have no external literature basis; they are implementation details internal to this code, chosen to sit safely above the O(h²) truncation floor of the existing routines.

**Recommendation:** retitle this issue to *"Finite-difference validation for the VMEC field ladder (`splint_vmec_data` d1/d2, `vmec_field`, `magfie_vmec`)"*, drop the completed and superseded checklist items, and spin the two step-6 items out as separate issues.
