### ISSUE TITLE
Check maybe undefined behavior 

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#20]
https://github.com/itpplasma/libneo/blob/d55908cc0b827707874e5ffea7e6ad500869a2b8/src/magfie/field_divB0.f90#L914

Zw and Rw are never initialized and it is not obviously guaranteed that the branches that do this will be hit in any case.

**Comment by pazathoth** [comment]
Maybe skip the re-interpolation to 360 elements entirely?

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still valid. Seven commits have touched `stretch_coords` since the linked `d55908c` (`e57e176`, `a739e5a`, `6eade7c`, `c874819`, `2e9c92d`, `115e68f`, `78e0dc3`), but the resampling loop itself — `field_divB0.f90:871-892`, the code this issue is about — is **byte-identical** to `d55908c` (verified by diffing the extracted loop). Only the declaration line changed, from `real(kind=real_kind)` to `real(dp)`. `test/field/test_stretch_coords.f90` covers the 150-point-allocation and empty-file paths only, not this. While verifying I found one further defect in the same 20 lines that is reachable from ordinary input and is considerably more severe than the reported one, plus a systematic accuracy loss inherent to the resampling. The reporter's follow-up suggestion ("skip the re-interpolation to 360 elements entirely") is the fix for all of them at once.

## Purpose

`stretch_coords` is the geometric guard that keeps EFIT field evaluation bounded: any point outside the convex wall is pulled back to `rho_c + delta*atan((rho-rho_c)/delta)` so the g-file spline is never extrapolated far outside its box (`src/magfie/field_divB0.f90:907-911`). It sits on the hot path — called once per field evaluation from `field` (`field_divB0.f90:70`), per grid point in the triple loop of `vector_potential_biot_savart_fourier` (`src/magfie/coil_tools.f90:511`), and in `bdivfree.f90:75` — so a wrong `rho_c` silently distorts the vacuum-field extension. The wall radius should be exact, not sampled.

## Current state

`src/magfie/field_divB0.f90:803-998`. On first call the routine reads the convex wall, sorts the points by poloidal angle about `R0 = (max(R)+min(R))/2`, then resamples the wall radius onto a fixed 360-point angular grid (`nrhotht=360`, line 815):

```fortran
    htht = TWOPI/(nrhotht-1)
    do i=2,nrhotht
      tht_wall(i) = htht*(i-1)
      do j=0,nrz
        if(tht_wall(i).ge.tht_w(j) .and. tht_wall(i).le.tht_w(j+1)) then
          if( abs((rad_w(j+1) - rad_w(j))/rad_w(j)) .gt. 1.e-3) then
            a = (zet_w(j+1) - zet_w(j))/(rad_w(j+1) - rad_w(j))
            b = zet_w(j) - a*(rad_w(j) - R0)
            Rw = b/(tan(tht_wall(i)) - a) + R0
            Zw = a*(Rw - R0) + b
          else
            a = (rad_w(j+1) - rad_w(j))/(zet_w(j+1) - zet_w(j))
            b = rad_w(j)-R0 - a*zet_w(j)
            Zw = b/(1./tan(tht_wall(i)) - a)
            Rw = a*Zw + b + R0
          end if
        end if
      end do
      rho_wall(i) = sqrt((Rw-R0)**2 + Zw**2)
    end do
```

`Rw`/`Zw` are plain locals declared at line 817 with no initialiser and no `save`. Three defects, in ascending order of how much they actually matter.

**(a) the reported one — real but latent.** Nothing guarantees the `j` loop assigns `Rw`/`Zw`; line 889 consumes them unconditionally. There is no `exit` on match, so when several `j` bracket the same angle the *last* one silently wins.

Being honest about reachability: I checked the repo's own `test/resources/convexwall.dat` and every one of the 359 grid angles gets exactly one bracketing `j` — no misses, no double matches. For a well-formed star-shaped wall the sorted `tht_w(0:nrz+1)` does cover `[0, TWOPI]`, so in exact arithmetic a match always exists. **This is a latent robustness bug, not an observed failure.** What makes it worth fixing is that nothing in the loader enforces star-shapedness or rejects a point at the centre, and the compiler cannot see the invariant either (`-Wall -Wextra` is on in Debug, `CMakeLists.txt:150-151`).

**(b) 0/0 on degenerate segments — latent, requires an exact-angle coincidence.** Both convex-wall fixtures in this repo close the polygon by repeating the first point: `test/resources/convexwall.dat` line 1 == line 5, `python/scripts/convexwall.asdex` line 1 == line 40. After sorting, the duplicate pair is a zero-length segment with `rad_w(j+1)==rad_w(j)`, so the `else` branch would compute `a = 0.0/0.0`.

Being honest about reachability again: **this does not fire on either fixture in the repo today, and does not crash Debug CI.** The division is guarded by the bracket test, so it executes only when a grid angle lands *exactly* on the duplicated node. For `convexwall.dat` the duplicate sits at `tht = 4.18911`, and `4.18911/htht = 239.35` — not an integer, so it is skipped. I verified this by simulation: zero degenerate hits across all 359 angles. Triggering it takes a hand-built fixture (below). Treat this as hardening that comes free with the rewrite, not as a live crash.

**(c) wraparound extrapolation at the outboard midplane — this one is live and severe.** Lines 901-905:

```fortran
  tht = atan2(z,(r-R0))
  if(tht .lt. 0.) tht = tht + TWOPI
  i = modulo(int(tht/htht), nrhotht-1) + 1
  rho_c = (rho_wall(i+1) - rho_wall(i))/(tht_wall(i+1) - tht_wall(i))   &
       *(tht - tht_wall(i)) + rho_wall(i)
```

For a point marginally below the midplane on the outboard side, `atan2` returns a magnitude far below half an ulp of `TWOPI` (`≈7e-16`), so `tht + TWOPI` rounds to exactly `TWOPI`. Then `int(tht/htht) = 359`, `modulo(359,359) = 0`, `i = 1`, and the interpolation extrapolates from `tht_wall(1) = 0` all the way to `2π` — 359 grid cells outside the bracket. No coincidence required: this hits an entire sliver of ordinary input.

## Reproduction / evidence

All numbers below are against `test/resources/convexwall.dat` (a rectangle `R ∈ [10,160]`, `Z ∈ [-130,140]`, hence `R0 = 85`, units cm). I reimplemented lines 871-905 verbatim to obtain them; they can be reproduced against the real routine by linking a driver to `field_sub`.

**(c), the live defect.** Point at `r = 160.0`, `z = -1.0e-17`, i.e. on the outboard wall:

```
  tht   = 6.283185307179586   (== TWOPI exactly)
  i     = 1
  rho_c = 79.12431653   <-- computed
  rho_c = 75.0          <-- correct (wall is the vertical line R = 160)
```

5.5 % too large; the wall is reported 4.12 cm further out than it is, so points in `75 <= rho < 79.124` are not stretched at all and the g-file spline is evaluated outside the wall. The mirror-image point `z = +1.0e-17` returns exactly 75.0, so the field is discontinuous across the outboard midplane.

**Systematic error from the resampling itself.** At the `(160,140)` corner (`tht = 1.0789871508`, true `rho = 158.8238017`), the table holds `rho_wall(62) = 155.5326965` and `rho_wall(63) = 158.3068102`; linear interpolation yields `157.3349931` — **0.94 % low**. Every corner of every wall is cut this way. The error is second-order in `htht` at smooth points but first-order at corners, so raising `nrhotht` does not cheaply remove it.

**(b), only with a constructed fixture.** Six lines, the last point deliberately duplicated *and* placed at exactly the grid angle `3*htht = 0.05250572680094361`:

```
 1.60000000000000000e+02  0.00000000000000000e+00
 1.20000000000000000e+02 -6.00000000000000000e+01
 1.00000000000000000e+01  0.00000000000000000e+00
 4.00000000000000000e+01  6.00000000000000000e+01
 1.04972437819473512e+02  1.04963210091159809e+00
 1.04972437819473512e+02  1.04963210091159809e+00
```

I verified `atan2(1.04963210091159809, 104.972437819473512 - 85.0)` compares bit-equal to `3*htht`, so at `i = 4` the bracket test selects the zero-length segment and evaluates `a = 0.0/0.0`. Under `-DCMAKE_BUILD_TYPE=Debug` that is an invalid operation and `-ffpe-trap=invalid,zero,overflow` (`CMakeLists.txt:158`) turns it into SIGFPE. The nearly-degenerate case (`|ΔR|/R < 1e-3` with `ΔZ` exactly 0) divides by zero for the same reason.

## Behaviour (BDD)

```gherkin
Scenario: exact wall radius at a polygon corner
  Given convexfile = "test/resources/convexwall.dat"
  When wall_radius is queried at tht = atan2(140.0_dp, 75.0_dp)
  Then the result equals sqrt(75.0_dp**2 + 140.0_dp**2) = 158.8238017426859
   And the relative error is below 1.0e-12
   # today: 157.3349931, 0.94 % low

Scenario: no discontinuity across the outboard midplane
  Given convexfile = "test/resources/convexwall.dat"
  When stretch_coords is called at (r,z) = (160.0_dp, -1.0e-17_dp)
   And stretch_coords is called at (r,z) = (160.0_dp, +1.0e-17_dp)
  Then both calls return rm within 1.0e-10 of each other
   And the implied rho_c equals 75.0_dp within 1.0e-12 relative
   # today: 79.12431653 vs 75.0

Scenario: duplicated wall point on an exact grid angle raises no FP exception
  Given convexfile = "test/resources/convexwall_duplicate_node.dat"
    And the build was configured with CMAKE_BUILD_TYPE=Debug (-ffpe-trap=invalid,zero,overflow)
  When stretch_coords is called at (r,z) = (140.0_dp, 5.0_dp)
  Then the program does not abort
   And rm, zm are finite (ieee_is_finite)

Scenario: malformed wall is rejected loudly instead of silently
  Given a convex wall file whose every point coincides with the centre R0
  When stretch_coords loads it
  Then the program calls error stop with a message naming the offending point
```

## Implementation plan

1. **Create `src/magfie/convex_wall.f90`**, `module convex_wall`, `implicit none`, `use libneo_kinds, only: dp` (`src/libneo_kinds.f90:19`) and `use math_constants, only: TWOPI` (`src/util/math_constants.f90:11`). Public: `type :: convex_wall_t` with components `integer :: npoint`, `real(dp) :: R0`, `real(dp), allocatable :: x(:), y(:), tht(:)` — where `x = rad - R0`, `y = zet`, index range `1:npoint+1` with the wrap point appended (`x(npoint+1) = x(1)`, `tht(npoint+1) = tht(1) + TWOPI`). Per `CODING_STANDARD.md:15` ("`public` data, procedures live outside"), keep the procedures outside the type.
2. **In the same file, `subroutine load_convex_wall(wall, filename)`**: lift `count_data_points`, `validate_data_count`, `read_data_points`, `compute_polar_coords` out of the `contains` block of `stretch_coords` (`field_divB0.f90:913-996`) to module scope, then add the validation the current code lacks — drop consecutive duplicates after sorting, `error stop` if fewer than 3 distinct points remain, `error stop` if any point satisfies `hypot(x,y) < 1.0e-10_dp` (a point at the centre zeroes the wall radius over a whole sector). Dropping duplicates is what makes defect (b) unreachable by construction. Keep the existing bubble sort or use an index sort; either is fine at `npoint ~ 10^2`.
3. **In the same file, `pure function wall_radius(wall, tht_in) result(rho_c)`**. Normalise `tht_in` into `[wall%tht(1), wall%tht(1)+TWOPI)` with `modulo` — this is what kills defect (c), since `modulo` has no wraparound cliff — then binary-search `wall%tht` for the bracketing `j` and intersect the ray with the segment in cross-product form. **No `tan`, no `1./tan`, no branch on segment orientation**:
   ```fortran
   ex = wall%x(j+1) - wall%x(j)
   ey = wall%y(j+1) - wall%y(j)
   den = cos(tht)*ey - sin(tht)*ex
   rho_c = (wall%x(j)*ey - wall%y(j)*ex) / den
   ```
   `den` vanishes only if the segment is collinear with the ray, i.e. the segment passes through the centre — excluded by step 2, but assert `abs(den) > 0` and `error stop` otherwise. This is exact for the polygon, so scenarios 1 and 2 pass by construction and the corner-cutting error disappears.
4. **Rewrite `stretch_coords` in `src/magfie/field_divB0.f90:803-998`** keeping only: the double-checked `icall`/`!$omp critical` lazy init (lines 830-833, unchanged), `call load_convex_wall(wall, convexfile)`, then `rho = hypot(r-R0, z)`, `tht = atan2(z, r-R0)`, `rho_c = wall_radius(wall, tht)`, and the existing stretching block at lines 907-911. Delete `nrhotht`, `rho_wall`, `tht_wall`, `htht`, `Rw`, `Zw`, `a`, `b`, `iflag`, `dummy` and the whole `contains` block. Keep `delta = 1.0_dp` and the `rm`/`zm` semantics identical. The `save`d `wall` replaces the `save`d tables.
5. **Wire the build in *two* places** — this is easy to miss:
   - `src/magfie/CMakeLists.txt`: add `convex_wall.f90` to the `add_library(magfie STATIC ...)` source list, **before** `field_divB0.f90` (currently line 11) so the module compiles first.
   - `src/efit_to_boozer/CMakeLists.txt:135`: this `add_custom_command` feeds `src/magfie/field_divB0.f90` to `numpy.f2py` directly. Add `"${CMAKE_SOURCE_DIR}/src/magfie/convex_wall.f90"` ahead of it in that argument list, or the `_efit_to_boozer` Python extension fails to build on the missing module.
   (Note: there is no `src/CMakeLists.txt` in this repo; the per-directory files above are the only two consumers — confirmed with `grep -rn field_divB0 --include=CMakeLists.txt .`)
6. **Add fixture `test/resources/convexwall_duplicate_node.dat`** with the six lines quoted under Reproduction. Leave `test/resources/convexwall.dat` alone — its repeated closing point is legitimate input the loader must handle, not something to silently drop from the fixture.
7. **Extend `test/field/test_stretch_coords.f90`** with four new subroutines, one per BDD scenario, leaving `test_stretch_coords_large_file` and `verify_empty_file_failure` unchanged. Use `util_for_test`'s `print_test`/`print_ok`/`print_fail` and `error stop` as the existing tests do. Scenario 4 needs the same out-of-process `execute_command_line` trick as `verify_empty_file_failure` (`test_stretch_coords.f90:91-121`), since it must observe an `error stop`. No new `add_test` entry is needed — `test/field/CMakeLists.txt:59-63` already registers the executable.
8. **Optionally add `test/field/test_convex_wall.f90`** exercising `wall_radius` against an analytic circle: for a regular `n`-gon inscribed in a circle of radius `a`, `a*cos(pi/n) <= wall_radius(tht) <= a` for all `tht`, with equality at the vertices. Register with `add_executable`/`add_test` in `test/field/CMakeLists.txt` next to the existing entries.

## Acceptance criteria

- [ ] `cmake -S . -B build -G Ninja && cmake --build build && cd build && ctest --output-on-failure` passes.
- [ ] Same with `-DCMAKE_BUILD_TYPE=Debug`, with **no SIGFPE** (this is where `-ffpe-trap=invalid,zero,overflow` bites).
- [ ] `wall_radius` at `atan2(140,75)` on `test/resources/convexwall.dat` returns `158.8238017426859` to `1e-12` relative (today: `157.3349931`, 0.94 % low).
- [ ] `stretch_coords(160.0_dp, -1.0e-17_dp, rm, zm)` and `stretch_coords(160.0_dp, +1.0e-17_dp, rm, zm)` agree to `1e-10`, and the implied `rho_c` is `75.0` (today: `79.12431653` vs `75.0`).
- [ ] `test_stretch_coords` and (if added) `test_convex_wall` green; `test_biotsavart`, `test_biotsavart_field`, `test_example_field`, `test_mesh` unchanged.
- [ ] The `_efit_to_boozer` f2py extension still builds (guards against missing step 5b).
- [ ] `gfortran -Wall -Wextra` emits no new `-Wmaybe-uninitialized` for `field_divB0.f90`.
- [ ] The `downstream-gate` workflow is green. Per `ci/downstreams` the blocking set is SIMPLE, NEO-2, MEPHIT, KAMEL and rabe; NEO-RT is report-only.

## References

No specific literature reference is needed for the replacement: ray-versus-segment intersection in cross-product form is a standard implementation detail, and the `atan`-based stretching device itself is internal to libneo/NEO-2. The cross-product form is preferred over the slope/`tan` form simply because it has no orientation-dependent singularity — the two branches at lines 876-886 exist only to work around that singularity, and both of the numerical defects above live in that workaround.

For context on how a comparable code represents the wall: ASCOT5 ([Varje et al. 2019, arXiv:1908.02482](https://arxiv.org/abs/1908.02482)) defines `wall_type_2D`, "axisymmetric wall model consisting of single contour", and `wall_type_3D`, "3D wall model consisting of triangles" (`src/wall.h` in `ascot4fusion/ascot5`) — i.e. the wall stays an explicit geometric object rather than being resampled onto a fixed angular grid. This is background only; note that libneo's existing ASCOT5 cross-check, `test/scripts/test_ascot5_compare.py`, compares the Cerfon-Freidberg analytic equilibrium (`B_GS`) and has nothing to do with wall handling, so it will not catch regressions here.

## Scope and risk

Single PR, roughly 250 lines added and 130 deleted, confined to `src/magfie/` and `test/field/`, plus the two build-file edits in step 5. The real risk is numerical: `rho_c` changes by up to ~1 % near wall corners and by ~5 % in the midplane-wraparound sector, so any downstream golden record that samples the field just outside the wall will move. That is a *correction*, but it must be surfaced deliberately — run the downstream gate early and expect MEPHIT to need a reference refresh.
