### ISSUE TITLE
Support CHEASE EQDSK files

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#24]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still open and still real. The PR that this issue was split off from says so in its own merge message: `f460e50` *"Revised EQDSK class (#23)"* — *"CHEASE file format support is still an open issue."* Two and a half years later `python/libneo/eqdsk_base.py` is still present (261 lines), still exported from `python/libneo/__init__.py:13`, and still has four in-tree consumers. Below is the spec.

## Purpose

CHEASE (Lütjens/Bondeson/Sauter) is one of the two equilibrium solvers whose `EQDSK*.OUT` files routinely land on ITPcp desks — the DEMO 2019 equilibria used in the NTV/ripple work are CHEASE output at COCOS 2, not EFIT output at COCOS 3. Reading them today means either hand-editing the file or writing a one-off parser, which is exactly what `doc/ExtraDocuments/Fileformats.md:40-56` currently advises ("readers like `poor_eqdsk.py` from the ntv-demo repo may be used ... you might very well need to write one yourself"). The second half of the issue matters just as much: libneo currently ships **two** incompatible EQDSK readers with different capabilities, different attribute names and transposed boundary arrays, and downstream code silently picks the weaker one.

## Current state

**Two readers, diverging.**

- `python/libneo/eqdsk.py:1` — class `eqdsk_file`, binary-mode reader with tolerant fallbacks. It already contains partial CHEASE handling at `python/libneo/eqdsk.py:251-256`:

  ```python
  line = f.readline().split()
  if len(line) < 1:
    line = f.readline().split()  # CHEASE case
  if len(line) < 1:
    line = f.readline().split()  # PROCESS case
  self.npbound = int(line[0])
  self.nplimiter = int(line[1])
  ```

  plus `try`/`seek(-rewind, 1)` fallbacks for the fixed-column second and third header lines (`eqdsk.py:148-199`) and a `readblock()` that repairs embedded `\n`, `\n\n` and `  ` (`eqdsk.py:639-655`). It has **no writer**.

- `python/libneo/eqdsk_base.py:11` — function `read_eqdsk`, text-mode, strictly 16-column/5-per-row, with a `readblock` that only tolerates the one newline it expects (`eqdsk_base.py:4-9`) and no blank-line tolerance before the `npbound nplimiter` record (`eqdsk_base.py:85-87`). It **does** have `write_eqdsk` (`eqdsk_base.py:105`) and the plotting/`approximate_fluxsurface_area_eqdsk` helpers that `eqdsk.py` lacks.

**Nothing tests CHEASE.** `test/python/test_eqdsk.py:13-16` and `test/python/test_eqdsk_base.py:14-17` both exercise exactly one file, `test/resources/input_efit_file.dat`, which is a conforming EFIT g-file (60-char header, `a48,3i4`). The CHEASE case was listed as a TODO in the old golden-record test and left behind when that test was moved out of the repo in `ef335da` ("Relocated parts of test_eqdsk.py to CODES"):

```python
    # TODO: CHEASE
    # "/proj/plasma/DATA/DEMO/teams/Equilibrium_DEMO2019_CHEASE/MOD_Qprof_Test/EQDSK_DEMO2019_q1_COCOS_02.OUT"
```

That path is the concrete target file for the fixture.

**API mismatch blocking the removal.** Run against `test/resources/input_efit_file.dat`, the two readers disagree:

| | `read_eqdsk` dict | `eqdsk_file` attrs |
|---|---|---|
| header string | `header` | `filenamedateEQDSK` |
| box centre | `zboxmid` | `zbox_mid` |
| normalised label | `s_pol` | `psieqprof`, `psinorm` |
| `Lcfs` shape | `(209, 2)` | `(2, 209)` (transposed at `eqdsk.py:264-265`) |

## Reproduction / evidence

No CHEASE file is committed, so here is a reduced MRE that isolates the *structural* difference the `# CHEASE case` branch exists for — a record separator where `eqdsk_base` does not expect one:

```bash
cd /path/to/libneo && pip install -e .
python - <<'EOF'
import numpy as np
from libneo.eqdsk_base import read_eqdsk
from libneo.eqdsk import eqdsk_file

lines = open("test/resources/input_efit_file.dat").read().split("\n")
# line 1747 is the "  209  773" nbbbs/limitr record; insert a blank line before it
open("/tmp/blankline.eqdsk", "w").write("\n".join(lines[:1747] + [""] + lines[1747:]))

for fn in (read_eqdsk, eqdsk_file):
    try:
        fn("/tmp/blankline.eqdsk"); print("OK  ", fn.__name__)
    except Exception as e:
        print("FAIL", fn.__name__, type(e).__name__, e)
EOF
```

Observed at `fe3f76e`:

```
FAIL read_eqdsk IndexError list index out of range
OK   eqdsk_file
```

Expected after this issue: both paths gone, one reader, and it opens the real CHEASE file.

**Verification recipe for the CHEASE support itself** (a physics-checkable one, not just "no exception"): for `EQDSK_DEMO2019_q1_COCOS_02.OUT`, COCOS 2 has `sigma_Bp = +1`, `exp_Bp = 0` and a *counter-clockwise* (R, phi, Z) triad, whereas the EFIT files libneo assumes are COCOS 3. The observable is therefore `q > 0` on the whole profile and `psi_edge > psi_axis` after standardisation, together with `spol_at_rz(Rpsi0, Zpsi0) == 0` and `spol_at_rz` on the LCFS `== 1`, which `python/libneo/eqdsk.py:18-19` currently only fakes with an ad-hoc sign flip:

```python
    if np.sign(self._psi_at_axis) != np.sign(self.PsiaxisVs):
      self._psi_at_edge = -self.PsiedgeVs
```

## Behaviour (BDD)

```gherkin
Scenario: CHEASE COCOS-2 file is read without error
  Given the fixture test/resources/chease_cocos02.eqdsk derived from
        EQDSK_DEMO2019_q1_COCOS_02.OUT
  When  eq = libneo.eqdsk.eqdsk_file("test/resources/chease_cocos02.eqdsk")
  Then  eq.nrgr and eq.nzgr equal the 3i4 fields of the header line
  And   eq.PsiVs.shape == (eq.nzgr, eq.nrgr)
  And   eq.Lcfs.shape[1] == eq.npbound

Scenario: COCOS index is detected, not guessed
  Given the same fixture
  When  eq.cocos is queried
  Then  eq.cocos.index == 2
  And   for test/resources/input_efit_file.dat the same property returns 3

Scenario: normalised poloidal flux is convention independent
  Given eq built from test/resources/chease_cocos02.eqdsk
  When  eq.spol_at_rz(eq.Rpsi0, eq.Zpsi0) is evaluated
  Then  the result is 0.0 within 1e-6
  And   eq.spol_at_rz(eq.Lcfs[0, :], eq.Lcfs[1, :]) is 1.0 within 1e-3

Scenario: round trip through the writer preserves the equilibrium
  Given eq built from test/resources/chease_cocos02.eqdsk
  When  eq.write("/tmp/rt.eqdsk") and eq2 = eqdsk_file("/tmp/rt.eqdsk")
  Then  eq2.PsiVs matches eq.PsiVs to rtol 1e-8
  And   eq2.qprof matches eq.qprof to rtol 1e-8

Scenario: eqdsk_base is gone
  Given the repository at the merge commit
  When  `rg -n "eqdsk_base" python/ test/ docs/` is run
  Then  it reports no matches
```

## Implementation plan

Do this as **two PRs**; PR 1 is the feature, PR 2 is the deletion.

**PR 1 — CHEASE support in `eqdsk_file`**

1. Add fixture `test/resources/chease_cocos02.eqdsk`. Take `EQDSK_DEMO2019_q1_COCOS_02.OUT` from the path recorded in `ef335da` (`/proj/plasma/DATA/DEMO/teams/Equilibrium_DEMO2019_CHEASE/MOD_Qprof_Test/`). If the full 181×181 grid is too large to commit, down-sample to 65×65 with `scipy.interpolate.RegularGridInterpolator` and re-emit **in the original CHEASE line layout**, keeping the header string and the `(5e16.9)`-style fields byte-for-byte in the same columns; note the provenance in a new `test/resources/README.md`.
2. `python/libneo/eqdsk.py` — replace the fixed `f.read(48)` header read in `generate_from_file` (`eqdsk.py:140-146`) with a full-first-line read plus a two-branch parse: if the line is ≥60 characters, slice `[48:52]`, `[52:56]`, `[56:60]` (strict `a48,3i4`); otherwise fall back to `line.split()[-3:]`. Keep `self.filenamedateEQDSK` as the identification string.
3. `python/libneo/eqdsk.py` — replace the `if len(line) < 1: ... # CHEASE case / # PROCESS case` ladder at `eqdsk.py:251-256` with a `_next_nonempty_line(f)` helper that skips any number of blank lines, and use the same helper for the coil-count read at `eqdsk.py:275-280`.
4. `python/libneo/eqdsk.py` — add `self.cocos`, a small `CocosT` dataclass with fields `index`, `sgn_Bp`, `exp_Bp`, `sgn_cyl`, `sgn_dpsi`, `sgn_q`, populated by a new method `_detect_cocos()`. Mirror the sign logic already validated on the Fortran side in `src/magfie/geqdsk_tools.f90:268-276` (`sgn_dpsi` from `SIBRY-SIMAG`, `sgn_Btor` from `BCENTR`, `sgn_Itor` from `CURRENT`, `sgn_F` from `FPOL`, `sgn_q` from `QPSI`) so Python and Fortran cannot drift — this is the Python half of what itpplasma/libneo#33 asks for.
5. `python/libneo/eqdsk.py` — make `_build_psi_interpolator` (`eqdsk.py:8-19`) use `self.cocos` instead of the `np.sign` heuristic, so `spol_at_rz` is 0 at the axis and 1 at the LCFS by construction.
6. `test/python/test_eqdsk.py` — add `test_eqdsk_read_chease`, `test_cocos_index_chease_is_2`, `test_cocos_index_efit_is_3`, `test_spol_zero_at_axis_and_one_on_lcfs`, all against the new fixture. No CMake wiring needed: `.github/workflows/main.yml:100-101` already runs `pytest test/python` and `pytest python/tests`.
7. `doc/ExtraDocuments/Fileformats.md:40-56` — delete the "write your own reader / use `poor_eqdsk.py`" advice and point at `eqdsk_file`. `docs/eqdsk.rst:127-135` — replace the "automatically detects sign inconsistencies" paragraph with the real COCOS detection and document `eq.cocos`.

**PR 2 — remove `eqdsk_base.py`**

8. `python/libneo/eqdsk.py` — add `eqdsk_file.write(filename)`, porting `write_eqdsk` from `eqdsk_base.py:105-164` verbatim including the fixed `3i4` header columns introduced by `cf8fc44` (#396), and add a `classmethod from_dict(eqdata)` so `vmec_to_efit.py` and `vmec_utils.py` can keep building an equilibrium as a plain dict.
9. `python/libneo/eqdsk.py` — port `plot_poloidal_flux`, `plot_fpol`, `plot_fluxsurfaces` and `approximate_fluxsurface_area_eqdsk` (`eqdsk_base.py:167-261`) as methods, and add the missing `s_pol` attribute (`np.linspace(0, 1, nrgr)`).
10. Migrate consumers: `python/libneo/vmec_to_efit.py:6`, `python/libneo/vmec_utils.py:7,68`, `python/libneo/eqdsk_to_boozer_chartmap.py:182-184` and `:246-252`. **Watch the `Lcfs` orientation** — `eqdsk_to_boozer_chartmap.py:184` consumes `eq["Lcfs"]` in `(npbound, 2)` layout while `eqdsk_file` transposes to `(2, npbound)` at `eqdsk.py:264-265`. Pick one (recommend `(2, npbound)`, matching `Lcfs[0]`=R, `Lcfs[1]`=Z) and fix the caller.
11. Delete `python/libneo/eqdsk_base.py`; drop `from .eqdsk_base import *` from `python/libneo/__init__.py:13`.
12. Fold `test/python/test_eqdsk_base.py` and `python/tests/test_eqdsk_base.py` into `test/python/test_eqdsk.py`. The 3i4-column assertion in `python/tests/test_eqdsk_base.py:43-59` must survive — it guards the Fortran `format_2000 = '(a48, 3i4)'` reader in `src/magfie/geqdsk_tools.f90:32`. Update `python/tests/test_eqdsk_to_boozer_chartmap.py:99-102`.
13. No sibling repo changes are required for `eqdsk_base` itself (it is Python-only and not re-exported through the f90wrap layer), but `rg eqdsk_base` across SIMPLE/NEO-2/MEPHIT/NEO-RT before merging PR 2 — the downstream gate in `.github/workflows/downstream-gate.yml` does not cover Python-only imports.

## Acceptance criteria

- [ ] `test/resources/chease_cocos02.eqdsk` exists and its provenance is recorded.
- [ ] `python -m pytest test/python -q` and `python -m pytest python/tests -vv -s` both pass (the exact CI commands, `.github/workflows/main.yml:100-101`).
- [ ] `eqdsk_file("test/resources/chease_cocos02.eqdsk")` raises nothing and `eq.cocos.index == 2`.
- [ ] `eqdsk_file("test/resources/input_efit_file.dat").cocos.index == 3`, i.e. no regression on the existing fixture.
- [ ] `spol_at_rz` returns 0 at the axis (atol 1e-6) and 1 on the LCFS (atol 1e-3) for both fixtures.
- [ ] Write/read round trip on both fixtures reproduces `PsiVs`, `fprof`, `qprof` to rtol 1e-8.
- [ ] `rg -n "eqdsk_base"` over the repository returns nothing after PR 2.
- [ ] `cd build && ctest --output-on-failure` unchanged, in particular `test_geqdsk_tools` (currently tracked as failing in itpplasma/libneo#116 — do not make it worse).

## References

- Lütjens, Bondeson, Sauter, *The CHEASE code for toroidal MHD equilibria*, Comput. Phys. Commun. **97** (1996) 219 — the file format's origin and its normalisations.
- Sauter & Medvedev, *Tokamak coordinate conventions: COCOS*, Comput. Phys. Commun. **184** (2013) 293 — the canonical definition of the 16 conventions, the `sigma_Bp`/`exp_Bp` classification, and the transformation rules. This is what step 4 should implement; it is also the reference already implied by `cocos_t` in `src/magfie/geqdsk_tools.f90:16-19`.
- Prior art for a tolerant multi-flavour reader: **OMFIT**'s `omfit_classes.omfit_eqdsk.OMFITgeqdsk` (auto-detects COCOS and converts), UKAEA's **freeqdsk** (`freeqdsk.geqdsk.read`, strict `a48,3i4` + `5e16.9`), and **OMAS**, which carries the same COCOS machinery for IMAS round trips. **ASCOT5** ingests GEQDSK through `a5py` and likewise normalises to a fixed convention before use.

## Related issues

- itpplasma/libneo#25 — "Support FREEGS EQDSK files", the sibling filed 10 seconds later. Same reader, same fixture-and-fallback mechanics. Consider doing #24 and #25 in one PR with two fixtures; the COCOS work in step 4 serves both.
- itpplasma/libneo#33 — "Add checks between Fortran and Python EQDSK routines". Step 4 is the natural place to add a Python↔`geqdsk_tools.f90` COCOS cross-check.
- itpplasma/libneo#116 — `test_geqdsk_tools` COCOS index mismatch. Independent bug, same subsystem; fixing it first would give step 4 a trustworthy Fortran reference.

## Scope and risk

Two PRs, roughly 300 lines of Python plus a fixture. The risk is concentrated in step 10: `eqdsk_to_boozer_chartmap.py` feeds the Boozer chartmap pipeline, and the `Lcfs` transpose is an easy silent-wrong-answer if the caller is not updated in the same commit — `python/tests/test_eqdsk_to_boozer_chartmap.py` must be green before merge. Committing a large fixture is the other cost; down-sample if the original 181×181 file is unwelcome in git.
