### ISSUE TITLE
Support FREEGS EQDSK files

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#25]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

## Purpose

The issue body is empty, so the first job is to establish what "support FREEGS EQDSK files" means concretely today. `rg -i freegs` over the checkout at `fe3f76e` returns nothing, so nothing has been done. But the obvious guess about *why* FreeGS files would fail turns out to be wrong, and that changes the whole scope. The spec below is deliberately narrow as a result.

## Current state

### What FreeGS actually writes

FreeGS does not implement its own g-file writer. `freegs/geqdsk.py` builds a data dict and delegates to `freeqdsk.geqdsk.write` (the writer was split out into the separate FreeQDSK package, <https://github.com/freegs-plasma/FreeQDSK>). FreeQDSK's `freeqdsk/geqdsk.py` declares:

```python
_header_fmt   = "(a48,3i4)"
_data_fmt     = "(5e16.9)"
_bdry_lim_fmt = "(2i5)"
```

These are **byte-identical to libneo's own format strings** in `src/magfie/geqdsk_tools.f90:32-34`:

```fortran
  character(len = *), parameter :: format_2000 = '(a48, 3i4)'
  character(len = *), parameter :: format_2020 = '(5es16.9)'
  character(len = *), parameter :: format_2022 = '(2i5)'
```

FreeQDSK also pads its header comment to exactly 48 characters
(`f"{label:11}{creation_date:10s}   {shot_str:>8s}{time_str:16s}"` = 11+10+3+8+16 = 48) and writes the same record order libneo reads: header, four float records, `fpol`, `pres`, `ffprim`, `pprime`, `psirz`, `qpsi`, then `(2i5)` counts, then boundary, then limiter.

So the intuitive framing — "FreeGS is another divergent writer like CHEASE and PROCESS, so libneo needs a layout-agnostic parser" — **does not hold**. A FreeGS g-file is EFIT-column-compliant. Do not rewrite the Fortran readers to list-directed input on the strength of this issue; that is a large, risky change with no failing case behind it.

(Note also that the existing `# CHEASE case` / `# PROCESS case` workarounds at `python/libneo/eqdsk.py:252-256` are not column-width workarounds either. They are `readline()` calls that skip *blank lines* before the `nbbbs limitr` record. Different failure mode.)

### The one real incompatibility: `nlim == 0`

FreeQDSK's writer omits the limiter record entirely when there is no wall:

```python
if nlim > 0:
    lim = np.empty(2 * nlim)
    lim[0::2], lim[1::2] = data["rlim"], data["zlim"]
    write_array(lim, fh, data_fmt)
```

A FreeGS `Machine` has `wall=None` by default (`Machine.__init__(self, coils, wall=None, ...)`), and several shipped machines are built that way — `freegs.machine.MAST()` returns `Machine(coils)` with no wall. Such an equilibrium writes `nlim = 0` and **no limiter record at all**. The file simply ends after the boundary.

libneo has three readers and they behave differently on that file:

**1. `src/magfie/geqdsk_tools.f90` — aborts.** `geqdsk_read` (`:64-138`) reads the limiter unconditionally with no `end=` and no `iostat=`:

```fortran
    read (fid, format_2022) geqdsk%nbbbs, geqdsk%limitr   ! :90
    allocate(geqdsk%rbbbs(geqdsk%nbbbs))
    allocate(geqdsk%zbbbs(geqdsk%nbbbs))
    allocate(geqdsk%rlim(geqdsk%limitr))
    allocate(geqdsk%zlim(geqdsk%limitr))
    read (fid, format_2020) (geqdsk%rbbbs(kw), geqdsk%zbbbs(kw), kw = 1, geqdsk%nbbbs)   ! :95
    read (fid, format_2020) (geqdsk%rlim(kw), geqdsk%zlim(kw), kw = 1, geqdsk%limitr)    ! :96
```

With `limitr == 0` the statement at `:96` has an empty io-list, but a formatted `READ` with an empty io-list still advances one record. There is no record left, and with no `end=`/`iostat=` the program dies with a raw Fortran runtime end-of-file error. (`allocate` of size 0 is fine, and `geqdsk_deinit` at `:44-62` handles zero-size allocatables correctly, so allocation is not the problem — only the read is.)

**2. `src/magfie/field_divB0.f90` — `read_eqfile2` stops, `read_eqfile1` survives.** The two routines are asymmetric. `read_eqfile1` (`:377-443`) guards both arrays:

```fortran
  read(gunit,*,end=55,err=250)n_bndyxy,nlimEQD        ! :421
  if (n_bndyxy > 0) then                              ! :423
    allocate(LCFS(2*n_bndyxy))
    read(gunit,2010,end=55,err=250)(LCFS(i),i=1,2*n_bndyxy)
  end if
  if (nlimEQD > 0) then                               ! :428
    allocate(limEQD(2*nlimEQD))
    read(gunit,2010,end=55,err=250)(limEQD(i),i=1,2*nlimEQD)
  end if                                              ! :431
```

`read_eqfile2` (`:446-506`) does not:

```fortran
  read(gunit,*,end=55,err=250)n_bndyxy,nlimEQD        ! :490
  allocate(LCFS(2*n_bndyxy))
  allocate(limEQD(2*nlimEQD))
  read(gunit,2010,end=55,err=250)(LCFS(i),i=1,2*n_bndyxy)
  read(gunit,2010,end=55,err=250)(limEQD(i),i=1,2*nlimEQD)   ! :494
```

Line `:494` reaches `end=55` and the routine executes `print *, 'READ_EQFILE2: Early EOF in',trim(gfile); STOP` (`:503`). This is the branch `field_eq` takes when `use_fpol` is true (`field_divB0.f90:163-167`), i.e. the `efit_to_boozer` path. So the *unguarded* reader is the one on the more consequential code path.

**3. Python — both readers already cope.** `python/libneo/eqdsk.py:267-272` and `python/libneo/eqdsk_base.py:95-99` read the limiter with `for k in range(2*nplimiter)`, which is a no-op at zero, and the subsequent `reshape` of an empty array is valid. No change needed for this failure.

That is the whole verified defect. It is small, it is real, and it is worth fixing.

## Reproduction / evidence

FreeGS is not a libneo dependency and no fixture exists, so generate one. Use a machine **without** a wall — note that `freegs.machine.TestTokamak()` *does* pass a wall and therefore will **not** reproduce the bug.

`test/scripts/generate_freegs_eqdsk.py` (new):

```python
# pip install freegs
import freegs

tokamak = freegs.machine.MAST()          # Machine(coils) — no wall, so nlim == 0
eq = freegs.Equilibrium(tokamak=tokamak,
                        Rmin=0.1, Rmax=2.0, Zmin=-1.0, Zmax=1.0,
                        nx=65, ny=65,
                        boundary=freegs.boundary.freeBoundaryHagenow)
profiles = freegs.jtor.ConstrainPaxisIp(eq, 1e3, 2e5, 2.0)
freegs.solve(eq, profiles, freegs.control.constrain(
    xpoints=[(1.1, -0.6), (1.1, 0.8)],
    isoflux=[(1.1, -0.6, 1.1, 0.6)]))
with open("test/resources/input_freegs_file.geqdsk", "w") as fh:
    freegs.geqdsk.write(eq, fh)
```

(Adapt the constructor to the installed FreeGS release; the load-bearing calls are `freegs.machine.MAST()` and `freegs.geqdsk.write`.) Confirm the fixture is the right shape before using it:

```bash
tail -c 200 test/resources/input_freegs_file.geqdsk    # must end after the boundary block
grep -n '^ *[0-9]\+ *0 *$' test/resources/input_freegs_file.geqdsk   # the "nbbbs 0" record
```

Then observe each reader:

```bash
make
./build/standardise_geqdsk.x test/resources/input_freegs_file.geqdsk /tmp/freegs_std.geqdsk
# expected at fe3f76e: Fortran runtime error, end of file

python -c "from libneo import eqdsk; e=eqdsk.eqdsk_file('test/resources/input_freegs_file.geqdsk'); print(e.nrgr, e.nzgr, e.nplimiter)"
# expected at fe3f76e: 65 65 0  (already works)
```

Use FreeQDSK's own reader as the oracle for the numeric content — it parses the same file independently, so it pins down whether libneo's values are right without anyone having to reason about byte offsets:

```python
from freeqdsk import geqdsk
with open("test/resources/input_freegs_file.geqdsk") as fh:
    ref = geqdsk.read(fh)
print(ref["nx"], ref["ny"], ref["fpol"][-1], ref["bcentr"], ref["rcentr"], ref["qpsi"][:3])
```

## Behaviour (BDD)

```gherkin
Scenario: geqdsk_read accepts a g-file with no limiter record
  Given a g-file whose counts record is "  129    0" and which ends after the boundary block
  When geqdsk_read is called on it
  Then it returns normally
  And geqdsk%limitr == 0
  And size(geqdsk%rlim) == 0 and size(geqdsk%zlim) == 0
  And no Fortran runtime end-of-file error is raised

Scenario: read_eqfile2 accepts the same g-file
  Given the same g-file
  When read_eqfile2 is called on it
  Then it returns normally
  And it does not print "READ_EQFILE2: Early EOF"

Scenario: geqdsk_read agrees with FreeQDSK on the FreeGS fixture
  Given test/resources/input_freegs_file.geqdsk generated with nx=65, ny=65
  When geqdsk_read parses it and freeqdsk.geqdsk.read parses it
  Then geqdsk%nw == 65 and geqdsk%nh == 65
  And geqdsk%fpol, geqdsk%pres, geqdsk%ffprim, geqdsk%pprime, geqdsk%qpsi each agree
      with the FreeQDSK arrays to 1e-9 relative, after the SI-to-CGS factors
      geqdsk_read applies
  And geqdsk%psirz agrees with FreeQDSK's psi to 1e-9 relative after the 1e8 factor

Scenario: a FreeGS file with a wall still round-trips
  Given a fixture generated from freegs.machine.TestTokamak() (which has a wall)
  When standardise_geqdsk.x is run on it
  Then it exits 0
  And geqdsk%limitr > 0

Scenario: the existing EFIT fixture is unaffected
  Given test/resources/input_efit_file.dat
  When ctest -R test_geqdsk_tools runs
  Then it passes with the same values as at fe3f76e
```

## Implementation plan

1. `src/magfie/geqdsk_tools.f90`, in `geqdsk_read` — guard the two reads at `:95` and `:96` with `if (geqdsk%nbbbs > 0)` and `if (geqdsk%limitr > 0)` respectively. Keep the unconditional `allocate` calls at `:91-94`: zero-size allocation is valid and keeps `geqdsk_deinit` and every downstream `size()` call well defined. This is the only change strictly required to close the issue.
2. `src/magfie/field_divB0.f90`, in `read_eqfile2` — copy the guards from `read_eqfile1:423-431` onto `:491-494`, so the two routines stop disagreeing about the same file. Do not otherwise touch these routines here; `read_eqfile1`'s guarded form is the template.
3. `test/scripts/generate_freegs_eqdsk.py` (new) and `test/resources/input_freegs_file.geqdsk` (new) — the generator above plus its committed output, alongside the existing `input_efit_file.dat`. Commit the fixture so CI needs no FreeGS dependency; if you want CI to regenerate it, add `freegs` to the `dev` extra at `pyproject.toml:26`, otherwise leave the dependency out.
4. `test/source/test_geqdsk_tools.f90` — add `subroutine test_read_freegs(sucess)` following the existing pattern. The fixture path convention is `'../../test/resources/...'` (see `:122` and `:173`); the working directory is set at `test/CMakeLists.txt:293-295`. Assert `nw == 65`, `nh == 65`, `limitr == 0`, `size(geqdsk%rlim) == 0`, and that `geqdsk_read` returns at all. Register it in the `sucess_all` chain at `:14-24`. No new `add_test` entry is needed — `test_geqdsk_tools` is already registered at `test/CMakeLists.txt:265`.
5. `test/python/test_eqdsk.py` — add `"test/resources/input_freegs_file.geqdsk"` to `test_files` (`:13-16`). This should pass without any Python change; if it does not, that is a separate finding worth its own issue.
6. `docs/eqdsk.rst` — add a short "Supported writers" section listing EFIT, CHEASE, PROCESS and FreeGS, and stating the policy: libneo writes strict EFIT columns and tolerates an absent limiter record on read.

Deliberately **not** in scope, despite being tempting:

- Converting the fixed-format reads to list-directed input. No FreeGS file needs it, and it would turn loud failures on genuinely malformed files into silent garbage.
- Deleting `python/libneo/eqdsk_base.py`. That is prescribed by the body of itpplasma/libneo#24 ("Remove `eqdsk_base.py` then."), and belongs to that issue, not this one.

### Adjacent findings (not required to close this issue)

Two things surfaced while checking the above. Both are real; neither is a FreeGS problem. File separately rather than folding them in.

- `python/libneo/eqdsk_base.py:160` writes the counts record free-form: `f.write(f"{eqdata['npbound']} {eqdata['nplimiter']}\n")`. `geqdsk_tools.f90:90` reads that record with `(2i5)`. With the default `BLANK='NULL'`, a line `129 129` is read as `nbbbs = 1291, limitr = 29`. This is the exact bug class that `cf8fc44` ("Write EQDSK header dimensions in fixed 3i4 columns (#396)") fixed for the *header* integers, and it is unguarded because no test crosses the Python writer with the Fortran reader — which is precisely what itpplasma/libneo#33 asks for.
- `geqdsk_classify` (`:264-305`) computes `sgn_q = sign_array(geqdsk%qpsi, 'QPSI', .true.)` at `:276`. When `qpsi` gives no majority sign, `sign_array` returns 0 (`:258-260`), `cocos%index` stays 0, and `geqdsk_standardise` (`:307-341`) skips the q flip at `:322` yet still asserts `geqdsk%cocos%index = 3` unconditionally at `:340`. That is the "secondary note" already recorded on itpplasma/libneo#302; leave it there.

## Acceptance criteria

- [ ] `test/resources/input_freegs_file.geqdsk` exists, its counts record ends in `0`, and the file has no limiter block after the boundary block.
- [ ] `test/scripts/generate_freegs_eqdsk.py` exists and regenerates that fixture with a pinned FreeGS version.
- [ ] `./build/standardise_geqdsk.x test/resources/input_freegs_file.geqdsk /tmp/out.geqdsk` exits 0 (it aborts with an end-of-file error at `fe3f76e`).
- [ ] A unit test drives `read_eqfile2` on the same fixture and it returns without printing `READ_EQFILE2: Early EOF`.
- [ ] `cd build && ctest -R test_geqdsk_tools --output-on-failure` passes, including the new `test_read_freegs` subtest.
- [ ] `python -m pytest test/python python/tests -q` passes with the FreeGS file added to `test_files`.
- [ ] `geqdsk_read`'s `fpol`, `pres`, `ffprim`, `pprime`, `qpsi` and `psirz` for the fixture agree with `freeqdsk.geqdsk.read` on the same file to 1e-9 relative, after libneo's SI-to-CGS factors.
- [ ] The values asserted by `test_geqdsk_tools` for `test/resources/input_efit_file.dat` are unchanged from `fe3f76e`.
- [ ] `.github/workflows/downstream-gate.yml` is green. Its gated set is `ci/downstreams`: SIMPLE, NEO-2, MEPHIT, KAMEL and rabe are blocking; NEO-RT is report-only. `field_divB0` is on the `efit_to_boozer` path, so the step-2 change is not cosmetic for these.

### Compatibility risk notes

One small PR. The two Fortran guards are three lines each and strictly widen the set of accepted files; no currently-readable file changes behaviour, because a file that *has* a limiter record still takes the same path. The fixture and tests are the bulk of the diff.

The one thing to watch: guarding `:95`/`:96` means a *truncated* EFIT file — one that promises `limitr = 27` but ends early — still fails, which is correct, but it now fails at `:96` rather than being distinguishable from the legitimate `limitr = 0` case. That is the intended distinction and the new test pins it.

## References

- L. L. Lao, H. St. John, R. D. Stambaugh, A. G. Kellman, W. Pfeiffer, *Reconstruction of current profile parameters and plasma shapes in tokamaks*, Nuclear Fusion **25** (1985) 1611 — the EFIT paper behind the G-EQDSK record layout these format strings encode.
- O. Sauter, S. Yu. Medvedev, *Tokamak coordinate conventions: COCOS*, Computer Physics Communications **184** (2013) 293-302, doi:10.1016/j.cpc.2012.09.010 — the convention taxonomy implemented in `geqdsk_classify` / `geqdsk_standardise`.
- FreeGS, <https://github.com/freegs-plasma/freegs> — `freegs/geqdsk.py` delegates writing to FreeQDSK.
- FreeQDSK, <https://github.com/freegs-plasma/FreeQDSK> — `freeqdsk/geqdsk.py` holds the actual `_header_fmt` / `_data_fmt` / `_bdry_lim_fmt` strings and the `if nlim > 0` guard quoted above. This is the file to re-read if FreeGS's output ever changes.
- H. Lütjens, A. Bondeson, O. Sauter, *The CHEASE code for toroidal MHD equilibria*, Computer Physics Communications **97** (1996) 219 — the writer behind the `# CHEASE case` workaround at `python/libneo/eqdsk.py:254`.

No literature reference covers the limiter-record guard itself; that is an implementation detail internal to the code.

### Related issues

- itpplasma/libneo#24 (CHEASE, same author, same day) — near-twin, not a duplicate: different writer, and its body prescribes removing `eqdsk_base.py`, which this issue deliberately leaves alone.
- itpplasma/libneo#33 (Fortran/Python EQDSK cross-checks) — owns the free-form counts-record bug noted above.
- itpplasma/libneo#302 (unvalidated `field_divB0` reader path) — overlaps step 2's file and owns the `sgn_q == 0` note. Its own follow-up comment corrects the caller list: MEPHIT sets `skip_read = .true.` and injects already-standardised arrays, so the exposed callers of `read_eqfile1/2` are `efit_to_boozer` and `bdivfree`.
- itpplasma/libneo#363 (automatic COCOS-3 check; migrated from the archived itpplasma/efit_to_boozer#14).
- itpplasma/libneo#28 (q-profile check for EQDSK).
- itpplasma/libneo#116 (`test_geqdsk_tools` COCOS index 15 vs 3). Reported as marked XFAIL, but no `WILL_FAIL` or `XFAIL` property exists in `CMakeLists.txt` or `test/CMakeLists.txt` at `fe3f76e`, so confirm whether `test_geqdsk_tools` is currently green before adding a subtest to it.

## Scope and risk

This is one small compatibility PR: guard zero-length boundary/limiter reads, add one generated-and-committed FreeGS fixture, exercise both Fortran readers and the existing Python reader, and document the supported writer. Do not broaden it into a list-directed parser rewrite or the separate Python-writer cleanup tracked by related issues.

The functional risk is low because files with a positive limiter count keep their existing path. The regression risk is distinguishing a legitimate `limitr = 0` end-of-file from a genuinely truncated file that advertises limiter data; the positive-wall and zero-wall fixtures must cover both sides of that boundary.
