### ISSUE TITLE
Add check for q profile for EQDSK

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#28]
Comparison of Fortran EFIT routines versus directly reading safety factor from EQDSK is in https://github.com/itpplasma/ntv-demo/blob/main/python/script_marsq_to_boozer.py

https://gitlab.tugraz.at/plasma/codes/efit_to_boozer

@marjohma @GeorgGrassler @pazathoth

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still open and still unimplemented. There is no place in the tree where the q profile recomputed by field-line integration is compared with the `QPSI` column of the g-file. Below is a spec that closes that gap.

## Purpose

`efit_to_boozer` does not trust the g-file's `QPSI` — it rebuilds the safety factor from scratch by integrating field lines until they return to the outboard midplane (`src/efit_to_boozer/field_line_integration_for_Boozer.f90:207-216`). That is the right thing to do numerically, but it also means the *one* quantity that would immediately expose a bad g-file read is never used. A factor-2π error in ψ (COCOS 11-18 "full flux" vs COCOS 3 "flux per radian"), a sign-reversed `SIBRY`/`SIMAG`, or a wrong axis location all produce a field that still looks smooth and divergence-free but whose q is wrong by an obvious, diagnosable factor. Since `q` sets the resonance condition `m - nq = 0`, an undetected error propagates straight into resonant-transport results and into mode positions. A cheap `q_integrated` vs `q_gfile` comparison at the end of the conversion turns a silent physics error into a loud one. This is the concrete diagnostic that #302 asks for on the `field_divB0` read path.

## Current state

**Computed q.** `flint_for_Boozer` follows a field line from `(rbeg(isurf), zaxis)` until it comes back to `Z = zaxis`, then inverts the accumulated toroidal angle (`src/efit_to_boozer/field_line_integration_for_Boozer.f90:207-216`):

```fortran
    aiota=2.d0*pi/phi_sep
    rrr=ymet(1)
    zzz=ymet(2)
...
    rsmall(isurf)=sqrt(abs(ymet(3))/pi)
    qsaf(isurf)=1.d0/aiota
    psi_pol(isurf)=psif-psi_axis
```

**g-file q, path A (dropped).** `read_eqfile1` declares `qpsi` as a local, reads it, and never returns it (`src/magfie/field_divB0.f90:393` and `:418`); `read_eqfile2` does the same at `:462`/`:487`. This is the reader that `field_eq` — and therefore `efit_to_boozer` — actually uses.

**g-file q, path B (kept, but only for signs).** `geqdsk_tools` stores `qpsi` in the derived type (`src/magfie/geqdsk_tools.f90:27`, allocated `:78`, read `:89`) and uses it only for COCOS classification (`:276`, `geqdsk%cocos%sgn_q = sign_array(geqdsk%qpsi, 'QPSI', .true.)`) and the sign repair at `:323-324`. `geoflux_coordinates` is the only consumer that uses the values: it trapezoidally integrates `qpsi dψ/2π` to get toroidal flux (`src/coordinates/geoflux_coordinates.f90:278` guard, routine `integrate_toroidal_flux` at `:399-413`).

**Output.** `flux_functions.dat` (`app/efit_to_boozer.f90:239-243`) writes `rbeg, rsmall, qsaf, psi_pol, psi_tor_vac, psi_tor*psitor_max`.

**Two traps that make column 4 *not* a `SIBRY`-normalised label.** The file is written *after* `spline_magdata_in_symfluxcoord`, which normalises in place (`src/efit_to_boozer/spline_and_interpolate_magdata.f90:64-67`):

```fortran
  psipol_max=psi_pol(nlabel)
  psitor_max=psi_tor(nlabel)
  psi_pol=psi_pol/psipol_max
  psi_tor=psi_tor/psitor_max
```

so column 4, labelled `psi_pol`, is really `s_pol` normalised to the *outermost successfully integrated surface*. That surface is not the separatrix, for two independent reasons:

1. `flint_for_Boozer` deliberately discards the last surface (`field_line_integration_for_Boozer.f90:162`, `nsurf=nsurf-1  !last point is bad, remove it`).
2. Integration also stops early when `psif > psimax` (`field_line_integration_for_Boozer.f90:147-150`), where `psimax` is read positionally from line 7 of `efit_to_boozer.inp` (`app/efit_to_boozer.f90:33`) and defaults to `1.d300` (`src/efit_to_boozer/efit_to_boozer_mod.f90:15`). The committed `test/python/efit_to_boozer.inp` sets `psimax = 2119063900.d0` in CGS. This stop was added by the current HEAD commit `fe3f76e`. Whether it binds for a given deck must be checked, not assumed.

**Any comparison must therefore be done in absolute ψ, not in normalised labels**, using `psipol_max` from `efit_to_boozer_mod` (`src/efit_to_boozer/efit_to_boozer_mod.f90:9`).

**Python side.** `python/libneo/eqdsk_base.py:78-83` reads the g-file `qprof` and builds a matching equidistant `s_pol`; `python/libneo/flux_converter.py:16-29` consumes a `q_profile`; `test/python/test_flux_converter.py` tests only self-consistency of the flux conversion against a hard-coded control array. Nothing compares the two q's. `git log --all -S'qpsi' -- test python` returns a single hit (`2162a36`, "Add geoflux coordinate support in libneo (#131)"), confirming no such test was ever added.

**Blocker for the Python route.** `psipol_max` is *not* exported by the f2py interface: the `use efit_to_boozer_mod, only: ...` list at `src/efit_to_boozer/f2py_interfaces/f2py_efit_to_boozer.f90:3-5` includes `psimax` but omits `psipol_max` and `psitor_max`. Any Python-side comparison in absolute ψ needs that symbol added first — see step 6.

## Reproduction / evidence

The fixture is `test/resources/input_efit_file.dat` — ASDEX Upgrade #31114, `nw=65`, `nh=129`, `SIMAG=-0.108122148`, `SIBRY=0.13648048`, `BCENTR=-2.50046372`. Its `QPSI` block (verified by parsing the file) runs

```
q[0]  = 1.03995204   q[1]  = 1.05116630   ...   q[62] = 4.21801090
q[63] = 5.55391938e+05   q[64] = 1.48103700e+06
```

i.e. monotonically rising from 1.04 on axis to ≈4.2, then diverging at the last two grid points because the equilibrium is diverted and q → ∞ at the X-point. **The comparison window must exclude those points.**

Verification recipe:

```bash
cd /path/to/libneo
make                       # wraps cmake --preset default && cmake --build --preset default
cd test/python             # holds efit_to_boozer.inp and field_divB0.inp,
                           # the latter pointing at ../resources/input_efit_file.dat
../../build/efit_to_boozer.x | tee run.log
```

`flux_functions.dat` appears in the working directory. `psipol_max` in CGS is the number printed by `flint_for_Boozer` at `field_line_integration_for_Boozer.f90:231` as `Normalized poloidal flux psi at the LCMS = <value> (psi on axis = 0)`. Scrape it from `run.log`; that is the only route until step 6 exports the symbol.

```python
import re
import numpy as np
from scipy.interpolate import CubicSpline
from libneo.eqdsk_base import read_eqdsk

# absolute psi scale (CGS, G cm^2) from the run log
m = re.search(r"Normalized poloidal flux psi at the LCMS =\s*(\S+)", open("run.log").read())
psipol_max_cgs = float(m.group(1).replace("D", "E"))

d = np.loadtxt("flux_functions.dat", skiprows=1)
s_pol_int, q_int = d[:, 3], d[:, 2]        # col 4 is psi_pol/psipol_max, col 3 is q

eq = read_eqdsk("../resources/input_efit_file.dat")
q_g, s_g = eq["qprof"], eq["s_pol"]        # s_pol is equidistant [0,1] over nw points

# drop the diverging X-point tail without hard-coding an index
keep = np.ones_like(q_g, dtype=bool)
for i in range(len(q_g) - 1, 0, -1):
    if abs(q_g[i]) > 10.0 * abs(q_g[i - 1]):
        keep[i] = False
    else:
        break
q_gfile = CubicSpline(s_g[keep], q_g[keep])

SIMAG, SIBRY = eq["PsiaxisVs"], eq["PsiedgeVs"]   # eqdsk_base.py:37-38
psi_abs_Wb = s_pol_int * psipol_max_cgs * 1e-8            # psi - psi_axis, Wb/rad
s_gfile = psi_abs_Wb / (SIBRY - SIMAG)

w = (s_gfile > 0.05) & (s_gfile < 0.85)
rel = np.abs(q_int[w]) / np.abs(q_gfile(s_gfile[w])) - 1.0
print("max |q_int/q_gfile - 1| =", np.abs(rel).max())
```

Observed today: nothing at all — no such diagnostic is emitted or checked. **The actual agreement level on this fixture has not been measured**; the first task of the implementing PR is to run the above, record the number, and set the tolerance from it (see acceptance criteria). Do not assume a value in advance.

The diagnostic value is in the failure modes: a full-flux (COCOS 11-family) g-file read through `read_eqfile1` should yield `q_int/q_gfile ≈ 2π` uniformly, and a sign-flipped file `≈ -1`.

## Behaviour (BDD)

```gherkin
Scenario: consistent COCOS-3 g-file passes the q check
  Given field_divB0.inp with gfile = '../resources/input_efit_file.dat'
  And efit_to_boozer.inp as committed in test/python/efit_to_boozer.inp
  When build/efit_to_boozer.x is run in test/python
  Then stdout contains a line "q check: max |q_int/q_gfile - 1| = <x>"
  And <x> is below the tolerance recorded in the PR from the baseline measurement
  And the exit status is 0

Scenario: X-point divergence of QPSI does not trigger a false alarm
  Given the same diverted g-file whose QPSI(64) = 1.481037e+06
  When the q check evaluates the comparison window
  Then grid points with s_pol > 0.85 are excluded from the deviation metric
  And the reported maximum deviation is unaffected by QPSI(63) and QPSI(64)

Scenario: full-flux g-file is diagnosed as a 2 pi convention error
  Given a copy of test/resources/input_efit_file.dat with SIMAG, SIBRY and
        the PSIRZ block all multiplied by 2*pi (a COCOS-11-family file)
  When build/efit_to_boozer.x is run on it
  Then the median of q_int/q_gfile is within 1% of 2*pi
  And the code prints "q check: ratio consistent with a 2*pi (full-flux) psi convention"
  And test_efit_q_profile reports this case as detected

Scenario: sign-reversed poloidal flux is diagnosed
  Given a copy of the g-file with SIMAG, SIBRY and PSIRZ negated
  When the q check runs
  Then the median of q_int/q_gfile is negative
  And the code prints a sign-convention warning naming COCOS

Scenario: unusable QPSI degrades gracefully
  Given a g-file whose QPSI block is all zeros
  When build/efit_to_boozer.x is run on it
  Then it prints "QPSI not usable, q check skipped"
  And the exit status is 0
```

## Implementation plan

1. **Create `src/efit_to_boozer/q_profile_check.f90`** — module `efit_to_boozer_q_check`, `implicit none`, `private`, `public :: compare_q_with_geqdsk, q_check_result_t`. Derived type `q_check_result_t` with components `max_rel_dev`, `median_ratio`, `n_points`, `window_s_min`, `window_s_max`, `logical :: consistent`, `logical :: looks_full_flux`, `logical :: sign_mismatch`, `logical :: skipped`. Subroutine signature:
   ```fortran
   subroutine compare_q_with_geqdsk(gfile, psipol_max_cgs, s_pol, q_int, res, &
                                    s_min, s_max, rel_tol)
   ```
   `s_pol`/`q_int` are the normalised label and integrated q from `flint_for_Boozer`; `s_min`, `s_max`, `rel_tol` optional with defaults `0.05_dp`, `0.85_dp`, and the tolerance measured in the baseline run.
   Body: `use geqdsk_tools, only: geqdsk_t, ...` to obtain `geqdsk%qpsi`, `geqdsk%simag`, `geqdsk%sibry` — these scalar component names are confirmed present at `src/magfie/geqdsk_tools.f90:26-27`. Look up the actual public read/classify/deinit procedure names in that module before writing the `only:` list. Build the g-file q on an equidistant `s_pol_gfile = [0,1]` grid of length `geqdsk%nw` via `use interpolate, only: construct_splines_1d, evaluate_splines_1d` (declared public at `src/interpolate/interpolate.f90:70` and `:72`; signatures at `:113` and `:143`), order 3, non-periodic. Map the integrated grid with `s_gfile = s_pol * psipol_max_cgs * 1.0d-8 / (sibry - simag)`. Drop any trailing points where `|qpsi(i)| > 10 * |qpsi(i-1)|` — no hard-coded index. Compute `ratio = q_int / q_gfile` over the window; set `looks_full_flux` when `abs(median_ratio)` is within 1% of `2*pi` or of `1/(2*pi)`, `sign_mismatch` when `median_ratio < 0`, and `skipped` when `qpsi` is all zeros or fewer than 4 usable points survive.
2. **Register the source in `src/efit_to_boozer/CMakeLists.txt`**, not the top-level file. The `efit_to_boozer` static library is declared there at `src/efit_to_boozer/CMakeLists.txt:64-69`; add `q_profile_check.f90` to that source list next to `field_line_integration_for_Boozer.f90` (line 66). **No new link libraries are needed**: `target_link_libraries(efit_to_boozer ... neo magfie)` already covers `geqdsk_tools` (in `magfie`) and `interpolate` (linked `PUBLIC` by `neo` at top-level `CMakeLists.txt:381`).
3. **Call it from `app/efit_to_boozer.f90`** immediately after `call spline_magdata_in_symfluxcoord` (currently line 53), while `psipol_max` is in scope. Use `gfile` from `use input_files, only : gfile` (already imported at `app/efit_to_boozer.f90:5`). Print a one-line summary unconditionally; print an explicit warning block when `.not. res%consistent`. **Do not `error stop`** in the app and **do not add a line to `efit_to_boozer.inp`** — that file is read positionally (`app/efit_to_boozer.f90:25-34`), so a new entry breaks every existing input deck, including the four committed copies under `test/python/`, `python/tests/`, `python/scripts/`, and `doc/efit_to_boozer/RUN/`. Keep the app diagnostic-only.
4. **Add `test/source/test_efit_q_profile.f90`** — a `program test_efit_q_profile` that calls `flint_for_Boozer` (or simply reads a `flux_functions.dat` produced by a preceding fixture run) and then `compare_q_with_geqdsk`, `error stop`ping when `res%max_rel_dev` exceeds the tolerance. Follow the existing style of `test/source/test_geqdsk_tools.f90`.
5. **Add the test fixture directory `test/efit_to_boozer/`** containing copies of `efit_to_boozer.inp` and `field_divB0.inp` with `gfile = '../resources/input_efit_file.dat'` (same relative-path convention already used by `test/python/field_divB0.inp`). Register in `test/CMakeLists.txt` next to `add_test(NAME test_geqdsk_tools ...)` (line 265) with
   ```cmake
   add_executable(test_efit_q_profile.x source/test_efit_q_profile.f90)
   target_link_libraries(test_efit_q_profile.x ${MAIN_LIB} ${MAGFIE_LIB} efit_to_boozer)
   add_test(NAME test_efit_q_profile COMMAND test_efit_q_profile.x)
   set_tests_properties(test_efit_q_profile PROPERTIES
     WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/test/efit_to_boozer)
   ```
   `MAIN_LIB` (`neo`) and `MAGFIE_LIB` (`magfie`) are set at `test/CMakeLists.txt:3` and `:5`; the `WORKING_DIRECTORY` pattern mirrors `test/CMakeLists.txt:293-295`.
6. **Export `psipol_max` through the f2py interface** — add `psipol_max` (and `psitor_max`, which is equally missing) to the `use efit_to_boozer_mod, only: ...` list at `src/efit_to_boozer/f2py_interfaces/f2py_efit_to_boozer.f90:3-5`. Without this the Python route cannot recover the absolute-ψ scale at all. Then add **`test/python/test_eqdsk_q_profile.py`**: `pytest.importorskip` on `_efit_to_boozer` (copy the skip guard from `python/tests/test_eqdsk_to_boozer_chartmap.py:25-31`), call the module's `init()`, then loop `magdata(2, s, psi, theta, ...)` — with `inp_label = 2` the routine takes absolute `psi` as input and sets `s = psi/psipol_max` internally (`src/efit_to_boozer/spline_and_interpolate_magdata.f90:137-138`), so q comes back directly on the poloidal-flux grid. Note `magdata` has 20 arguments (`f2py_efit_to_boozer.f90:106-108`) with `s, psi, theta` all `intent(inout)`. Compare against `libneo.eqdsk_base.read_eqdsk(...)['qprof']` splined on `['s_pol']`.
7. **Add the two perturbed-g-file cases** as generated fixtures inside the Python test (write a scaled copy of `input_efit_file.dat` to `tmp_path` with ψ multiplied by 2π, and one with ψ negated) and assert that `looks_full_flux` / `sign_mismatch` fire. Do not commit extra g-files; generate them from the existing fixture with `libneo.eqdsk_base.write_eqdsk` (`python/libneo/eqdsk_base.py:105`).
8. **Cross-repo:** none required. Step 3 only adds printed output, so downstream consumers are unaffected; keep it that way so the downstream gate stays green.

## Acceptance criteria

- [ ] `cmake --build --preset default` succeeds with `src/efit_to_boozer/q_profile_check.f90` in the `efit_to_boozer` library.
- [ ] `cd build && ctest -R test_efit_q_profile --output-on-failure` passes.
- [ ] The baseline `max |q_int/q_gfile - 1|` on `test/resources/input_efit_file.dat` over `0.05 <= s_pol <= 0.85` is **measured, printed, and quoted in the PR description**, and the enforced tolerance is set from it with a stated margin.
- [ ] The X-point points `QPSI(63)=5.554e5` and `QPSI(64)=1.481e6` are excluded automatically, with no hard-coded index 63.
- [ ] The synthetic 2π-scaled g-file is reported with `looks_full_flux = .true.` and `median_ratio` within 1% of 2π.
- [ ] The synthetic sign-flipped g-file is reported with `sign_mismatch = .true.`.
- [ ] A g-file whose `QPSI` block is all zeros yields `skipped = .true.`, a printed "QPSI not usable, q check skipped", and exit status 0 — no crash.
- [ ] `psipol_max` is importable from `_efit_to_boozer` after step 6.
- [ ] `python -m pytest test/python/test_eqdsk_q_profile.py -q` passes, or skips cleanly when `_efit_to_boozer` is not built.
- [ ] No regression: `ctest` green overall, in particular `test_geqdsk_tools`, `test_boozer_converter_vs_simple`, and `test_geoflux`.

## References

- L. L. Lao, H. St. John, R. D. Stambaugh, A. G. Kellman, W. Pfeiffer, *Reconstruction of current profile parameters and plasma shapes in tokamaks*, Nuclear Fusion **25** (1985) 1611 — defines the EFIT g-file and the `QPSI` column being compared against.
- O. Sauter, S. Yu. Medvedev, *Tokamak coordinate conventions: COCOS*, Computer Physics Communications **184** (2013) 293-302, doi:10.1016/j.cpc.2012.09.010 — the 2π and sign conventions the check is designed to catch; already the basis of the COCOS classification and standardisation code in `src/magfie/geqdsk_tools.f90`.
- A. H. Boozer, *Plasma equilibrium with rational magnetic surfaces*, Physics of Fluids **24** (1981) 1999 — the Boozer coordinate construction `efit_to_boozer` targets, in which `iota = 1/q` is the primary surface label datum.

Beyond the three references above, this is an implementation detail internal to the code; no specific literature prescribes the check. Note that `test/scripts/test_ascot5_compare.py` is **not** a precedent for it — that script cross-checks libneo's analytic Cerfon-Freidberg solver against ASCOT5's `B_GS` implementation, never reads a g-file, and never touches q.

## Scope and risk

Single PR, roughly 250 lines of new Fortran plus two test files; the app change is a few lines of printed diagnostics. Main risks: (a) getting the ψ normalisation wrong — the `psi_pol` column is normalised to the outermost *integrated* surface, which differs from `SIBRY` both because the last surface is discarded and because of the `psimax` early stop, so comparing normalised labels directly will produce a spurious deviation near the edge; (b) picking a tolerance before measuring the baseline — measure first, then enforce, and keep the app diagnostic-only so only the fixture test gates CI.

Related open issues, worth cross-linking rather than merging: itpplasma/libneo#302 (the `read_eqfile1`/`read_eqfile2` path drops `qpsi` and performs no convention checks — this check is the natural regression test for that fix, and step 1 here deliberately reads the g-file a second time through `geqdsk_tools` so the two issues stay independent), itpplasma/libneo#363 (automatic COCOS-3 detection on EQDSK input), itpplasma/libneo#33 (Fortran vs Python EQDSK reader cross-checks — step 6 above is a partial contribution), and itpplasma/libneo#361 (EQDSK→Boozer vs GPEC, a superset validation at a different level).
