### ISSUE TITLE
Test evan order in spline three to five

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#30]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

The issue body is empty, so the intent is reconstructed from the title and then checked against the code. It is still open for a good reason: **the one even-order routine that has no test is also demonstrably broken.** The numbers below come from compiling `src/spl_three_to_five.f90` out of tree and measuring convergence, not from reading the code.

## Purpose

`spl_three_to_five` is the spline kernel underneath essentially every interpolated field in the stack: `src/interpolate/interpolate.f90`, the batch/OpenACC layer `src/interpolate/batch_interpolate_{1,2,3}d.f90`, the Boozer converter (`src/boozer_converter.F90:848,867`), and the symmetry-flux splines in `src/efit_to_boozer/spline_and_interpolate_magdata.f90:25`. Order 4 is an advertised, reachable option throughout that layer, so a user selecting it is entitled to quartic accuracy. Even-degree spline interpolation *at the knots* is the classically delicate case — the interpolation operator is singular — and that is precisely what the title flags and what has never been exercised.

Note on terminology: in this code `ns` is the polynomial **degree** (`splcoe(0:ns,:)`, evaluated as `sum splcoe(k,i)*x**k`), so `ns=4` is a quartic and its design error rate is O(h⁵).

## Current state

`test/source/test_spl_three_to_five.f90` (522 lines, added in `c6a56b0`, "Improve test coverage with meaningful non-tautological tests (#233)") is registered at `test/CMakeLists.txt:172-173` and `test/CMakeLists.txt:270`. Its driver list spans `test/source/test_spl_three_to_five.f90:12-24`; the order-specific part is lines 18-22:

```fortran
call test_spl_reg_order3(all_passed)
call test_spl_reg_order4(all_passed)
call test_spl_reg_order5(all_passed)
call test_spl_per_order3(all_passed)
call test_spl_per_order5(all_passed)
```

There is `test_spl_reg_order4` but **no `test_spl_per_order4`** — confirmed, the string does not occur anywhere in the file. That is the literal gap: even degree is covered for the regular spline and not for the periodic one.

The periodic quartic is reachable from user code with no guard:

- `spl_per` dispatches `ns==4` to `spl_four_per` at `src/spl_three_to_five.f90:665-673`; `construct_splines_1d` passes `order` straight through at `src/interpolate/interpolate.f90:131` (and the 2d/3d builders at `:303,317,483,499,519`).
- The batch layer dispatches periodic order 4 to `spl_four_per_line` at `src/interpolate/batch_interpolate_1d.f90:198,379` and `src/interpolate/batch_interpolate_3d.f90:357,414,475`.

**There are two independent copies of the defective routine, and both must be fixed:**

| Routine | Location | Suspect line |
|---|---|---|
| `spl_four_per` | `src/spl_three_to_five.f90:333-415` | `:385` |
| `spl_four_per_line` | `src/interpolate/acc_spline_build_order5.f90:245-326` | `:297` |

`src/spl_three_to_five.f90:380-389`:

```fortran
  d(n)=0.d0
  do i=n-1,1,-1
    d(i)=gam(i)-d(i+1)
  enddo

  phi=-.5d0*d(1)
  do i=1,n
    d(i)=d(i)+phi
    phi=-phi
  enddo
```

`src/interpolate/acc_spline_build_order5.f90:292-301` is the same block, reformatted, with `phi = -0.5d0*d(1)` at `:297`. A grep for `-0.5d0*d(1)` / `-.5d0*d(1)` across the repo finds exactly these two occurrences plus unrelated uses inside `c(n-1)` expressions.

`src/spl_three_to_five.f90` is the live source, referenced by path from `src/interpolate/CMakeLists.txt:2`, `src/efit_to_boozer/CMakeLists.txt:138` and `bench/spline_many/CMakeLists.txt:57`.

## Reproduction / evidence

Out of tree, no repo writes:

```bash
mkdir -p /tmp/spl && cd /tmp/spl
cp /path/to/libneo/src/spl_three_to_five.f90 .
# driver: build spl_per on [0,2pi] for f(x)=sin(x)+0.3*cos(2x) with
# h = 2*pi/(n-1) and nodes x_i=(i-1)*h (the convention of the existing
# test_spl_per_order3), evaluate the polynomial piece by Horner at 5001
# sample points spanning [0,2pi], report max|spline-exact|.
gfortran -O2 -o drv spl_three_to_five.f90 drv.f90 && ./drv
```

Observed (`gfortran 16.1.1`, `f(x)=sin(x)+0.3*cos(2x)` on `[0,2π]`):

| `ns` | n=33 | n=65 | n=129 | ratio | implied rate |
|---|---|---|---|---|---|
| 3 (`splper`) | 2.282e-05 | 1.409e-06 | 8.769e-08 | ~16 | O(h⁴) ✔ |
| **4 (`spl_four_per`)** | **1.981e-04** | **2.467e-05** | **3.081e-06** | **~8** | **O(h³) ✘** |
| 5 (`spl_five_per`) | 7.997e-08 | 1.195e-09 | 1.844e-11 | ~66 | O(h⁶) ✔ |

Order 4 is not merely below spec — at n=129 it is **35× less accurate than order 3 on the same grid**, and its rate is one order *worse* than the cubic. For contrast, `spl_reg` order 4 on `exp(-x)sin(3x)` over `[0,1]` gives 4.522e-08 → 8.882e-10 → 1.923e-11 (ratios 51, 46): the regular even-degree path is fine.

The mechanism is the parity of the interval count `n-1`:

| n | intervals | parity | max err |
|---|---|---|---|
| 33 | 32 | even | 1.98146e-04 |
| 65 | 64 | even | 2.46672e-05 |
| 129 | 128 | even | 3.08088e-06 |
| 34 | 33 | odd | 5.77119e-07 |
| 66 | 65 | odd | 1.81673e-08 |
| 130 | 129 | odd | 5.79631e-10 |

Odd interval counts give ratios 31.8 and 31.3 — clean **O(h⁵), the correct quartic rate**. Even interval counts collapse to O(h³). Since periodic grids in this codebase are overwhelmingly written as `n = 2^k + 1` over a full period (`h = 2*pi/(n-1)` with n=65 in the existing `test_spl_per_order3`), **the broken parity is the one everybody actually uses.**

### Why it survived

The spline is well-formed: for `ns=4, n=65` the knot jumps are C⁰ 1.4e-17, C¹ 3.7e-14, C² 1.0e-12, C³ 8.9e-16 — genuine C³ continuity — and interpolation at the nodes is exact. This is not a coding slip producing garbage.

The backward recursion `d(i) = gam(i) - d(i+1)` determines `d` only up to the alternating vector `d(i) = (-1)**i * c`. That vector closes periodically iff `(-1)**(n-1) = 1`, i.e. iff `n` is odd, i.e. iff the interval count `n-1` is **even**. So:

- **Odd interval count** (`n` even): the alternating vector is *not* periodic, the closure is unique, and the existing `phi = -0.5d0*d(1)` shift produces exactly the right solution (it enforces `d(n) = d(1)`). Measured O(h⁵). **This path is correct and must not be disturbed.**
- **Even interval count** (`n` odd): the alternating vector *is* a genuine null vector, the system is singular, and every member of the solution family interpolates exactly at the nodes and is C³ — which is why all cheap checks pass. The existing shift picks the member satisfying `d(n) = -d(1)`, an antiperiodic condition, and that member is not the accurate one.

### The obvious one-line fix is wrong — verified

Replacing the shift with a symmetric mean-removal of the alternating component *unconditionally* is the tempting fix. It was implemented and measured, and it **regresses the currently-correct odd-interval path** from O(h⁵) to ~O(h⁴):

| n | intervals | baseline | unconditional mean-removal |
|---|---|---|---|
| 34 | 33 (odd) | 5.771e-07 | 1.698e-05 |
| 66 | 65 (odd) | 1.817e-08 | 9.329e-07 |
| 130 | 129 (odd) | 5.796e-10 | 5.419e-08 |

The fix **must be conditional on the parity of `n-1`**.

### A parity-conditional fix that was measured to work

Applied in place of the `phi` block, this restores O(h⁵) on both parities:

```fortran
  if(mod(n-1,2).ne.0) then
    ! odd interval count: alternating vector is not periodic, closure is unique
    phi=-.5d0*d(1)
    do i=1,n
      d(i)=d(i)+phi
      phi=-phi
    enddo
  else
    ! even interval count: alternating vector is a null mode, remove its mean
    phi=0.d0
    do i=1,n-1
      phi=phi+(-1.d0)**i*d(i)
    enddo
    phi=phi/dble(n-1)
    do i=1,n
      d(i)=d(i)-(-1.d0)**i*phi
    enddo
  endif
```

Measured on `f(x)=sin(x)+0.3*cos(2x)`:

| n | intervals | baseline | with fix |
|---|---|---|---|
| 33 | 32 (even) | 1.981e-04 | 6.705e-07 |
| 65 | 64 (even) | 2.467e-05 | 1.962e-08 |
| 129 | 128 (even) | 3.081e-06 | 6.014e-10 |
| 34 | 33 (odd) | 5.771e-07 | 5.771e-07 (unchanged) |
| 66 | 65 (odd) | 1.817e-08 | 1.817e-08 (unchanged) |
| 130 | 129 (odd) | 5.796e-10 | 5.796e-10 (unchanged) |

Even-count ratios become 34.2 and 32.6 (O(h⁵)), and n=65 vs n=66 now agree to a factor of 1.08. Checked on three functions (`sin(x)`, `exp(cos(x))`, `sin(3x)+0.7cos(x)-0.2sin(2x)`); in every case the even-count curve moves onto the odd-count curve and the odd-count curve is bit-for-bit unchanged. Treat this as a verified-working starting point, not as a mandate — any alternative that meets the acceptance criteria is fine.

### Two traps for whoever writes the test

1. **Polynomial exactness cannot catch this.** A quartic polynomial is not periodic, so there is no polynomial you can feed `spl_per` that both exercises degree 4 and respects the boundary condition. The test *must* be a convergence-rate test.
2. **The test function matters.** The size of the wrong alternating component depends on the function's symmetry about the first node. `exp(cos(x))` (symmetric about x=0) shows **no defect at all** on even interval counts — baseline 1.259e-04 / 1.929e-06 / 4.919e-08 / 1.465e-09, already O(h⁵). Do not "fix" a failing test by changing the function. `sin(x)+0.3*cos(2x)` exposes the defect and is the function the acceptance criteria are stated against.

## Behaviour (BDD)

```gherkin
Scenario: Periodic quartic spline attains its design order on an even interval count
  Given f(x) = sin(x) + 0.3*cos(2*x) sampled on [0, 2*pi] with n = 33, 65, 129
    And h = 2*pi/(n-1) and nodes x_i = (i-1)*h, so the interval count n-1 is even
  When test_spl_per_order4 calls spl_per(4, n, h, splcoe) and evaluates by Horner
       at 5001 points spanning [0, 2*pi]
  Then max|spline - exact| shall satisfy err(65)/err(129) >= 24.0
    And max|spline - exact| at n = 129 shall be < 1.0d-8
   # baseline fe3f76e: ratio 8.0, err(129) = 3.081e-06 -- FAILS
   # with the parity fix: ratio 32.6, err(129) = 6.014e-10 -- passes

Scenario: Periodic quartic spline is never worse than the periodic cubic
  Given the same f and the same grid n = 129, h = 2*pi/128
  When spl_per(3, ...) and spl_per(4, ...) are both built
  Then max|spline - exact| for ns = 4 shall be strictly smaller than for ns = 3
   # baseline: 3.081e-06 (ns=4) vs 8.769e-08 (ns=3) -- FAILS by a factor of 35
   # with the fix: 6.014e-10 vs 8.769e-08 -- passes with 146x margin

Scenario: Parity of the interval count does not change the convergence order
  Given f(x) = sin(x) + 0.3*cos(2*x) on [0, 2*pi]
  When spl_per(4, ...) is built for n = 65 (64 intervals) and n = 66 (65 intervals)
  Then the two max errors shall agree within a factor of 4.0
   # baseline: 2.467e-05 vs 1.817e-08, a factor of 1358 -- FAILS
   # with the fix: 1.962e-08 vs 1.817e-08, a factor of 1.08 -- passes
   # this scenario is what catches an unconditional mean-removal, which would
   # give 1.962e-08 vs 9.329e-07, a factor of 47.6 -- still FAILS

Scenario: The odd-interval path does not regress
  Given f(x) = sin(x) + 0.3*cos(2*x) on [0, 2*pi] with n = 34, 66, 130
  When spl_per(4, n, h, splcoe) is built
  Then max|spline - exact| shall satisfy err(66)/err(130) >= 24.0
    And max|spline - exact| at n = 130 shall be < 1.0d-8
   # baseline: ratio 31.3, err = 5.796e-10 -- ALREADY PASSES, this is a guard

Scenario: The batch periodic order-4 path attains its design order
  Given the same f on n = 65 periodic nodes in the third dimension
  When construct_batch_splines_3d is called with order(3) = 4, periodic(3) = .true.
       for n = 33, 65, 129
  Then max|spline - exact| shall satisfy err(65)/err(129) >= 24.0
   # exercises spl_four_per_line, the second copy of the defect

Scenario: Existing coverage does not regress
  Given the current test suite
  When `cd build && ctest -R "test_spl_three_to_five|test_interpolate|test_batch_interpolate" --output-on-failure` is run
  Then every listed test shall pass
```

## Implementation plan

`CODING_STANDARD.md:42` says "Write test *before* code", so the failing test lands first, in its own commit.

1. **`test/source/test_spl_three_to_five.f90`** — add `subroutine test_spl_per_order4(passed)` in the `contains` block, modelled on `test_spl_per_order5` (lines 417-456) but written as a **convergence-rate** check, not a point check: loop `n` over `(/33, 65, 129/)`, build with `spl_per(4, n, h, splcoe)` using `h = 2*pi/(n-1)`, evaluate by Horner over 5001 sample points, store `emax(k)`, assert `emax(2)/emax(3) >= 24.0` and `emax(3) < 1.0d-8`. Register it by inserting `call test_spl_per_order4(all_passed)` at line 22, between the existing `test_spl_per_order3` and `test_spl_per_order5` calls. No CMake change is needed — the executable and `add_test` already exist at `test/CMakeLists.txt:172-173,270`.
2. **`test/source/test_spl_three_to_five.f90`** — add `subroutine test_spl_per_order4_parity(passed)` (scenario 3: n=65 vs n=66, factor-of-4 agreement) and `subroutine test_spl_per_order4_odd(passed)` (scenario 4: the odd-count regression guard). Register both. Confirm the suite now fails, and note which of the three fail: `cd build && ctest -R test_spl_three_to_five --output-on-failure`. Expected at `fe3f76e`: scenarios 1, 2 and 3 fail; scenario 4 passes and stays passing.
3. **`src/spl_three_to_five.f90`** — fix `spl_four_per` (lines 333-415) by replacing the `phi` block at lines 385-389 with a parity-conditional treatment. The block quoted above under "A parity-conditional fix that was measured to work" is a verified starting point. Keep the routine `recursive` and keep the `fac = 1.d0/h` rescaling block (lines 404-411) untouched. Do not apply an unconditional mean-removal — measurements above show it regresses the odd-interval path.
4. **`src/interpolate/acc_spline_build_order5.f90`** — apply the identical fix to `spl_four_per_line` (lines 245-326), whose `phi = -0.5d0*d(1)` sits at line 297. This is the routine the batch/OpenACC path actually calls; skipping it leaves `construct_batch_splines_{1,3}d` broken and makes step 6 unfixable. Mind the `!$acc routine seq` context: keep the added code branch-simple and free of allocation.
5. **`test/source/test_interpolate.f90`** — add a periodic order-4 case through the public API (`construct_splines_1d(..., order=4, periodic=.true., spl)`, `src/interpolate/interpolate.f90:113-135`) so the fix is pinned where users actually call it, not only at the kernel.
6. **`test/source/test_batch_interpolate.f90`** — add the equivalent order-4 periodic case for the batch layer (scenario 5), which reaches `spl_four_per_line` via `src/interpolate/batch_interpolate_3d.f90:357,414,475`.
7. **`src/spl_three_to_five.f90`** — while in the file, confirm `spl_four_reg` (lines 263-330) is free of the same class of defect. Measurement says it is already O(h⁵) (4.522e-08 → 8.882e-10 → 1.923e-11 on `exp(-x)sin(3x)`), so this should be a no-op; record the numbers in the PR rather than changing code.
8. **Downstream.** Steps 3-4 change numerical output for any consumer using periodic order-4 splines. The checked-out downstreams use order 5 or order 3 throughout — SIMPLE `order = [5,5,5]` (`test/test_batch_splines.f90:63`) and `ns_tp = 5`, rabe `order = [5,5]` (`src/field/fourier_field.f90:113`), MEPHIT `nspl = 3` (`src/magdata_in_symfluxcoord.f90:4`), NEO-RT `nspl = 3` (`POTATO/BOOZER_TO_EFIT/SRC/magdata_in_symfluxcoord.f90:3`); inside libneo, `ns_tp_B = 5` at `src/boozer_converter.F90:1360` and `nspl = 3` at `src/efit_to_boozer/efit_to_boozer_mod.f90:3`. No order-4 periodic use was found, so the blast radius should be nil — the reverse-dependency gate (`.github/workflows/downstream-gate.yml`, gated set in `ci/downstreams`) will confirm. No ordered PR dependency expected.

If you prefer atomic issues, steps 1-2 (the failing test) and steps 3-6 (the fix) split cleanly, and step 1 alone is already worth landing since it converts a silent accuracy loss into a red build.

## Acceptance criteria

- [ ] `test_spl_per_order4`, `test_spl_per_order4_parity` and `test_spl_per_order4_odd` exist in `test/source/test_spl_three_to_five.f90` and are called from the driver list.
- [ ] `test_spl_per_order4` and `test_spl_per_order4_parity` **fail** on `fe3f76e` and pass after the fix (evidence in the PR description). `test_spl_per_order4_odd` passes both before and after — it is a regression guard.
- [ ] `spl_per(4, ...)` on `f(x)=sin(x)+0.3*cos(2x)` over `[0,2π]` achieves `err(n=65)/err(n=129) >= 24.0` (currently 8.0).
- [ ] `spl_per(4, 129, ...)` max error `< 1.0d-8` (currently 3.081e-06).
- [ ] `spl_per(4, ...)` error at n=65 (even intervals) and n=66 (odd intervals) agree within a factor of 4 (currently 1358).
- [ ] `spl_per(4, ...)` at n=130 stays `< 1.0d-8` with `err(66)/err(130) >= 24.0` — the odd-interval path is not regressed.
- [ ] `spl_per(4, ...)` is strictly more accurate than `spl_per(3, ...)` on the same grid.
- [ ] `spl_four_per_line` in `src/interpolate/acc_spline_build_order5.f90` carries the same fix, and the batch periodic order-4 case in `test/source/test_batch_interpolate.f90` meets the same rate bar.
- [ ] `cd build && ctest --output-on-failure` passes in full, in particular `test_interpolate`, `test_batch_interpolate`, `test_batch_interpolate_oracle`, `test_batch_eval_oracle` and `test_boozer_converter_vs_simple`.
- [ ] The downstream gate is green: SIMPLE, NEO-2, MEPHIT, KAMEL and rabe are blocking; NEO-RT is report-only (`ci/downstreams`).

## References

- C. de Boor, *A Practical Guide to Splines*, Springer, Applied Mathematical Sciences 27, 1978 (rev. ed. 2001) — standard treatment of spline interpolation conditioning, including why even-degree splines are naturally interpolated at points staggered from the knots (knot averages / Greville abscissae) rather than at the knots themselves. Background for why the knot-interpolated periodic quartic is the delicate case; it does not describe this specific code.
- J. H. Ahlberg, E. N. Nilson, J. L. Walsh, *The Theory of Splines and Their Applications*, Academic Press, 1967 — cyclic/periodic spline systems and the structure of the associated circulant matrices.
- The parity argument itself needs no external citation and is verified directly above: the alternating vector `(+1,-1,+1,...)` closes on itself under periodic wrap-around iff the number of distinct nodes `n-1` is even, which is exactly when the fix-up at `src/spl_three_to_five.f90:385` and `src/interpolate/acc_spline_build_order5.f90:297` selects the wrong member of the solution family.

## Scope and risk

Single PR, moderate: new rate-based tests in an existing test program (no CMake wiring needed) plus a ~15-line parity-conditional change applied to **two** routines, `spl_four_per` and `spl_four_per_line`. The main risk is doing the fix unconditionally and silently regressing the odd-interval path — scenario 3 and the odd-count guard exist specifically to catch that. Secondary risk is step 3 shifting numerical output for consumers of periodic order-4 splines; none were found in libneo's production paths or in the checked-out downstreams, and the gate covers the rest. If the fix proves harder than expected, landing steps 1-2 alone is still net-positive — an `error stop` on a known accuracy defect beats silent O(h³).

Related but not duplicate: itpplasma/libneo#204 ("interpolate: consolidate spline build/eval backends and keep legacy as test oracle") would be a natural place to inherit these rate tests as the oracle's acceptance bar — and note that #204's consolidation would also collapse the two duplicated copies of this defect into one.
