### ISSUE TITLE
Integration test API

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#31]
Add triggers to integration testing in Gitlab.

* Internal codes and test data are not exposed
* Integration tests can only be modified by in-house developers
* libneo itself contains only tests with public data
* Branches with same name are preferred with fallback to main

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Three of the four bullets here are done, but on GitHub rather than GitLab. The fourth — *"Branches with same name are preferred with fallback to main"* — is the one requirement that the current gate does **not** implement, and it is the requirement that makes coordinated breaking changes possible at all. Rescoping the issue to that.

## Purpose

libneo is upstream of SIMPLE, NEO-2, MEPHIT, KAMEL, rabe and NEO-RT, and every libneo PR is blocked on those codes staying green (`.github/workflows/downstream-gate.yml`, `ci/downstreams`). Today the gate always builds the downstream at its **default branch**: `gh workflow run "$wf" -R "itpplasma/$repo" --ref main` (`.github/workflows/downstream-gate.yml:119`). That is correct for a non-breaking libneo change and a deadlock for a breaking one: a libneo PR that renames a public symbol or changes a signature makes `SIMPLE@main` fail to compile, the gate goes red, and the only way out is to merge the downstream adaptation first — which cannot itself build, because it needs the unmerged libneo. The escape hatch the original issue asked for is the standard convention across this org already: a downstream branch of the same name as the libneo branch is preferred, `main` is the fallback. SIMPLE already implements exactly that semantics in the *other* direction (`SIMPLE/cmake/Util.cmake:3-43`, `get_branch_or_main`), so the convention is established; the gate simply does not honor it.

## Current state

**Already satisfied by `#278` (`08e6bd5`, "Per-PR reverse-dependency gate against downstream codes"), which superseded the GitLab premise of this issue:**

- *"Internal codes and test data are not exposed"* — the gate never checks out downstream sources. It calls `gh workflow run` on the downstream repo and polls the run (`run_wf`, `downstream-gate.yml:109-145`); private code and fixtures stay inside the downstream repo and its own runners.
- *"Integration tests can only be modified by in-house developers"* — the integration workflows live in the org-owned downstream repos, and the gate refuses to run for forks: `github.event.pull_request.head.repo.full_name == github.repository` (`downstream-gate.yml:37`), with the reason stated in the header comment at `downstream-gate.yml:13-15` (a fork head SHA is not on origin, so downstream `FetchContent` could not resolve it).
- *"libneo itself contains only tests with public data"* — `test/resources/` holds three public fixtures only (`convexwall.dat`, `input_boozer_file.dat`, `input_efit_file.dat`); the odeint golden record is derived from libneo's own latest public tag (`test/odeint/fetch_golden_record.sh:20-29`), not from an internal dataset.

**Not satisfied — the gap this issue should now track.** The gated set and its per-row policy live in `ci/downstreams:31-36`:

```
SIMPLE   main.yml         yes   yes
NEO-2    unit-tests.yml   yes   no
MEPHIT   main.yml         yes   yes
KAMEL    ci.yml           yes   yes
rabe     test.yml         yes   golden.yml
NEO-RT   test.yml         no    no
```

and the dispatch itself is hard-pinned to `main` (`downstream-gate.yml:109-124`):

```bash
run_wf() {
  local repo=$1 wf=$2; shift 2
  ...
      # --ref main skips gh's GraphQL default-branch lookup, which fails
      # hard when the token's hourly API quota is drained. Dispatch
      # errors are retried with backoff for the same reason.
      dispatched=0
      for _ in 1 2 3; do
        if gh workflow run "$wf" -R "itpplasma/$repo" --ref main \
             -f "libneo_ref=$REF" "$@"; then
```

`REF` is the libneo PR head SHA (`downstream-gate.yml:45`), and downstream workflows already accept it as an input — e.g. `SIMPLE/.github/workflows/main.yml:9-13` declares `libneo_ref` and consumes it at lines 83 and 170. So the *libneo side* of the ref plumbing is complete; only the *downstream* ref is frozen.

Note also that libneo's own `cmake/Modules/Util.cmake:36` still carries a `get_branch_or_main` implementation, but it is dead: nothing in `CMakeLists.txt` or `cmake/*.cmake` includes `Modules/Util.cmake` any more — the only references to the symbol are inside that file itself (line 20, line 36). It was orphaned by `137fc8d`, "Always FetchContent dependencies; drop `$ENV{CODE}` local-source bypass (#319)". Do not reuse it as the reference implementation — `SIMPLE/cmake/Util.cmake:3-43` is the maintained version, and it is the one that added the `main`-fallback warning (line 39) and the `GITHUB_HEAD_REF`/`GITHUB_REF_NAME` fallbacks (lines 14-17) that libneo's copy lacks.

## Reproduction / evidence

Deadlock, reproducible without touching CI. Note that SIMPLE resolves libneo through `FetchContent` from `https://github.com/itpplasma/libneo.git` (`SIMPLE/cmake/Util.cmake:73`), so a branch-ref repro needs the libneo branch **pushed**; the override variable is `LIBNEO_REF` (`SIMPLE/Makefile:9-11`, consumed at `SIMPLE/cmake/Util.cmake:77`), not a `*_BRANCH` variable.

```bash
# 1. Take any public libneo symbol used by SIMPLE and rename it on a branch.
cd libneo && git switch -c fix/rename-demo
#    e.g. rename a public procedure in src/odeint/odeint_allroutines.f90
#    and update all libneo call sites + tests so libneo itself is green:
make && make test          # green  (Makefile:14 all, Makefile:29 test)
git push -u origin fix/rename-demo

# 2. Build SIMPLE@main against that libneo, exactly as the gate does:
cd ../SIMPLE && git switch main
make build-deterministic LIBNEO_REF=fix/rename-demo
```

(For a fully offline variant, use `make build-deterministic LIBNEO_PATH=/abs/path/to/libneo`, which maps to `-DLIBNEO_SOURCE_DIR` at `SIMPLE/Makefile:13-15` and skips the fetch. `LIBNEO_REF`/`LIBNEO_PATH` are honored only as **command-line** assignments — `$(origin ...)` deliberately ignores the ambient environment.)

Observed: SIMPLE@main fails to compile (unresolved symbol), so `downstream-gate` reports `::error::SIMPLE CI red against libneo <sha>` (`downstream-gate.yml:173`) and, because `SIMPLE` is `blocking=yes` in `ci/downstreams`, `fail=1` propagates to `exit $fail` (`downstream-gate.yml:179`) and fails the libneo PR. Expected after this change: the gate finds `itpplasma/SIMPLE` branch `fix/rename-demo` (the adaptation branch), dispatches `main.yml` from that ref with `libneo_ref=<libneo PR sha>`, and gates on that combination.

Verification recipe for the implemented feature, on a throwaway pair of branches:

```bash
# Create a no-op branch of the same name in both repos.
gh api repos/itpplasma/libneo/git/refs -f ref=refs/heads/test/gate-branch-match \
    -f sha=$(gh api repos/itpplasma/libneo/git/ref/heads/main -q .object.sha)
gh api repos/itpplasma/SIMPLE/git/refs  -f ref=refs/heads/test/gate-branch-match \
    -f sha=$(gh api repos/itpplasma/SIMPLE/git/ref/heads/main  -q .object.sha)
# Open a libneo PR from test/gate-branch-match, then inspect the gate log.
```

Expected in the gate log: `SIMPLE (main.yml) against libneo <sha> [downstream ref test/gate-branch-match]`, and `gh run view <id> -R itpplasma/SIMPLE --json headBranch` returns `test/gate-branch-match`. With the SIMPLE branch deleted and the libneo branch kept, the same run must report the fallback and dispatch at `main`.

## Behaviour (BDD)

```gherkin
Scenario: Downstream branch of the same name is preferred
  Given a libneo PR whose head branch is "fix/rename-demo"
  And itpplasma/SIMPLE has a branch "fix/rename-demo" containing .github/workflows/main.yml
  When downstream-gate dispatches SIMPLE main.yml
  Then the dispatch uses --ref fix/rename-demo
  And the dispatched run's headBranch is "fix/rename-demo"
  And the run receives libneo_ref equal to github.event.pull_request.head.sha

Scenario: Fallback to main when no matching downstream branch exists
  Given a libneo PR whose head branch is "fix/spline-tolerance"
  And itpplasma/NEO-2 has no branch named "fix/spline-tolerance"
  When downstream-gate dispatches NEO-2 unit-tests.yml
  Then the dispatch uses --ref main
  And no warning annotation about a missing branch is emitted
  And exactly one branch-existence API call is made per downstream

Scenario: Matching branch exists but predates the gated workflow file
  Given itpplasma/KAMEL has a branch "fix/rename-demo" that does not contain .github/workflows/ci.yml
  When downstream-gate dispatches KAMEL ci.yml at that ref
  Then the dispatch fails with an HTTP 404 or 422
  And the gate retries once at --ref main
  And it emits "::warning::KAMEL fix/rename-demo lacks ci.yml — falling back to main"
  And the gate verdict is taken from the main-ref run, not from the failed dispatch

Scenario: Branch matching does not change the full-ci extra-workflow path
  Given a libneo PR labeled "full-ci" whose head branch is "fix/rename-demo"
  And itpplasma/rabe has a branch "fix/rename-demo"
  When downstream-gate processes the rabe row (full column "golden.yml")
  Then both test.yml and golden.yml are dispatched at --ref fix/rename-demo
  And both receive libneo_ref equal to the libneo PR head SHA
```

## Implementation plan

1. **`.github/workflows/downstream-gate.yml`** — add `HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}` to the `env:` block at lines 43-46, next to the existing `REF` (line 45) and `FULL` (line 46).
2. **`.github/workflows/downstream-gate.yml`** — add a helper next to `latest_dispatch_id()` (lines 53-56):
   ```bash
   # Downstream ref to run the integration workflow from: a branch of the same
   # name as the libneo PR branch if it exists, else main. One API call per
   # downstream; any error resolves to main (never fails the gate on its own).
   downstream_ref() {
     local repo=$1
     [ -z "${HEAD_BRANCH:-}" ] && { echo main; return; }
     if gh api "repos/itpplasma/$repo/git/ref/heads/$HEAD_BRANCH" \
          --silent >/dev/null 2>&1; then
       echo "$HEAD_BRANCH"
     else
       echo main
     fi
   }
   ```
   Use `git/ref/heads/<branch>` rather than `branches/<branch>`: it is exact-match and does not fall back to fuzzy resolution. It resolves correctly for slash-containing branch names. Resolve it **once per downstream row**, not once per `run_wf` call, so the `full-ci` extra-workflow loop reuses the same ref.
3. **`.github/workflows/downstream-gate.yml`** — change `run_wf()` (lines 109-145) to take the ref as its first argument (`run_wf <ref> <repo> <wf> [extra -f …]`) and substitute `--ref "$dref"` for the literal `--ref main` at line 119. Keep the existing 3× dispatch retry with 30 s backoff (lines 118-124) and the comment at lines 114-116, amended to say the ref is now explicit per downstream (the point of that comment — avoiding gh's GraphQL default-branch lookup — still holds because a ref is always passed).
4. **`.github/workflows/downstream-gate.yml`** — inside `run_wf`, if all three dispatch attempts fail **and** `$dref != main`, fall back once: re-run the dispatch loop with `--ref main`, emit `::warning::$repo $dref lacks $wf — falling back to main`, and only then take the existing error path at line 126. This covers the third BDD scenario (stale downstream branch without the workflow file); without it, an old same-named branch turns into a hard gate failure.
5. **`.github/workflows/downstream-gate.yml`** — update the row loop at line 150 to call `dref=$(downstream_ref "$repo")` before the `full`/fast branch, pass `$dref` into every `run_wf` call (lines 159, 161, 166 — including the `IFS=','` extra-workflow loop), and add the ref to the `::group::` header at line 155 so the log states which downstream ref was used.
6. **`.github/workflows/downstream-gate.yml`** — extend the header comment block (lines 1-15) with the branch-matching rule and its precedence, so the convention is documented where maintainers look first.
7. **`ci/downstreams`** — extend the column documentation comment (lines 1-30) with one paragraph stating that the *ref* the workflow is dispatched from is resolved automatically (same-named branch, else `main`) and is not a per-row column. No changes to rows 31-36.
8. **`.github/workflows/downstream-gate.yml`** — the token needs `contents:read` on the downstream repos to resolve `git/ref/heads/*`. The header comment at lines 13-14 records only that `RELEASE_BOT_TOKEN` has `actions:write` there; confirm the read scope before merging. If it is missing, `gh api` returns non-zero and the helper resolves everything to `main` — which is exactly today's behaviour, so the change is fail-safe.
9. **Test.** There is no harness for shell inside workflow YAML in this repo, so extract the pure decision into a testable script: create **`ci/downstream_ref.sh`** containing `downstream_ref()` (sourced by the workflow via `. ci/downstream_ref.sh`, which `actions/checkout@v4` at line 40 already makes available), and add **`test/scripts/test_downstream_ref.sh`** driving it with a stubbed `gh` on `PATH` that returns 0 for one repo/branch pair and non-zero otherwise, asserting four cases: match, no match, empty `HEAD_BRANCH`, and API error. Register it in `test/CMakeLists.txt` alongside the existing `add_test` entries (e.g. line 249) with `add_test(NAME test_downstream_ref COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/scripts/test_downstream_ref.sh)` so `make test` covers it.
10. **No downstream repo changes are required.** All six gated workflows already declare a `libneo_ref` `workflow_dispatch` input on their default branch — verified in `SIMPLE/.github/workflows/main.yml:9-13`, `NEO-2/.github/workflows/unit-tests.yml`, `MEPHIT/.github/workflows/main.yml`, `KAMEL/.github/workflows/ci.yml`, `rabe/.github/workflows/{test,golden}.yml` and `NEO-RT/.github/workflows/test.yml`. A same-named feature branch inherits the input as long as it is branched from a current `main`; a downstream branch forked before that input existed will fail dispatch and take the `main` fallback from step 4.

## Acceptance criteria

- [ ] `make && make test` passes, including the new `test_downstream_ref` case.
- [ ] `actionlint .github/workflows/downstream-gate.yml` reports no syntax error.
- [ ] A libneo PR from branch `test/gate-branch-match`, with a same-named branch present in `itpplasma/SIMPLE`, produces a SIMPLE run whose `headBranch` is `test/gate-branch-match` and whose `libneo_ref` input equals the libneo PR head SHA.
- [ ] The same PR, with the SIMPLE branch deleted, produces a SIMPLE run whose `headBranch` is `main`, with no warning annotation.
- [ ] A same-named downstream branch that lacks the gated workflow file yields exactly one `::warning::` and a green/red verdict taken from the `main`-ref run, never a bare dispatch error.
- [ ] Exactly one extra API call per downstream row (six total) — verified by counting `gh api .../git/ref/heads/` lines in the gate log; the token's hourly quota concern documented at `downstream-gate.yml:66-68` is not regressed.
- [ ] A libneo PR whose branch name matches nothing anywhere behaves byte-identically to today: all six dispatched at `--ref main`.
- [ ] `ci/downstreams` rows 31-36 are unchanged; the six-repo gated set and their `blocking`/`full` policy are untouched.

## References

No specific literature reference; this is CI/build-infrastructure work internal to the org. The prior art is in-repo and in-org:

- `SIMPLE/cmake/Util.cmake:3-43` — `get_branch_or_main`, the maintained same-name-else-`main` implementation, on the dependency-resolution side.
- `libneo/cmake/Modules/Util.cmake:36` — the older, orphaned copy of the same idea (do not reuse).
- libneo#278 (`08e6bd5`) — the gate this issue now amends.
- itpplasma/code#55 — the `<DEP>_BRANCH` convention in the consumers.

## Scope and risk

Single PR, roughly 40 lines of shell in one workflow plus a small extracted script and its test. The change is fail-safe by construction: any failure to resolve a branch degrades to today's `--ref main` behaviour. The real risks are (a) an extra `gh api` call per downstream against the token's hourly quota, already a known constraint documented at `downstream-gate.yml:66-68`, and (b) stale same-named branches in downstream repos silently becoming the gated ref — mitigated by naming the ref in the `::group::` header (step 5) and by branch hygiene under `CODING_STANDARD.md:62` (stale branches deleted, or renamed `archive/...` with a README).

Related open issues: **itpplasma/libneo#277** (release-time gate: poll, tag, bump PRs) is the release-branch counterpart and would want the same helper; **itpplasma/code#55** standardizes `<DEP>_BRANCH` in the consumers. Neither subsumes this one — they gate on a *release branch*, not on a same-named *feature* branch.
