### ISSUE TITLE
Add checks between Fortran and Python EQDSK routines

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#33]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still relevant. libneo parses the G-EQDSK format independently in Fortran and in Python, and no test compares the two. Below is a cross-language failure reproduced at HEAD, plus the spec to close the gap.

## Purpose

A GEQDSK file is the primary equilibrium input for `efit_to_boozer`, `field_eq`/`field_divB0`, `geoflux_coordinates`, and everything downstream (NEO-2, NEO-RT, MEPHIT). libneo parses that format in several independent places across two languages, and the parsers have drifted. When the Python writer emits a record the Fortran reader cannot parse — or when the two readers disagree on a unit or an array orientation — the error is silent at the interface and shows up much later as a wrong iota or a mirrored flux map. A cross-language conformance test is the cheapest way to pin the format contract down.

## Current state

Fortran readers/writers:

- `src/magfie/geqdsk_tools.f90:64-138` `geqdsk_read` — the full reader; populates `geqdsk_t` (`geqdsk_tools.f90:21-30`) and **converts everything to CGS** on the way in (`geqdsk_tools.f90:99-137`, factors from `src/util/math_constants.f90:45-52`). `geqdsk_write` (`geqdsk_tools.f90:140-167`) converts back to SI with hard-coded literals.
- `src/magfie/field_divB0.f90:377-443` `read_eqfile1` and `:446-506` `read_eqfile2` — raw readers, SI, no consistency handling. The header is parsed separately again by `read_dimeq1` (`field_divB0.f90:359-374`, format `(6a8,3i4)`), and `read_eqfile_west` (`:551`) is a further WEST-variant GEQDSK reader. All of these are module procedures of `module field_sub` (`field_divB0.f90:1`), which declares no `private`, so they are directly `use`-able.

Python readers/writers:

- `python/libneo/eqdsk_base.py:11-101` `read_eqdsk` / `:105-164` `write_eqdsk` — dict-based, **SI throughout**.
- `python/libneo/eqdsk.py:132` `eqdsk_file.generate_from_file` — a second, independent Python parser, with `try/except` fixed-width→free-form fallbacks (`eqdsk.py:150-169`, `:178-200`); this is the class documented in `docs/eqdsk.rst`.

Existing tests are all *intra*-language:

- `test/source/test_geqdsk_tools.f90:57-90` — Fortran write→read round trip, comparing only four integers (`nw`, `nh`, `nbbbs`, `limitr`); note `limitr` is compared against itself (`geqdsk_in%limitr == geqdsk_in%limitr`, **`test_geqdsk_tools.f90:82`**), so that field is effectively untested.
- `test/python/test_eqdsk_base.py:24-35` — Python write→read round trip.
- `python/tests/test_eqdsk_base.py:43-57` `test_write_eqdsk_header_matches_3i4_columns` — checks the header `(3i4)` columns, added in `cf8fc44` ("Write EQDSK header dimensions in fixed 3i4 columns (#396)"). Its docstring already states the motivation is Fortran readability — but it asserts on the *string columns*, not on an actual Fortran read. That is the half-measure this issue asks to complete.

Nothing anywhere reads a file with one language and compares against the other.

The remaining mismatch is the boundary-count record. Fortran:

```fortran
! src/magfie/geqdsk_tools.f90:34
character(len = *), parameter :: format_2022 = '(2i5)'
! src/magfie/geqdsk_tools.f90:90
read (fid, format_2022) geqdsk%nbbbs, geqdsk%limitr
```

Python:

```python
# python/libneo/eqdsk_base.py:160
f.write(f"{eqdata['npbound']} {eqdata['nplimiter']}\n")
```

Free-form on write, fixed `(2i5)` on read.

## Reproduction / evidence

Fixture: `test/resources/input_efit_file.dat` (nw=65, nh=129; line 1748 reads `  209  773`).

```bash
cd /path/to/libneo
PYTHONPATH=$PWD/python MPLBACKEND=Agg python3 - <<'PY'
from libneo.eqdsk_base import read_eqdsk, write_eqdsk
d = read_eqdsk("test/resources/input_efit_file.dat")
print(d["npbound"], d["nplimiter"])          # 209 773
print(d["PsiVs"].shape)                       # (129, 65)  == (nzgr, nrgr)
write_eqdsk("/tmp/py_written.geqdsk", d)
PY
grep -nE '^[0-9]+ [0-9]+$' /tmp/py_written.geqdsk
# 1748:209 773      <-- free-form, not (2i5)
```

Now parse that record the way `geqdsk_read` does:

```bash
cat > /tmp/t.f90 <<'EOF'
program t
  integer :: fid, n1, n2, ios
  open(newunit=fid, file='rec.txt', status='old', action='read')
  read(fid, '(2i5)', iostat=ios) n1, n2
  print *, 'ios=', ios, ' n1=', n1, ' n2=', n2
end program t
EOF
gfortran -o /tmp/t /tmp/t.f90
printf '209 773\n' > rec.txt && /tmp/t
```

Observed (gfortran, default `BLANK='NULL'`):

```
 ios=           0  n1=        2097  n2=          73
```

Expected: `n1 = 209, n2 = 773`. `iostat` is **0** — the read silently succeeds with wrong values. Other counts fail the same way, while the Fortran-written fixed-width form is fine:

```
'33 33'                     -> n1=3333, n2=0
'129 129'                   -> n1=1291, n2=29
'  209  773' (Fortran-written) -> n1=209, n2=773   (correct)
```

Replaying the whole of `geqdsk_read` (same formats and same read sequence, with `iostat=` added, which the real routine does not have) against `/tmp/py_written.geqdsk` gives:

```
 hdr    ios=0  nw=65  nh=129        <-- (a48,3i4) header is fine since cf8fc44
 l2..l5 ios=0                       <-- (5es16.9) records are fine
 fpol/pres/ffprim/pprime ios=0
 psirz  ios=0
 qpsi   ios=0
 2i5    ios=0  nbbbs=2097  limitr=73   <-- WRONG, silently
 bbbs   ios=-1                          <-- end of file
 lim    ios=5001
```

`geqdsk_read` then does `allocate(geqdsk%rbbbs(2097))` and tries to read 4194 reals where 418 exist (`geqdsk_tools.f90:91-96`), with no `iostat=` on any of those reads, so **the program aborts on end-of-file**. So: files written by `libneo.eqdsk_base.write_eqdsk` are not readable by libneo's own `geqdsk_read`.

Rewriting only line 1748 of that same file as `%5d%5d` and replaying makes every record parse with `ios=0` through to the end. The `(2i5)` record is therefore the *only* remaining format mismatch, and the one-line fix in step 1 is sufficient to close it.

Second, non-bug but must be encoded in the test: `geqdsk_read` returns CGS (`geqdsk_tools.f90:99-137`), Python returns SI. A cross-check must apply `length_si_to_cgs = 1e2`, `magneticflux_si_to_cgs = 1e8`, `magneticfield_si_to_cgs = 1e4`, `pressure_si_to_cgs = 1e1`, `current_si_to_cgs = 1e-1*C` (`src/util/math_constants.f90:45-52`) explicitly rather than comparing raw numbers.

Third, orientation: `geqdsk%psirz(kw, kh)` is `(R, Z)` (`geqdsk_tools.f90:88`) while `eqdata['PsiVs']` is reshaped `(nzgr, nrgr)` = `(Z, R)` (`eqdsk_base.py:76`). Verified on the fixture: `PsiVs[0,0] = -0.096520789` matches the raw `psirz(1,1)`, `PsiVs[-1,-1] = -0.52133435` matches `psirz(nw,nh)`, and `PsiVs.T` has shape `(65, 129)`. The fixture is non-square, so a transpose error is detectable — but only if someone tests it.

## Behaviour (BDD)

```gherkin
Scenario: Python-written g-file is readable by the Fortran reader
  Given test/resources/input_efit_file.dat is read by libneo.eqdsk_base.read_eqdsk
  And the dict is written back with write_eqdsk to <tmp>/py_written.geqdsk
  When geqdsk_dump.x <tmp>/py_written.geqdsk <tmp>/py_written.dump is executed
  Then the run exits with status 0
  And the dump reports nbbbs = 209 and limitr = 773

Scenario: Fortran and Python agree on scalars from the same file
  Given test/resources/input_efit_file.dat
  When geqdsk_dump.x writes the geqdsk_t scalars and read_eqdsk parses the same file
  Then rdim/1e2 equals rboxlength = 1.92000008
  And rleft/1e2 equals rboxleft = 0.75 and rcentr/1e2 equals R0
  And rmaxis/1e2 equals Rpsi0 = 1.7158165
  And simag/1e8 equals PsiaxisVs = -0.108122148
  And sibry/1e8 equals PsiedgeVs = 0.13648048
  And bcentr/1e4 equals Btor_at_R0 = -2.50046372
  And each comparison holds to rtol 1e-9

Scenario: Fortran and Python agree on profiles and the 2D flux map
  Given test/resources/input_efit_file.dat with nw = 65 and nh = 129
  When both readers parse it
  Then fpol/(1e4*1e2) equals fprof, with fprof[0] = -4.12663221
  And pres/1e1 equals ptotprof, with ptotprof[0] = 136924.406
  And qpsi equals qprof, with qprof[0] = 1.03995204
  And psirz/1e8 equals PsiVs.T elementwise, with shape (65, 129) versus (129, 65)
  And each comparison holds to rtol 1e-9, atol 0

Scenario: Fortran-written g-file is readable by both Python readers
  Given standardise_geqdsk.x has written <tmp>/fortran_written.geqdsk
  When libneo.eqdsk_base.read_eqdsk and libneo.eqdsk.eqdsk_file both parse it
  Then both report nrgr = 65 and nzgr = 129
  And their flux arrays agree to rtol 1e-12

Scenario: field_divB0 reader agrees with geqdsk_tools on the same file
  Given input_files::gfile is set to test/resources/input_efit_file.dat
  When read_dimeq1 then read_eqfile2, and geqdsk_read, parse it
  Then psiRZ (SI) equals psirz/1e8 to rtol 1e-12
  And rad equals R_eqd/1e2 and zet equals Z_eqd/1e2 to rtol 1e-12
```

## Implementation plan

1. **Fix the writer bug first (separate, small PR).** `python/libneo/eqdsk_base.py:160`: replace
   `f.write(f"{eqdata['npbound']} {eqdata['nplimiter']}\n")` with
   `f.write(f"{eqdata['npbound']:5d}{eqdata['nplimiter']:5d}\n")`, matching `format_2022 = '(2i5)'` in `src/magfie/geqdsk_tools.f90:34`. Add a regression test in `python/tests/test_eqdsk_base.py` in the style of `test_write_eqdsk_header_matches_3i4_columns` (`python/tests/test_eqdsk_base.py:43-57`): assert `int(line[0:5]) == npbound` and `int(line[5:10]) == nplimiter`. Do this before step 2 so the new cross-check goes green rather than landing red.

2. **Add `test/source/geqdsk_dump.f90`** — a dumper program in the style of `test/source/geoflux_coord_dump.f90` (two positional arguments read via `get_command_argument`, see `geoflux_coord_dump.f90:28-29`). Takes input g-file and output dump file. Calls `geqdsk_read` from `geqdsk_tools`, then writes a plain-text, easily parsed dump: a `key = value` block for the scalars (`nw`, `nh`, `nbbbs`, `limitr`, `rdim`, `zdim`, `rcentr`, `rleft`, `zmid`, `rmaxis`, `zmaxis`, `simag`, `sibry`, `bcentr`, `current`) followed by named array sections (`fpol`, `pres`, `ffprim`, `pprime`, `qpsi`, `rbbbs`, `zbbbs`, `rlim`, `zlim`, `R_eqd`, `Z_eqd`) and `psirz` written with an explicit `# psirz nw nh` header and `kw` fastest. Use `es24.16` so the comparison is limited by the file's own precision, not by the dump. Values stay in the CGS units that `geqdsk_read` produces — do not convert in the dumper; the conversion belongs in the test, where it is visible.

3. **Add a `--via-field-divb0` mode** to the same program for Scenario 5. `read_eqfile1`/`read_eqfile2` are module procedures of `module field_sub` (`src/magfie/field_divB0.f90:1`, no `private` declared), so `use field_sub, only : read_dimeq1, read_eqfile2` works directly. Note the calling contract: `read_eqfile2` declares `nwEQD, nhEQD` as `intent(inout)` and sizes its output arrays with them (`field_divB0.f90:452-456`), so you **must** call `read_dimeq1(nwEQD, nhEQD)` (`field_divB0.f90:359`) first and allocate before calling it. Both routines take the filename from `input_files::gfile`, so set `gfile = trim(path)` directly the way `src/magfie/geoflux_field.f90:22` does — no `field_divB0.inp` is needed. Dump `psiRZ`, `fpol`, `rad`, `zet`, `psiAxis`, `psiSep`, `bt0`, `rzero` in SI.

4. **Wire it into `test/CMakeLists.txt`.** Next to the existing `add_executable(geoflux_coord_dump.x source/geoflux_coord_dump.f90)` at `test/CMakeLists.txt:144`, add
   `add_executable(geqdsk_dump.x source/geqdsk_dump.f90)` and link it against the same targets `test_geqdsk_tools.x` uses (`${MAIN_LIB}`, `${MAGFIE_LIB}`; `test/CMakeLists.txt:123-127`).

5. **Add `test/scripts/geqdsk_fortran_python_compare.py`** — argparse over `--exe`, `--geqdsk`, `--work-dir`, following the `--exe $<TARGET_FILE:geoflux_coord_dump.x>` pattern of `test_geoflux_plot` (`test/CMakeLists.txt:317-325`). It (a) runs `geqdsk_dump.x` on the fixture, (b) parses the dump, (c) runs `libneo.eqdsk_base.read_eqdsk` on the same fixture, (d) applies the CGS↔SI factors from `src/util/math_constants.f90:45-52` as module-level named constants in the script, (e) `numpy.testing.assert_allclose(..., rtol=1e-9)` field by field including `psirz` vs `PsiVs.T`, (f) writes the Python dict back with `write_eqdsk` and re-runs `geqdsk_dump.x` on the written file, asserting exit status 0 and matching `nbbbs`/`limitr`. Exit non-zero with a per-field diff report on failure.

6. **Register the ctest** in `test/CMakeLists.txt` next to `add_test(NAME test_geqdsk_tools COMMAND test_geqdsk_tools.x)` (`test/CMakeLists.txt:265`):
   `add_test(NAME test_geqdsk_fortran_python COMMAND ${Python_EXECUTABLE} ${CMAKE_SOURCE_DIR}/test/scripts/geqdsk_fortran_python_compare.py --exe $<TARGET_FILE:geqdsk_dump.x> --geqdsk ${CMAKE_SOURCE_DIR}/test/resources/input_efit_file.dat --work-dir ${CMAKE_CURRENT_BINARY_DIR})`. Put it inside the same `if(LIBNEO_TESTING_ENABLED)` block that guards `test_geqdsk_plot` (`test/CMakeLists.txt:300`, `:308-315`).

7. **Add the pure-Python half** in `python/tests/test_eqdsk_cross_readers.py`: parse `test/resources/input_efit_file.dat` with both `libneo.eqdsk_base.read_eqdsk` and `libneo.eqdsk.eqdsk_file`, assert the two agree on `nrgr`, `nzgr`, `R`, `Z`, the flux map, `fprof` and `qprof` to `rtol=1e-12`. Note the two classes use different attribute names (`eqdsk_base` returns a dict with `zboxmid`, `eqdsk_file` stores `self.zbox_mid`), so map the names explicitly rather than iterating keys. This costs nothing, runs in the existing `python -m pytest python/tests` CI step (`.github/workflows/main.yml:101`), and catches drift between the two Python parsers without needing a build.

8. **Fix `test/source/test_geqdsk_tools.f90:82`** while you are in the file: `geqdsk_in%limitr == geqdsk_in%limitr` should compare against `geqdsk_out%limitr`.

9. **Document the contract** in `docs/eqdsk.rst`: one short section stating that `geqdsk_t` is CGS, the Python dict is SI, `psirz` is `(R, Z)` while `PsiVs` is `(Z, R)`, and that the record formats are `(a48,3i4)`, `(5es16.9)`, `(2i5)`.

No sibling repo changes are required. MEPHIT and `geoflux_coordinates` consume `geqdsk_t` and are unaffected by adding a test.

## Acceptance criteria

- [ ] `cmake --build --preset default && ctest --preset default -R test_geqdsk --output-on-failure` passes, including the new `test_geqdsk_fortran_python`.
- [ ] `python -m pytest python/tests test/python -q` passes, including `test_eqdsk_cross_readers.py` and the new `(2i5)` writer-column test.
- [ ] Every scalar in Scenario 2 and every array in Scenario 3 matches to `rtol = 1e-9` on `test/resources/input_efit_file.dat`.
- [ ] Round trip `read_eqdsk` → `write_eqdsk` → `geqdsk_dump.x` exits 0 and reports `nbbbs = 209`, `limitr = 773`.
- [ ] Reverting the one-line fix from step 1 makes `test_geqdsk_fortran_python` fail (the test demonstrably has teeth).
- [ ] `test_geqdsk_tools`, `test_geoflux`, `test_geoflux_coordinate_system` and the ASCOT5 comparison (`test/scripts/test_ascot5_compare.py`) are unchanged.

## References

- L. L. Lao, H. St. John, R. D. Stambaugh, A. G. Kellman, W. Pfeiffer, *Reconstruction of current profile parameters and plasma shapes in tokamaks*, Nucl. Fusion **25** (1985) 1611 — the EFIT paper behind the G-EQDSK record layout the fixed formats above encode.
- O. Sauter, S. Yu. Medvedev, *Tokamak coordinate conventions: COCOS*, Comput. Phys. Commun. **184** (2013) 293 — the convention taxonomy `geqdsk_classify`/`geqdsk_standardise` (`src/magfie/geqdsk_tools.f90:13-14`) implement; relevant to the sign-agreement part of any cross-check.
- O. Meneghini et al., *Integrated modeling applications for tokamak experiments with OMFIT*, Nucl. Fusion **55** (2015) 083008 — OMFIT centralises G-EQDSK handling in a single `OMFITgeqdsk` reader/writer class rather than maintaining several independent parsers. Worth considering as the long-term direction here: expose the Fortran reader to Python through the existing `src/f2py_interfaces/` layer and delete the duplicates, instead of cross-checking N parsers pairwise.

Everything else in this comment is an implementation detail internal to libneo, with no external literature reference.

## Scope and risk

Two PRs: (1) the one-line `(2i5)` writer fix plus its unit test, (2) the dumper, the comparison script, and the ctest/pytest wiring. Low risk — step 1 changes only whitespace in written g-files (Python's own `read_eqdsk` uses `split()` at `eqdsk_base.py:85` and is insensitive to it), and everything else is additive test code. The main way this bites is if the new test surfaces further pre-existing disagreements between the readers; treat those as separate findings rather than expanding this PR.

Possibly related, worth checking before starting so the work is not duplicated: #302, #363, #28 (other EQDSK convention/validation issues), #127 (Fortran-backed Python bindings, the structural fix that would make most of this redundant), and #396 / `cf8fc44`, which fixed the analogous `(3i4)` header-column mismatch and is the direct precedent for step 1.
