### ISSUE TITLE
Add derivatives to splines

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#42]
Right now, only second derivatives for 1D splines exist.

**Comment by krystophny** [comment]
## Hybrid FD/AD split note

This issue fits a mixed differentiability strategy.

A single solver can expose AD or analytical products for branch-stable subkernels while finite differences or zeroth-order samples remain around hard outputs and driver logic.

Pattern:

- use AD or analytical products for cheap local pieces: profiles, splines, interpolation, field kernels, residual kernels, or smooth proxy maps;
- keep finite differences or zeroth-order sampling for full executable calls, root and topology changes, orbit-class events, convergence logic, restart logic, or long-time loss labels;
- use cheap derivative products to choose reduced finite-difference directions or anisotropic random directions for the expensive target;
- report event changes as diagnostics, not as failed gradients.

Cost model: cheap proxy Jacobians shape where expensive evaluations are spent. This gives useful optimization signal before full end-to-end differentiability exists.

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

The checklist in the body is stale. Against current `master` two of the four unchecked boxes are already done, and exactly one gap remains. Re-scoping below.

**Checklist reconciliation (verified at `fe3f76e`):**

| Box | Status in code | Evidence |
|---|---|---|
| 1D first | done | `evaluate_splines_1d_der` — `src/interpolate/interpolate.f90:155`; batch `evaluate_batch_splines_1d_der` — `src/interpolate/batch_interpolate_1d.f90:711` |
| 1D second | done | `evaluate_splines_1d_der2` — `interpolate.f90:168`; batch `_1d_der2`/`_1d_der3` — `batch_interpolate_1d.f90:726,782` |
| **2D first** | **done, box wrong** | `evaluate_splines_2d_der` — `interpolate.f90:340`, `evaluate_splines_2d_many_der` — `interpolate.f90:391`; batch `evaluate_batch_splines_2d_many_der`/`_2d_der` — `batch_interpolate_2d.f90:543,623` |
| **2D second** | **MISSING — the real remaining work** | no `evaluate_splines_2d_der2`, `evaluate_splines_2d_many_der2`, `evaluate_batch_splines_2d_der2`, `evaluate_batch_splines_2d_many_der2` anywhere; public lists at `interpolate.f90:74,59` and `batch_interpolate_2d.f90:28-32` stop at `_der` |
| **3D first** | **done, box wrong** | `evaluate_splines_3d_der` — `interpolate.f90:545`; batch `evaluate_batch_splines_3d_der` — re-exported at `interpolate.f90:61` |
| 3D second | done | `evaluate_splines_3d_der2` — `interpolate.f90:558`, `_3d_many_der2` — `interpolate.f90:706`; batch `_3d_der2`, `_3d_der3` — `batch_interpolate_3d.f90:1229,1239`, cores at `1576`, `1601` |

So: **please tick 2D-first and 3D-first, and keep this issue open only for 2D second derivatives.** Spec follows.

## Purpose

The 2D tensor-product spline is the natural representation for axisymmetric geometry — `R(s, θ)`, `Z(s, θ)`, `|B|(s, θ)`, and the poloidal flux `ψ(R, Z)`. Anything that needs a metric tensor derivative, a Christoffel symbol, a curvature, or a Newton step on a 2D map needs the second derivatives of those maps, not just the first. The 3D path already supplies this and has a live consumer: `src/boozer_converter.F90` calls `evaluate_batch_splines_3d_der2` at lines 260, 352 and 514, and reads the packing back at line 518 (`! convention from der2 is (rr, rt, rp, tt, tp, pp)`). The 2D path has no equivalent, so an axisymmetric consumer must either pad to a fake third dimension or fall back to finite differences — losing the `1e-11`-level agreement the analytic Horner path delivers against the test oracle, and re-introducing exactly the FD noise the issue comment's hybrid FD/AD note wants to push out of the "cheap local pieces" tier.

Note for scope: the *scalar* `evaluate_splines_3d_der2` currently has no caller inside this repository — it is public API only (`interpolate.f90:76`). The batch variant is the one with in-tree consumers. Both flavours are specified below so the 2D layer reaches parity with 3D, but the batch routine is the one with a demonstrated use case.

## Current state

The scalar 2D kernel stops after the first derivative. `src/interpolate/interpolate.f90:391-447`, `evaluate_splines_2d_many_der`, carries exactly two Horner accumulators — the value chain and one `d/dx1` chain — and derives `d/dx2` by a power-weighted sweep at the end:

```fortran
        real(dp) :: coeff_2(0:spl%order(2))
        real(dp) :: coeff_2_dx1(0:spl%order(2))
...
            coeff_2_dx1(:) = spl%coeff(spl%order(1), 0:spl%order(2), &
                                       interval_index(1) + 1, interval_index(2) + 1) &
                             *spl%order(1)
            do k1 = spl%order(1) - 1, 1, -1
                coeff_2_dx1(:) = spl%coeff(k1, :, interval_index(1) + 1, &
                                           interval_index(2) + 1)*k1 &
                                 + x_local(1)*coeff_2_dx1
            end do
...
            dy(2, ie) = coeff_2(spl%order(2))*spl%order(2)
            do k2 = spl%order(2) - 1, 1, -1
                dy(2, ie) = coeff_2(k2)*k2 + x_local(2)*dy(2, ie)
            end do
```

The 3D analogue `evaluate_splines_3d_many_der2` at `src/interpolate/interpolate.f90:706-839` is the exact template to copy. It declares `coeff_23`, `coeff_23_dx1`, `coeff_23_dx1x1`, then `coeff_3`, `coeff_3_dx1`, `coeff_3_dx2`, `coeff_3_dx1x1`, `coeff_3_dx1x2`, `coeff_3_dx2x2` (`interpolate.f90:712-720`), and packs `d2y` in upper-triangular column order `(11, 12, 13, 22, 23, 33)` — visible in the assignments at `interpolate.f90:811-836`, where `d2y(1)=11`, `d2y(2)=12`, `d2y(3)=13`, `d2y(4)=22`, `d2y(5)=23`, `d2y(6)=33`. For 2D the same convention collapses to `d2y(3) = (11, 12, 22)`.

The batch 2D kernel `evaluate_batch_splines_2d_many_der` (`src/interpolate/batch_interpolate_2d.f90:543-621`) has the same shape with a leading quantity index, and uses a heap `allocate` for the accumulators (`batch_interpolate_2d.f90:551,559`). The batch 3D kernels instead use fixed-size automatic arrays sized by `MAX_QUANTITIES = 8` / `MAX_ORDER = 8` (`src/interpolate/batch_interpolate_3d.f90:17-18`, used at `1401-1409`) precisely so they can carry `!$acc routine seq`. `batch_interpolate_2d.f90` currently has **no** `!$acc routine seq` anywhere (11 occurrences in `batch_interpolate_3d.f90`, none in the 2D file) — worth matching the 3D convention for the new routine so the GPU path is not closed off.

The test oracle module `test/source/spline_eval_reference.f90` publishes `evaluate_splines_1d_der2_ref` and `evaluate_splines_3d_der2_ref` but only `evaluate_splines_2d_der_ref` (public list at `spline_eval_reference.f90:8-12`) — the 2D second-derivative reference is missing there too.

## Reproduction / evidence

This is a feature gap, not a bug, so here is the verification recipe. The build is CMake+Ninja driven through the `Makefile` (`Makefile:24,27` → `cmake --preset default`, `cmake --build --preset default`):

```bash
cd /path/to/libneo
make
cd build && ctest --output-on-failure -R 'interpolate|eval_oracle'
```

Today that passes and covers 2D value + first derivative only — `test/source/test_batch_eval_oracle.f90:128-132` asserts `2d der dy1`/`2d der dy2` against the oracle at `REL_TOL = 1.0d-11` (`test_batch_eval_oracle.f90:25`), and `test_interpolate.f90`'s `test_spline_2d` (lines 163-205) never touches derivatives at all. Confirm the gap directly:

```bash
rg -n 'splines_2d_der2' src/ test/     # → no matches at fe3f76e
```

**Test-name warning.** Two distinct oracle tests exist and are easy to confuse:

- `test_batch_eval_oracle` — built from `test/source/test_batch_eval_oracle.f90` (`test/CMakeLists.txt:202`), registered at `test/CMakeLists.txt:280`. **This is the one holding `test_2d_evaluation` and the 25×27 separable grid, and the one this spec edits.**
- `test_batch_interpolate_oracle` — a different executable from `test/source/test_batch_interpolate_oracle.f90` (`test/CMakeLists.txt:199`), registered at `:279`, containing `test_oracle_1d/2d/3d`. Not edited here.

`ctest -R test_batch_interpolate_oracle` does **not** match `test_batch_eval_oracle`. Use `ctest -R test_batch_eval_oracle`.

**Verification target.** The 2D oracle test builds the separable analytic function at `test/source/test_batch_eval_oracle.f90:105`:

```fortran
y_grid(i1, i2) = exp(0.15d0*cos(x1(i1))) * (1.5d0 + 0.5d0*sin(x2(i2)))
```

with `f(x1,x2) = g(x1)*h(x2)`, `g = exp(0.15 cos x1)`, `h = 1.5 + 0.5 sin x2`. Because it is separable the mixed second derivative is exactly `g'(x1) h'(x2)`, which makes the check independent of the spline machinery:

- `d2y(1) = g''(x1) h(x2)`, `g'' = 0.15*exp(0.15 cos x1)*(0.15 sin²x1 - cos x1)`
- `d2y(2) = g'(x1) h'(x2)`, `g' = -0.15 sin(x1) exp(0.15 cos x1)`, `h' = 0.5 cos x2`
- `d2y(3) = g(x1) h''(x2)`, `h'' = -0.5 sin x2`

The grid is 25×27 with `x_min = [1.0, -0.5]`, `x_max = [4.0, 2.5]` (`test_batch_eval_oracle.f90:88-90`), and `test_2d_evaluation` sweeps three cases (`test_batch_eval_oracle.f90:111-113`):

| case | `order` | `periodic` |
|---|---|---|
| 1 | `[3, 3]` | `[.false., .false.]` |
| 2 | `[5, 5]` | `[.true., .true.]` |
| 3 | `[5, 3]` | `[.true., .false.]` |

**Important:** `f` is *not* periodic on `[1,4] × [-0.5,2.5]`, so cases 2 and 3 impose a wrap the data does not satisfy. The facade-vs-oracle comparison at `REL_TOL = 1.0d-11` is still valid for all three cases (both sides consume the same coefficients), but any comparison against the *analytic* `g''h`, `g'h'`, `gh''` is only meaningful on a fully non-periodic spline. Build a dedicated `order = [5,5]`, `periodic = [.false.,.false.]` spline for that check rather than reusing case 2. Convergence: for spline order `p` the second-derivative error is `O(h^(p-1))`, so halving `h_step` should shrink the `d2y` error by roughly `2^(p-1)` at interior points.

## Behaviour (BDD)

```gherkin
Scenario: Scalar 2D second derivatives match the reference oracle
  Given a SplineData2D built by construct_splines_2d over x_min=[1.0,-0.5],
        x_max=[4.0,2.5] on a 25x27 grid of exp(0.15*cos(x1))*(1.5+0.5*sin(x2))
        for each of the three existing cases of test_2d_evaluation:
        order=[3,3] periodic=[.false.,.false.], order=[5,5] periodic=[.true.,.true.],
        order=[5,3] periodic=[.true.,.false.]
  When test_batch_eval_oracle.x calls evaluate_splines_2d_der2(spl, x_eval, y, dy, d2y)
       and evaluate_splines_2d_der2_ref(spl, x_eval, y_ref, dy_ref, d2y_ref)
       at the 50 evaluation points of test_2d_evaluation
  Then y, dy(1:2) and d2y(1:3) agree with the reference within REL_TOL = 1.0d-11

Scenario: Packing convention is (11, 12, 22)
  Given a SplineData2D of the separable function g(x1)*h(x2) built with
        order=[5,5] and periodic=[.false.,.false.] on the same 25x27 grid
  When evaluate_splines_2d_der2 is called at the interior point x_eval = [2.5, 1.0]
  Then d2y(1) equals g''(x1)*h(x2), d2y(2) equals g'(x1)*h'(x2) and
       d2y(3) equals g(x1)*h''(x2), each to relative tolerance 1.0d-6

Scenario: Batch 2D second derivatives agree with per-quantity scalar splines
  Given a BatchSplineData2D with num_quantities = 3 built from the same grid
        and three independent analytic surfaces, plus three matching SplineData2D
  When test_batch_interpolate.x calls evaluate_batch_splines_2d_der2 and, for each
       quantity, evaluate_splines_2d_der2
  Then y_batch(iq), dy_batch(:,iq) and d2y_batch(:,iq) match the scalar results
       to relative tolerance 1.0d-11 for every iq

Scenario: Periodic wrap is respected in the second derivative
  Given a SplineData2D with order=[5,5] and periodic=[.true.,.true.]
  When evaluate_splines_2d_der2 is called at x and at x + [period(1), period(2)]
  Then both calls return d2y agreeing to relative tolerance 1.0d-12
```

## Implementation plan

Follow the repo's test-first rule in `CODING_STANDARD.md:42` ("Write test *before* code").

1. **`test/source/spline_eval_reference.f90`** — add `evaluate_splines_2d_der2_ref(spl, x, y, dy, d2y)` next to the existing `evaluate_splines_2d_der_ref` (declared in the public list at line 10, defined at line 135, ends at line 186). Write it in the deliberately naive style of the other `_ref` routines: no shared accumulators, straight per-derivative Horner sweeps. Add the name to the `public ::` statement at line 10.
2. **`test/source/test_batch_eval_oracle.f90`** — in `test_2d_evaluation` (starts line 87) declare `d2y_facade(3)`, `d2y_ref(3)` alongside the existing `dy_facade(2)`/`dy_ref(2)`; add `evaluate_splines_2d_der2` and `evaluate_splines_2d_der2_ref` to the module `use` lists at the top of the file; after the existing `2d der dy2` assertion (line 132) add `assert_close` calls for `2d der2 d2y11`/`d2y12`/`d2y22` at `REL_TOL`. Run `ctest -R test_batch_eval_oracle` and confirm it fails to compile — that is the red state.
3. **`src/interpolate/interpolate.f90`** — implement `evaluate_splines_2d_many_der2(spl, x, y, dy, d2y)` immediately after `evaluate_splines_2d_many_der` (ends at line 447). Add accumulator `coeff_2_dx1x1(0:spl%order(2))` seeded as `spl%coeff(N1, :, ...)*N1*(N1-1)` with the sweep `do k1 = N1-1, 2, -1`, mirroring `coeff_23_dx1x1` in the 3D routine (declared `interpolate.f90:713`). Then emit `d2y(1,ie)` from `coeff_2_dx1x1` by a plain `do k2 = N2-1, 0, -1` sweep; `d2y(2,ie)` from `coeff_2_dx1` with the `k2`-weighted sweep `do k2 = N2-1, 1, -1`; `d2y(3,ie)` from `coeff_2` with the `k2*(k2-1)` sweep `do k2 = N2-1, 2, -1` — the three sweep shapes are the 2D projection of the `d2y(1)`/`d2y(3)`/`d2y(6)` sweeps at `interpolate.f90:816-836`. Document the packing `(11,12,22)` in a one-line comment on the `d2y` declaration.
4. **`src/interpolate/interpolate.f90`** — add the single-point wrapper `evaluate_splines_2d_der2(spl, x, y, dy, d2y)` with `real(dp), intent(out) :: y, dy(2), d2y(3)`, delegating through `x_arr(2,1)` exactly like `evaluate_splines_2d_der` at line 340 and `evaluate_splines_3d_der2` at line 558. Extend the `public ::` line at 74 to `evaluate_splines_2d, evaluate_splines_2d_der, evaluate_splines_2d_der2` and line 75 to include `evaluate_splines_2d_many_der2`.
5. **`src/interpolate/batch_interpolate_2d.f90`** — implement `evaluate_batch_splines_2d_many_der2` after `evaluate_batch_splines_2d_many_der` (ends at line 621) and the single-point `evaluate_batch_splines_2d_der2` after `evaluate_batch_splines_2d_der` (ends at line 637). Prefer fixed-size automatic arrays `real(dp) :: coeff_2(MAX_QUANTITIES, 0:MAX_ORDER)` etc. over the heap `allocate` used at line 559, mirroring `src/interpolate/batch_interpolate_3d.f90:17-18,1401-1409`, and put `!$acc routine seq` as the first line of *both* the `_many_der2` kernel and the single-point wrapper — that is what 3D does (`batch_interpolate_3d.f90:1024` on `_3d_many_der`, `:1059` on `_3d_der`, `:1230` on `_3d_der2`). Add a runtime guard `if (spl%num_quantities > MAX_QUANTITIES) error stop` matching the 3D convention. Add both new names to the `public ::` block at lines 28-32.
   *Optional, not required for this PR:* `MAX_QUANTITIES`/`MAX_ORDER` are currently private parameters of `batch_interpolate_3d` (`:17-18`). Sharing them from `src/interpolate/batch_interpolate_types.f90` avoids duplicated literals, but that module today exports only derived types and is consumed by the OpenACC-resident path — if you take this option, build the `nvfortran` target (`Makefile:56-65`) before merging. Duplicating the two parameters privately in `batch_interpolate_2d.f90` is an acceptable lower-risk alternative.
6. **`src/interpolate/batch_interpolate.f90`** — re-export the two new batch names: add to the `use batch_interpolate_2d, only:` list at lines 27-30 and to the `public ::` statements at lines 68-69.
7. **`src/interpolate/interpolate.f90`** — re-export them from the facade too: the `use batch_interpolate, only:` block at lines 26-29 and `public ::` at line 59.
8. **`test/source/test_batch_interpolate.f90`** — add `test_batch_spline_2d_second_derivatives()`, modelled on `test_batch_spline_3d_second_derivatives()` (defined at line 1062, called at line 30) and on `test_batch_spline_2d_derivatives()` (defined at line 704): build one `BatchSplineData2D` with `num_quantities = 3` plus three scalar `SplineData2D`, compare all of `y`, `dy`, `d2y` at `1e-11`. Register the call after `test_batch_spline_2d_derivatives()` at line 23.
9. **`test/source/test_interpolate.f90`** — extend `test_periodic_wrap_2d()` (starts line 286) with the periodic-wrap `d2y` scenario above at `1e-12`.
10. **Build wiring** — no new source files, so `src/interpolate/CMakeLists.txt` and `test/CMakeLists.txt` need no new `add_executable`/`add_test` entries. The existing registrations already cover the new code: `test_interpolate` (`test/CMakeLists.txt:274`), `test_batch_interpolate` (`:275`) and `test_batch_eval_oracle` (`:280`).
11. **Downstream** — `.github/workflows/downstream-gate.yml` gates every libneo PR against the downstreams listed in `ci/downstreams`: SIMPLE, NEO-2, MEPHIT, KAMEL and rabe are blocking; NEO-RT is report-only. This change is purely additive (new public names, no signature changes), so the gate should stay green and no companion PR is required. rabe is the plausible first consumer of a 2D second-derivative entry point, but its source is not part of this checkout, so confirm that in the rabe repository before promising anything there; it belongs in a separate follow-up either way.

## Acceptance criteria

- [ ] `rg -n 'evaluate_splines_2d_der2|evaluate_splines_2d_many_der2|evaluate_batch_splines_2d_der2|evaluate_batch_splines_2d_many_der2' src/` returns all four symbols, each in its module `public ::` list and re-exported by the `interpolate` facade.
- [ ] `make && cd build && ctest --output-on-failure` passes with zero failures, in both the Release and Debug configurations built by `.github/workflows/main.yml:66-71`. The Debug configuration is the one carrying `-ffpe-trap=invalid,zero,overflow` and `-fcheck=all,no-recursion` (`CMakeLists.txt:155,158`).
- [ ] `ctest -R test_batch_eval_oracle` asserts 2D `d2y(1:3)` against `evaluate_splines_2d_der2_ref` within `REL_TOL = 1.0d-11` for all three order/periodicity cases of `test_2d_evaluation`. (Note the test name — `test_batch_interpolate_oracle` is a different executable.)
- [ ] `ctest -R test_batch_interpolate` asserts batch-vs-scalar 2D `d2y` agreement within `1e-11` for `num_quantities = 3`.
- [ ] Separable-function check on a dedicated `order = [5,5]`, `periodic = [.false.,.false.]` spline over the 25×27 grid: `d2y(1)`, `d2y(2)`, `d2y(3)` reproduce `g''h`, `g'h'`, `gh''` to relative error < `1e-6` at interior points. Do not run this check against the periodic cases — the test function is not periodic on this domain.
- [ ] `d2y` packing is `(11, 12, 22)`, documented in-source, consistent with the `(11,12,13,22,23,33)` convention of `batch_interpolate_3d.f90:1243` and `boozer_converter.F90:518`.
- [ ] No regression in `test_boozer_converter_vs_simple` (`test/CMakeLists.txt:558-562`), which sits downstream of the interpolate layer.

## References

No specific literature reference; this is an implementation detail internal to the code. The evaluation scheme is nested Horner on the local polynomial coefficients of a tensor-product piecewise polynomial, and the only authority needed is the existing 3D implementation in this repository:

- 3D scalar template to mirror: `src/interpolate/interpolate.f90:706-839` (`evaluate_splines_3d_many_der2`).
- 3D batch template, including the `!$acc routine seq` and fixed-size-work-array conventions: `src/interpolate/batch_interpolate_3d.f90:1229-1238` and the core at `:1576`.
- Packing convention, stated in-source: `batch_interpolate_3d.f90:1243` and `src/boozer_converter.F90:518`.
- Reference (naive) implementations used as the test oracle: `test/source/spline_eval_reference.f90:316-440` (`evaluate_splines_3d_der2_ref`).
- Underlying 1D coefficient construction: `spl_per`/`spl_reg` from `src/spl_three_to_five.f90`, imported at `src/interpolate/interpolate.f90:3`.

## Scope and risk

Single PR, roughly 250-350 lines of new Fortran plus tests, entirely additive — no existing signature changes, so the downstream gate is low-risk. The only judgement call is the optional parameter-sharing in step 5; taking the lower-risk path (private duplicates in `batch_interpolate_2d.f90`) keeps the change confined to two source files and two test files.

Duplicate scan: the triage pass flagged itpplasma/libneo#204, #229 and #230 as touching the spline layer without covering 2D second derivatives. Those issue contents were not re-read during this review — confirm them manually before closing this as a duplicate of any of them.
