### ISSUE TITLE
Improve OpenMP in Biot-Savart code

### ISSUE THREAD

**Issue by pazathoth** [itpplasma/libneo#44]
Multi-threaded FFTW starts to be useful when arrays have a few thousand entries, which is currently not the case in the Biot-Savart computations. Thus it would be more useful to use single-threaded FFTW instead and parallelize the surrounding loop, i.e. instead of
```fortran
p_fft_output = fftw_alloc_complex(int(nfft, c_size_t))
call c_f_pointer(p_fft_output, fft_output, [nfft])
p_AR = fftw_alloc_real(int(nphi, c_size_t))
call c_f_pointer(p_AR, AR, [nphi])
! ... further input arrays
do kZ = 1, nZ
  do kR = 1, nR
    !$omp parallel do shared(AR) ...
    do kphi = 1, nphi
      ! ... fill input arrays
    end do
    !$omp end parallel do
    call fftw_execute_dft_r2c(plan_nphi, AR, fft_output)
    AnR(0:nmax, kR, kZ, kc) = fft_output(1:nmax+1) / dble(nphi)
    ! ... further transforms
  end do
end do
```
do
```fortran
!$omp parallel private(AR, fft_output), shared(AnR)
p_fft_output = fftw_alloc_complex(int(nfft, c_size_t))
call c_f_pointer(p_fft_output, fft_output, [nfft])
p_AR = fftw_alloc_real(int(nphi, c_size_t))
call c_f_pointer(p_AR, AR, [nphi])
! ... further input arrays
!$omp do collapse(3) ...
do kZ = 1, nZ
  do kR = 1, nR
    do kphi = 1, nphi
      ! ... fill input arrays
    end do
    call fftw_execute_dft_r2c(plan_nphi, AR, fft_output)
    AnR(0:nmax, kR, kZ, kc) = fft_output(1:nmax+1) / dble(nphi)
    ! ... further transforms
  end do
end do
!$omp end do
!$omp end parallel
```
Finally, the question is whether to link `fftw3` **or** `fftw3_omp`.

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still valid, with one part of it already resolved. The FFTW question at the end of the issue is moot — `coil_tools` no longer uses FFTW at all (commit `8189204`, "Route coil_tools FFT through fortnum, drop FFTW (#317)"); `fftw3` vs `fftw3_omp` is not a choice the repo has to make any more. But the actual substance of the request — the OpenMP region is opened and closed *inside* the (kR, kZ) loops instead of around them — is untouched in `src/magfie/coil_tools.f90` at HEAD. Spec below.

## Purpose

`vacfield.x` is the production path that turns filament coil geometry (AUG B-coils, GPEC/Nemov coil sets) into the toroidal Fourier modes `Bn`/`AnR, Anphi, AnZ, dAnphi_dR, dAnphi_dZ` that MEPHIT consumes as its vacuum perturbation field (`src/magfie/vacfield.f90:114`, `:133`; consumed downstream in `MEPHIT/src/mephit_pert.f90`). For a realistic AUG grid — `tools/vacfield_AUG.in` specifies `nR = 150`, `nZ = 300`, `nphi = 512`, `nmax = 64` — the run is a pure Biot-Savart sum over `nseg` segments at `nR*nZ*nphi ≈ 2.3e7` field points per coil, i.e. embarrassingly parallel and completely dominated by that triple loop. The current code parallelises only the innermost `nphi` loop and pays a fork/join per `(kR, kZ)` pair, so it does `2 * nR * nZ = 90 000` barrier round-trips per coil for chunks of 512 iterations each. Moving the parallel region outside the `kR`/`kZ` loops removes that overhead and gives the scheduler four orders of magnitude more work per region.

## Current state

Two routines in `src/magfie/coil_tools.f90` have the bad structure. `biot_savart_fourier` (line 400) and `vector_potential_biot_savart_fourier` (line 465). Both now use `fortnum_fft` rather than FFTW:

```fortran
      use fortnum_fft, only: fft_r2c, fortnum_fft_plan_t, fft_plan_init
```
(`src/magfie/coil_tools.f90:402` and `:466`)

The offending nesting, `biot_savart_fourier` lines 426-461:

```fortran
      call fft_plan_init(plan_nphi, nphi)
      do kc = 1, ncoil
         do kZ = 1, nZ
            do kR = 1, nR
!$omp parallel do schedule(static) default(none) &
!$omp private(kphi, ks, XYZ_r, XYZ_i, XYZ_f, dist_i, dist_f, BXYZ) &
!$omp shared(nphi, kc, coils, R, kR, Z, kZ, cosphi, sinphi, BR, Bphi, BZ)
               do kphi = 1, nphi
                  ...
               end do
!$omp end parallel do
               call fft_r2c(BR, BnR, plan_nphi)
               call fft_r2c(Bphi, Bnphi, plan_nphi)
               call fft_r2c(BZ, BnZ, plan_nphi)
               Bn(0:nmax, 1, kR, kZ, kc) = BnR(1:nmax + 1)/dble(nphi)
```

`vector_potential_biot_savart_fourier` is identical in shape (parallel region at `:516-550`, five `fft_r2c` calls at `:551-560`), with the extra wrinkle that `stretch_coords` is called per `(kR, kZ)` at `:511` when `use_convex_wall` is true.

The scratch arrays that must become thread-private are subroutine-scope automatics: `BR, Bphi, BZ` (`:412`) and `BnR, Bnphi, BnZ` (`:413`); `AR, Aphi, AZ, dAphi_dR, dAphi_dZ` (`:482`) and `fft_output` (`:483`).

Two facts that make the restructure safe, both verifiable:

1. **The fortnum plan is shareable.** `fortnum_fft.f90` (FetchContent-pinned at `62a559c`, `CMakeLists.txt:244-251`) states in its module header: *"Pass a caller-owned fortnum_fft_plan_t to reuse twiddle tables across transforms of the same length (thread safe: plans are read-only during the transform)."* `fft_r2c` with `plan` present only reads `plan%n` and forwards to `r2c_planned`. So `plan_nphi` stays `shared`; no per-thread plan is needed.
2. **`stretch_coords` is already thread-safe.** `src/magfie/field_divB0.f90:830-833` uses double-checked locking with `!$omp critical` around the lazy convex-wall load.

Note that the third Biot-Savart routine in the same file, `biot_savart_sum_coils`, **already has the pattern this issue asks for** — `!$omp parallel do schedule(static) collapse(3)` over `kZ, kphi, kR` at `src/magfie/coil_tools.f90:367-369`. Use it as the in-repo template.

**Correction to the issue's proposed snippet:** it writes `!$omp do collapse(3)` over `kZ, kR, kphi`, but the `kphi` loop is *closed* before the `fft_r2c` calls, so those three loops are not perfectly nested and `collapse(3)` is invalid there. The collapsible loops are `kZ` and `kR` (and optionally `kc`). Collapse over `kc` as well is possible but conflicts with the per-coil progress `write` at `:507`; keep `kc` serial.

## Reproduction / evidence

There is no correctness bug to reproduce — this is a performance defect. Verification recipe using the fixture that already exists in the repo (`test/magfie/tilted_coil_geometry.py` generates `tilted_coil.dat`; `test/magfie/tilted_coil_fourier_modes.f90:32-37` runs `nR = 50, nZ = 50, nphi = 192, nmax = 16`, i.e. 2500 `(kR, kZ)` pairs → 5000 fork/join events per coil today):

```bash
make                                     # cmake --preset default && cmake --build --preset default
cd build/test/magfie
python3 /mnt/…/libneo/test/magfie/tilted_coil_geometry.py tilted_coil.dat

for t in 1 2 4 8 16; do
  OMP_NUM_THREADS=$t /usr/bin/time -f "$t threads: %e s" ./tilted_coil_fourier_modes.x
done
```

Observed today: wall time is essentially flat above ~4 threads, because each parallel region only has `nphi = 192` iterations and the barrier cost is comparable to the work. Expected after the fix: near-linear scaling to the physical core count, since each thread gets a contiguous block of `nR*nZ/nthreads` independent `(kR, kZ)` columns.

Bit-for-bit invariance is the second half of the recipe. Every `(kR, kZ)` column writes only its own slice of `Bn` / `An*`, and the reduction order inside the `ks` segment loop is unchanged, so the result must be **identical**, not merely close:

```bash
OMP_NUM_THREADS=1  ./tilted_coil_fourier_modes.x && cp Bnvac.nc Bnvac_serial.nc
OMP_NUM_THREADS=16 ./tilted_coil_fourier_modes.x && cmp Bnvac.nc Bnvac_serial.nc
```

For the AUG-scale case, `tools/vacfield_AUG.in` is a ready-made namelist; run `vacfield.x` with a real AUG coil set and time it before/after.

## Behaviour (BDD)

```gherkin
Scenario: Fourier B-field modes are thread-count invariant
  Given the fixture tilted_coil.dat generated by test/magfie/tilted_coil_geometry.py
  And the grid nR=50, nZ=50, nphi=192, nmax=16 from tilted_coil_fourier_modes.f90
  When tilted_coil_fourier_modes.x is run with OMP_NUM_THREADS=1 and then with OMP_NUM_THREADS=16
  Then the two Bnvac.nc outputs are byte-identical under cmp
  And test_coil_tools_biot_savart still passes at its declared tolerances
    (fourier_tolerance = 1.0e-10, analytical_tolerance = 1.0e-8)

Scenario: Vector-potential modes are thread-count invariant with the convex wall on
  Given a coil_field namelist derived from tools/vacfield_AUG.in with use_convex_wall = .true.
  And a convexwall.dat reachable through field_divB0.inp
  When vacfield.x writes AnR, Anphi, AnZ, dAnphi_dR, dAnphi_dZ at 1 and at 16 threads
  Then max |An(16 threads) - An(1 thread)| == 0 exactly for every mode and grid point

Scenario: Parallel region count drops from O(nR*nZ) to O(1) per coil
  Given biot_savart_fourier compiled with -fopenmp
  When the source is inspected
  Then exactly one !$omp parallel do directive exists in the routine
  And it encloses the kZ and kR loops with collapse(2), not the kphi loop

Scenario: Scaling improves measurably
  Given tilted_coil_fourier_modes.x on a machine with >= 8 physical cores
  When wall time is measured at OMP_NUM_THREADS = 1 and 8
  Then the speedup is at least 5x, versus the near-flat curve observed at fe3f76e
```

## Implementation plan

1. **`src/magfie/coil_tools.f90`, `biot_savart_fourier` (lines 400-462).** Delete the inner `!$omp parallel do` / `!$omp end parallel do` (`:430-432`, `:452`). Move `BR, Bphi, BZ, BnR, Bnphi, BnZ` out of the subroutine-scope declarations at `:412-413` and into a `block` construct inside the new parallel region (preferred over listing automatics in `private`, since it makes the per-thread allocation explicit and avoids compiler-dependent handling of automatic arrays in `private`). Wrap the `kZ`/`kR` loops:
   ```fortran
   do kc = 1, ncoil
   !$omp parallel do schedule(static) collapse(2) default(none) &
   !$omp private(kR, kZ, kphi, ks, XYZ_r, XYZ_i, XYZ_f, dist_i, dist_f, BXYZ) &
   !$omp shared(nR, nZ, nphi, nmax, kc, coils, R, Z, cosphi, sinphi, Bn, plan_nphi)
      do kZ = 1, nZ
         do kR = 1, nR
            block
              real(dp) :: BR(nphi), Bphi(nphi), BZ(nphi)
              complex(dp) :: BnR(nphi/2 + 1), Bnphi(nphi/2 + 1), BnZ(nphi/2 + 1)
              ...
            end block
         end do
      end do
   !$omp end parallel do
   end do
   ```
   Keep `plan_nphi` shared and `intent(in)` in `fft_r2c` (justified by the fortnum thread-safety note quoted above). Keep `schedule(static)` — the work per `(kR, kZ)` is exactly `nphi * nseg` flops, perfectly uniform, and static preserves reproducibility.
2. **Same file, `vector_potential_biot_savart_fourier` (lines 465-563).** Identical transformation: remove `!$omp parallel do` at `:516-520` and `!$omp end parallel do` at `:550`; wrap `kZ`/`kR` at `:508-509` with `collapse(2)`; move `AR, Aphi, AZ, dAphi_dR, dAphi_dZ, fft_output` (`:482-483`) and the scalars `actual_R, actual_Z` (`:481`) into the block / `private` list. `min_distance`, `max_eccentricity`, `use_convex_wall` are `shared`. Leave the `kc` loop and its progress `write` at `:507` serial.
3. **Same file, warm up the convex wall before the parallel region.** In `vector_potential_biot_savart_fourier`, after the existing `call read_field_input` at `:503`, add a single throw-away `call stretch_coords(R(1), Z(1), actual_R, actual_Z)` when `use_convex_wall` is true, so the `!$omp critical` lazy init in `field_divB0.f90:830` is never contended and the first-touch cost does not land inside a timed region.
4. **Same file, tidy the now-dead `nfft`.** `nfft` is set at `:424` and `:490` but no longer used for FFTW allocation; either use it to size the block-local complex arrays or delete the variable. Do not leave it dangling.
5. **`test/magfie/test_thread_invariance_biot_savart.f90` (new).** Per `CODING_STANDARD.md` TDD, write this first and watch it pass trivially at 1 thread. Program that calls `biot_savart_fourier` and `vector_potential_biot_savart_fourier` on a small circular coil (reuse `create_circular_coil` style helpers from `test/magfie/test_coil_tools_biot_savart.f90`), once with `call omp_set_num_threads(1)` and once with `call omp_set_num_threads(max(2, omp_get_max_threads()))`, and `error stop` unless every element compares exactly equal. Guard the `use omp_lib` behind the same `ENABLE_OPENMP` condition the library uses.
6. **`test/magfie/CMakeLists.txt`.** Add `add_executable(test_thread_invariance_biot_savart.x test_thread_invariance_biot_savart.f90)` linking `neo magfie util_for_test`, and `add_test(NAME test_thread_invariance_biot_savart COMMAND test_thread_invariance_biot_savart.x)` with `LABELS "magfie;biot_savart;openmp"` and `TIMEOUT 300`, matching the existing block at lines 4-18 of that file.
7. **No build-system change is otherwise needed.** `magfie` already links `OpenMP::OpenMP_Fortran` under `ENABLE_OPENMP` (`CMakeLists.txt:422-424`), and FFTW is gone, so there is no `fftw3` vs `fftw3_omp` decision left — record that in the PR description and cross-reference #317 / #295.
8. **Downstream check.** MEPHIT is in `ci/downstreams` and is the main consumer of `write_Anvac_fourier` / `write_Bnvac_fourier` output; the per-PR reverse-dependency gate (`.github/workflows/downstream-gate.yml`) will exercise it. Since the change is required to be bit-identical, no MEPHIT-side edit is expected.

## Acceptance criteria

- [ ] `make && cd build && ctest --output-on-failure` passes with no new failures.
- [ ] `test_thread_invariance_biot_savart` passes and asserts **exact** equality (`==`, not a tolerance) between the 1-thread and N-thread results for `Bn`, `AnR`, `Anphi`, `AnZ`, `dAnphi_dR`, `dAnphi_dZ`.
- [ ] `test_coil_tools_biot_savart` and the `tilted_coil_*` test chain (`tilted_coil_generate_geometry` → `tilted_coil_fourier_modes` → `tilted_coil_field_validation`) still pass at their existing tolerances.
- [ ] `rg -c '!\$omp parallel do' src/magfie/coil_tools.f90` returns 3, one per Biot-Savart routine, and neither of the two Fourier routines has a directive inside the `kR`/`kZ` loops.
- [ ] `OMP_NUM_THREADS=8 ./tilted_coil_fourier_modes.x` is at least 5x faster than `OMP_NUM_THREADS=1`, timings quoted in the PR.
- [ ] Debug build with `-ffpe-trap` (the CI Debug matrix leg) shows no new traps. Note the pre-existing filament-singularity trap tracked separately in itpplasma/libneo#350 — this PR must not make it worse, and should not attempt to fix it.
- [ ] MEPHIT downstream gate green.

## References

- Biot-Savart for filament coils with the arc-averaged segment formula used here is the standard approach of Hanson & Hirshman, *Compact expressions for the Biot-Savart fields of a filamentary segment*, Phys. Plasmas **9**, 4410 (2002) — the `(dist_i + dist_f)/(dist_i*dist_f*(dist_i*dist_f + XYZ_i·XYZ_f))` kernel at `coil_tools.f90:445-447` is exactly their form. Other codes computing vacuum fields from filaments the same way and parallelising over the *field-point* grid rather than the transform: STELLOPT's `BEAMS3D`/`MAKEGRID` (`mgrid` generation), SIMSOPT's `BiotSavart` (vectorised over evaluation points, with SIMD kernels), and DESC's coil field evaluation.
- The FFT itself is now fortnum's mixed-radix Stockham implementation after Temperton, *J. Comput. Phys.* **52**, 1 (1983), with a Bluestein chirp-z fallback (Bluestein, *IEEE Trans. Audio Electroacoust.* **18**, 451 (1970)) — cited in the `fortnum_fft` module header. The issue's original premise is confirmed by that design: a length-512 real transform is far too small to amortise threading inside the transform, so single-threaded FFT plus outer-loop parallelism is the right split.
- The general guidance to hoist `parallel` regions above the loop nest and reuse one thread team (rather than fork/join per iteration) is standard OpenMP practice; see the OpenMP API 5.2 specification, `parallel` and `collapse` clauses. No further literature is needed — the rest is an implementation detail internal to the code.

## Scope and risk

Single PR, roughly 60 lines of directive and declaration churn in one file plus one new test. The real risk is a wrongly-scoped `private`/`shared` list producing a silent race: mitigate by keeping `default(none)` (both routines already use it) and by making the new invariance test assert exact equality, which catches races that a tolerance-based check would hide. The second risk is a compiler that mishandles automatic arrays inside a `collapse`d parallel region — the `block` construct in step 1 avoids that entirely.

Related open issues: itpplasma/libneo#350 (correctness and `-ffpe-trap` problems in the same two routines — keep separate, but whoever touches `coil_tools.f90` should read it first), and itpplasma/libneo#295 / itpplasma/MEPHIT#24 for the FFTW removal that already answered this issue's closing question.
