### ISSUE TITLE
Check error status after opening HDF5 files

### ISSUE THREAD

**Issue by pazathoth** [itpplasma/libneo#49]
When a HDF5 file is opened for reading in, say, a Jupyter notebook, opening the HDF5 file with `hdf5_tools` will fail with less than enlightening debug messages. A `h5_check` after retrieving the error status should do the trick.

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still valid at `fe3f76e`. `h5_open` and `h5_open_rw` have never called `h5_check()`, and the module has since gained two new consumers (SPECTRE and JOREK readers, July 2026), so the blast radius grew rather than shrank.

## Purpose

`hdf5_tools` is the HDF5 entry point for libneo and for every downstream code that reads or writes HDF5 through it — MEPHIT (`MEPHIT/src/mephit_util.f90:220,279,543,612,703,724`), NEO-2 (`NEO-2/COMMON/collop_compute.f90`, `NEO-2/COMMON/magnetics.f90`, `NEO-2/NEO-2-PAR/propagator.f90:2651`), and now libneo's own `src/spectre/spectre_reader.f90:49` and `src/field/jorek_restart.f90:70`. When `h5fopen_f` fails — the common case being HDF5 ≥1.10 file locking while a Jupyter kernel holds the same file open via h5py, but equally a truncated file, a non-HDF5 file, or a wrong-version superblock — the failure is currently swallowed. Execution continues with an undefined `h5id`, and the user's first symptom is an HDF5 error stack emitted from some unrelated `h5ltread_dataset_*_f` call several frames later. The fix is small and turns a class of confusing debugging sessions into a one-line diagnostic naming the file.

## Current state

`src/hdf5_tools/hdf5_tools.F90:185-199`:

```fortran
  subroutine h5_open(filename, h5id)
    character(len=*)      :: filename
    integer(HID_T)        :: h5id
    logical               :: f_exists

    inquire (file=filename, exist=f_exists)
    if (f_exists) then
       call h5fopen_f(trim(filename), H5F_ACC_RDONLY_F, h5id, h5error)
    else
       write (*,*) "HDF5 file does not exist:", filename
       error stop
    end if
  end subroutine h5_open
```

The existence branch is handled; the *open failure* branch is not. `h5error` is set by `h5fopen_f` and then never read. Same pattern in `h5_open_rw` (`:204-222`, line 214). Note `inquire` is done on the untrimmed `filename` while `h5fopen_f` gets `trim(filename)` — harmless today but inconsistent.

The checker itself, `:134-140`:

```fortran
  subroutine h5_check()
    if (h5error < 0) then
       write (*,*) "HDF5 Error"
       call H5Eprint_f(h5error)
       error stop
    end if
  end subroutine h5_check
```

Two defects here. It carries no context (no filename, no operation name), and `h5eprint_f`'s first argument is `INTEGER, INTENT(OUT) :: hdferr` (HDF5 Fortran `H5Eff.F90`, `SUBROUTINE h5eprint_f(hdferr, name)`), so passing `h5error` *overwrites* the error code being reported instead of consuming it. Currently benign because `error stop` follows immediately, but it will bite anyone who makes `h5_check` non-fatal.

Other unchecked entry points in the same file: `h5_init` (`:117-121`), `h5_deinit` (`:126-129`), `h5_close` (`:176-180`), `h5_close_group` (`:253-257`), `h5_get_nmembers` (`:263-269`), `h5_get_objinfo` (`:275-283`). By contrast the dataset accessors are already covered — e.g. `h5_get_double_0` at `:1076-1082` ends in `call h5_check()`.

`test/source/test_hdf5_tools.f90` (registered at `test/CMakeLists.txt:155-158` and `:267`) exercises only the happy path: create, add, close, open, get, compare.

## Reproduction / evidence

`test/spectre/test_spectre_reader.x` takes the HDF5 path as `argv(1)` (`test/spectre/test_spectre_reader.f90:21-25`) and routes it into `load_spectre` → `h5_open`, so it is a ready-made probe. Point it at a file that *exists but is not HDF5*:

```bash
cd /path/to/libneo
make                                  # cmake --preset default && cmake --build --preset default
./build/test/spectre/test_spectre_reader.x test/resources/input_efit_file.dat
```

Observed at `fe3f76e`: `load_spectre` passes its own `inquire` existence check (`src/spectre/spectre_reader.f90:41-46`), calls `h5_open`, which fails silently, then `h5_get(h5id, 'input/physics/Igeometry', ...)` at `:50` reports an HDF5 error stack rooted in `H5Dopen`/`H5Fget_obj_ids` on an invalid identifier — with no mention of the file that actually failed to open.

Expected after the fix: a single line naming the operation and the file, e.g.

```
HDF5 error in h5_open: could not open file: test/resources/input_efit_file.dat
```

followed by the HDF5 stack and `error stop`.

The locking variant of the same bug (the one in the issue body) reproduces with:

```bash
python3 -c "import h5py,time; f=h5py.File('lock.h5','w'); time.sleep(60)" &
sleep 2
./build/test/spectre/test_spectre_reader.x lock.h5
```

## Behaviour (BDD)

```gherkin
Scenario: opening a file that exists but is not HDF5
  Given the text file test/resources/input_efit_file.dat exists
  When a program calls h5_open('test/resources/input_efit_file.dat', h5id)
  Then the program terminates via error stop
  And stderr or stdout contains "h5_open" and the string "input_efit_file.dat"

Scenario: opening a file held open for write by another process
  Given lock.h5 is open in mode 'w' by a running h5py process
  When a program calls h5_open('lock.h5', h5id)
  Then the program terminates via error stop
  And the message names "lock.h5" rather than an unrelated dataset name

Scenario: h5_open_rw still creates a missing file
  Given no file named brand_new.h5 exists in the working directory
  When a program calls h5_open_rw('brand_new.h5', h5id) and then h5_close(h5id)
  Then brand_new.h5 exists and contains the dataset 'version' with value 1

Scenario: existing happy path is unchanged
  Given the fixture test/spectre/data/spectre_test.h5
  When ctest -R "test_spectre_reader|test_hdf5_tools|test_jorek_restart" runs
  Then all three tests pass with no new output on the success path
```

## Implementation plan

1. **`src/hdf5_tools/hdf5_tools.F90`, `h5_check` (`:134-140`)** — add an optional context argument and stop clobbering the error code:

   ```fortran
   subroutine h5_check(context)
     character(len=*), intent(in), optional :: context
     integer :: print_status

     if (h5error < 0) then
        if (present(context)) then
           write (*, '(A)') "HDF5 error in "//trim(context)
        else
           write (*, '(A)') "HDF5 error"
        end if
        call h5eprint_f(print_status)
        error stop
     end if
   end subroutine h5_check
   ```

   The optional dummy keeps all ~180 existing bare `call h5_check()` sites compiling unchanged.

2. **Same file, `h5_open` (`:185-199`)** — after `h5fopen_f`, add
   `call h5_check("h5_open: could not open file: "//trim(filename))`.
   Also make the `inquire` use `trim(filename)` for consistency with the `h5fopen_f` call.

3. **Same file, `h5_open_rw` (`:204-222`)** — add
   `call h5_check("h5_open_rw: could not open file: "//trim(filename))`
   inside the `f_exists` branch only. **Do not** touch the else branch: NEO-2 relies on the create-on-missing behaviour (`NEO-2/COMMON/magnetics.f90:1527`, `NEO-2/COMMON/binarysplit_mod.f90:411`).

4. **Same file, remaining entry points** — add context-carrying `h5_check` calls to `h5_init` (`:117`), `h5_deinit` (`:126`), `h5_close` (`:176`), `h5_close_group` (`:253`), `h5_get_nmembers` (`:263`), `h5_get_objinfo` (`:275`). `h5_close`/`h5_close_group` failures currently vanish and are a real leak source given the comment at `:249-252` about the open-group limit.

5. **`test/source/test_hdf5_tools_errors.f90` (new)** — a program that takes a path as `argv(1)`, calls `h5_init` then `h5_open` on it, and (unreachable if the fix works) prints `"REACHED"` and `error stop 1`. Model the argument handling on `test/spectre/test_spectre_reader.f90:21-25`.

6. **`test/CMakeLists.txt`** — next to the existing block at `:155-158`, add:

   ```cmake
   add_executable(test_hdf5_tools_errors.x source/test_hdf5_tools_errors.f90)
   target_link_libraries(test_hdf5_tools_errors.x ${HDF5_TOOLS_LIB})
   ```

   and next to `:267`:

   ```cmake
   add_test(NAME test_hdf5_open_not_hdf5
            COMMAND test_hdf5_tools_errors.x
                    ${PROJECT_SOURCE_DIR}/test/resources/input_efit_file.dat)
   set_tests_properties(test_hdf5_open_not_hdf5 PROPERTIES
                        PASS_REGULAR_EXPRESSION "h5_open.*input_efit_file")
   ```

   `PASS_REGULAR_EXPRESSION` overrides the exit-code check, so the `error stop` does not mark the test failed. Follow the repo's TDD rule (`CODING_STANDARD.md`): add step 5/6 first and watch it fail before doing steps 1-4.

7. **Optional follow-up, separate PR** — a non-aborting `h5_open_status(filename, h5id, ierr)` so `spectre_reader.f90` and `jorek_restart.f90`, which already carry an `ierr` protocol (`src/spectre/spectre_reader.f90:40-46`, `src/field/jorek_restart.f90:60-66`), can return a code instead of aborting a downstream run. Keep this out of the first PR.

No downstream repo needs to change: the signature change is additive and the new behaviour only replaces undefined behaviour with a clean abort. The downstream gate (`ci/downstreams`) will still exercise MEPHIT, NEO-2 and KAMEL against the change.

## Acceptance criteria

- [ ] `cmake --build --preset default` succeeds with no new warnings in `src/hdf5_tools/`.
- [ ] `cd build && ctest -R test_hdf5 --output-on-failure` passes, including the new `test_hdf5_open_not_hdf5`.
- [ ] `./build/test/spectre/test_spectre_reader.x test/resources/input_efit_file.dat` prints a message containing `h5_open` and `input_efit_file.dat` and exits non-zero, with no HDF5 stack from `H5Dopen`.
- [ ] `ctest -R "test_spectre|test_jorek|test_hdf5_tools"` passes unchanged (no regression on the happy path).
- [ ] `rg -n "call h5fopen_f|call h5fcreate_f" src/hdf5_tools/hdf5_tools.F90` — every hit is followed within three lines by a `h5_check` call.
- [ ] `h5_open_rw` on a non-existent path still creates the file with a `version` dataset (covered by the third BDD scenario).
- [ ] The full downstream gate (`.github/workflows/downstream-gate.yml`) is green for SIMPLE, NEO-2, MEPHIT, KAMEL, rabe.

## References

No specific literature reference; this is an implementation detail internal to the code. The relevant normative material is the HDF5 Fortran API contract: every `h5*_f` routine returns a negative `hdferr` on failure and the caller must inspect it (HDF Group, *HDF5 Fortran Reference Manual*), and `h5eprint_f`'s first argument is `INTENT(OUT)` as declared in the HDF5 source `fortran/src/H5Eff.F90`. The file-locking behaviour that triggers the reported Jupyter symptom is the HDF5 1.10+ SWMR file lock, disableable via `HDF5_USE_FILE_LOCKING=FALSE` — worth mentioning in the new error message as a hint.

## Scope and risk

Single small PR: ~40 lines changed in one file plus one new test and two CMake blocks. The only real risk is turning a previously silent no-op into an abort in some downstream path that was accidentally tolerating a failed close — `h5_close`/`h5_close_group` (step 4) are the candidates, so if the downstream gate goes red, split step 4 out and land steps 1-3 and 5-6 first.

Related: itpplasma/libneo#348 proposes replacing the HDF5/NetCDF Fortran bindings with ISO C bindings across libneo and downstreams, which would eventually supersede this wrapper — but that is a large rewrite with no PR yet, and it should not block a 40-line diagnostic fix. itpplasma/libneo#268 (make HDF5 Fortran optional) touches the same target's build wiring; no code conflict. itpplasma/KAMEL#54 would move KAMEL onto this very module (KAMEL currently vendors its own copy at `KAMEL/common/hdf5_tools/hdf5_tools.f90`), so landing this first makes that migration strictly better.
