### ISSUE TITLE
Add routines in Python to access MDS+ from AUG, TCV and MAST-U

### ISSUE THREAD

**Issue by krystophny** [itpplasma/libneo#82]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `fe3f76e`. Verify before acting.*

Still open and still unimplemented. `rg -ni 'mds\+|mdsplus|aug_sfutils|shotfile|pyuda'` over the whole checkout returns **zero hits**, and the same search across every sibling checkout in `/mnt/storage/triage/repos/` also returns nothing — no other repo in the org has quietly grown this capability. `git log --all -i --grep=mds` is empty. The issue body is empty, so the spec below fills it in.

One correction up front, because it changes the design: only **TCV** is natively MDSplus. AUG's canonical store is the shotfile system (Python access via `aug_sfutils`; an MDSplus gateway exists but is a secondary view), and MAST-U's canonical store is **UDA** (`pyuda`), not MDSplus. So the deliverable is *one machine-agnostic fetch API with three pluggable transports*, not "MDS+ routines". Writing it as literal MDS+ for all three will not work against MAST-U.

## Purpose

Every AUG/TCV/MAST-U study in this group currently starts by someone hand-copying a g-file and a set of kinetic profiles onto disk. The downstream chain is fully automated from a g-file onward — `python/libneo/eqdsk_to_boozer_chartmap.py` writes `field_divB0.inp` and drives `efit_to_boozer.x`, and `src/magfie/standardise_geqdsk.f90` fixes the COCOS convention — but the first step is manual and unrecorded, so runs are not reproducible from a shot number. Concretely, `rmp_torque#5` ("Compute NTV for MAST-U for Anu and Tuomas"), `rmp_torque#4` and `NEO-2#81` (both AUG 30835) all need exactly this. A `fetch_equilibrium("AUG", 30835, t=2.5)` that lands in libneo's existing eqdsk dict schema makes shot number plus time the reproducible input.

## Current state

libneo's Python package has readers/writers for the *file* formats but no data-system access:

- `python/libneo/eqdsk_base.py:11` `read_eqdsk(filename)` builds the canonical dict (`nrgr`, `nzgr`, `rboxlength`, `zboxlength`, `R0`, `rboxleft`, `zboxmid`, `R`, `Z`, `Rpsi0`, `Zpsi0`, `PsiaxisVs`, `PsiedgeVs`, `Btor_at_R0`, `Ip`, `fprof`, `ptotprof`, `fdfdpsiprof`, `dpressdpsiprof`, `PsiVs`, `qprof`, `npbound`, `nplimiter`, `Lcfs`, `Limiter`).
- `python/libneo/eqdsk_base.py:105` `write_eqdsk(filename, eqdata)` writes that dict back out as GEQDSK. **This is the integration point**: anything that produces the dict gets the whole downstream chain for free.
- `python/libneo/eqdsk.py:1` `class eqdsk_file` wraps a file and adds `psi_at_rz`.
- `src/magfie/standardise_geqdsk.f90:1` — `standardise_geqdsk.x infile outfile`, calling `geqdsk_read`/`geqdsk_classify`/`geqdsk_standardise`/`geqdsk_write` from `src/magfie/geqdsk_tools.f90`. Use this rather than reimplementing COCOS handling in Python.

The import surface is eager and this constrains the design — `python/libneo/__init__.py` does:

```python
from .boozer import *
from .eqdsk import *
from .eqdsk_base import *
```

so a new module that imports `MDSplus`/`aug_sfutils`/`pyuda` at top level and is added to that list would make `import libneo` fail on every machine without those packages installed, including CI. The new module must be imported lazily.

Dependencies live in `pyproject.toml:15-45` (`[project.optional-dependencies]` already has `chartmap`, `dev`, `docs`); CI runs `python -m pytest python/tests -vv -s` (`.github/workflows/main.yml:101`) on a GitHub-hosted runner with **no route to any lab network**, so no test may require a live server.

## Reproduction / verification recipe

There is nothing to reproduce; this is a feature request. Verification recipe, smallest useful case:

```bash
pip install -e ".[dev,mdsplus]"
python -c "
from libneo.machine_data import fetch_equilibrium
from libneo.eqdsk_base import write_eqdsk
eq = fetch_equilibrium('AUG', 30835, time=2.5)   # on an IPP machine
write_eqdsk('g30835.2500', eq)
"
./build/standardise_geqdsk.x g30835.2500 g30835.2500.std
python -c "
from libneo.eqdsk_base import read_eqdsk
import numpy as np
e = read_eqdsk('g30835.2500.std')
print(e['Ip'], e['Btor_at_R0'], e['R0'], e['PsiVs'].shape)
assert e['PsiVs'].shape == (e['nzgr'], e['nrgr'])
"
```

Expected physical sanity for AUG 30835 (an existing group reference case, cf. `NEO-2#81`, `GORILLA_APPLETS#40`): `R0` ≈ 1.65 m, `|Btor_at_R0|` ≈ 2.5 T, `|Ip|` ≈ 0.8 MA. A round-trip check that does *not* need the network: `write_eqdsk` the fetched dict, `read_eqdsk` it back, and require every float array to agree to `rtol=1e-6` — the write format is `%16.8E` (`eqdsk_base.py:107`), so 8 significant digits is the achievable tolerance.

Offline test data: record one real fetch per machine to a small `.npz` under `python/tests/data/` (subsample `PsiVs` to a 33×33 grid to keep it a few tens of kB) and replay it through a fake client. Do not add multi-MB fixtures.

## Behaviour (BDD)

```gherkin
Scenario: importing libneo without any data-system client installed
  Given MDSplus, aug_sfutils and pyuda are all absent from the environment
  When the user runs "python -c 'import libneo'"
  Then the import succeeds with exit code 0
  And "from libneo.machine_data import fetch_equilibrium" also succeeds
  And only calling fetch_equilibrium('TCV', 70000) raises ImportError
       with a message naming the missing package and the pip extra "libneo[mdsplus]"

Scenario: fetched equilibrium is a valid libneo eqdsk dict
  Given the recorded fixture python/tests/data/tcv_70000_liuqe.npz
  When fetch_equilibrium('TCV', 70000, time=1.0, client=FakeMdsClient(fixture)) is called
  Then the returned dict has every key produced by libneo.eqdsk_base.read_eqdsk
  And eq['PsiVs'].shape == (eq['nzgr'], eq['nrgr'])
  And len(eq['fprof']) == len(eq['qprof']) == eq['nrgr']
  And eq['R'][0] == pytest.approx(eq['rboxleft'], rel=1e-12)

Scenario: GEQDSK round trip preserves the fetched data
  Given a dict returned by fetch_equilibrium from any recorded fixture
  When it is passed to libneo.eqdsk_base.write_eqdsk and read back with read_eqdsk
  Then every float array agrees to rtol=1e-6
  And nrgr, nzgr, npbound, nplimiter are bit-identical

Scenario: nearest-time selection is explicit
  Given a fixture whose equilibrium time base is [1.0, 1.1, 1.2] s
  When fetch_equilibrium(..., time=1.14) is called
  Then the slice at 1.1 s is returned
  And the returned dict carries eq['time'] == 1.1 and eq['shot'] and eq['source']
       recording the tree/diagnostic and node paths actually read

Scenario: live-server tests never run in CI
  Given the GitHub-hosted runner used by .github/workflows/main.yml
  When "python -m pytest python/tests -vv -s" runs
  Then all tests marked @pytest.mark.network are skipped
  And the suite exits 0 without opening a socket
```

## Implementation plan

1. **Create `python/libneo/machine_data/__init__.py`** — public API only: `fetch_equilibrium(machine, shot, time=None, *, client=None, source=None)`, `fetch_profiles(machine, shot, time=None, *, client=None)`, `list_machines()`. No third-party imports at module level.
2. **Create `python/libneo/machine_data/base.py`** — `class MachineBackend` with abstract `fetch_equilibrium`/`fetch_profiles`, plus `_check_eqdsk_dict(d)` validating exactly the key set produced by `eqdsk_base.read_eqdsk` (import the key list from a single shared tuple so the two cannot drift). Put nearest-time selection and the `shot`/`time`/`source` provenance stamping here, not in the backends.
3. **Create `python/libneo/machine_data/tcv.py`** — MDSplus backend. Open tree `tcv_shot`, read the LIUQE results under `\results::`. *Do not trust node names from this comment* — put them in a module-level `SIGNALS` dict, verify each one interactively against a real shot on a TCV-connected host, and record the verified map in the module docstring. Accept an injected `client` object exposing `.get(expr)` so tests can replay a fixture.
4. **Create `python/libneo/machine_data/aug.py`** — shotfile backend via `aug_sfutils`, equilibrium diagnostic selectable (`EQH` default, `IDE`/`EQI` optional) through the `source=` argument. `aug_sfutils` already exposes equilibrium objects and a GEQDSK export path; prefer converting its output into the libneo dict over re-deriving `fdfdpsiprof`/`dpressdpsiprof` yourself. Same injected-client pattern.
5. **Create `python/libneo/machine_data/mastu.py`** — `pyuda` backend (this is the one that is *not* MDS+). Equilibrium comes from the EPM/EFIT++ output group; again put the signal paths in a `SIGNALS` dict verified on a UDA-connected host.
6. **Edit `pyproject.toml`** — add to `[project.optional-dependencies]`: `mdsplus = ["MDSplus"]`, `aug = ["aug_sfutils"]`, `mastu = []` (pyuda is not on PyPI; document the site-local install in the module docstring and in `docs/`). Add `machine_data` to `[tool.scikit-build.wheel.packages]` coverage — verify the existing `libneo = "python/libneo"` entry at `pyproject.toml:59-60` picks up the subpackage, and add an explicit entry if it does not. Add a `[project.scripts]` entry `libneo-fetch-equilibrium = "libneo.machine_data.cli:main"` alongside the existing `libneo-write-chartmap`.
7. **Create `python/libneo/machine_data/cli.py`** — `libneo-fetch-equilibrium --machine AUG --shot 30835 --time 2.5 --out g30835.2500`, calling `fetch_equilibrium` then `write_eqdsk`.
8. **Do NOT touch `python/libneo/__init__.py`'s star-import block.** If a top-level convenience name is wanted, add a module-level `__getattr__` that imports `machine_data` on first attribute access.
9. **Create `python/tests/test_machine_data.py`** — fixture-replay tests for scenarios 1-4 above. Follow the existing style in `python/tests/test_eqdsk_base.py`; `python/tests/conftest.py` already extends `libneo.__path__` so a new subpackage is importable in an editable checkout.
10. **Create `python/tests/data/{tcv,aug,mastu}_*.npz`** — one recorded, subsampled slice per machine, plus a short `README` in that directory naming shot, time, tree/diagnostic and the date recorded.
11. **Edit `pyproject.toml`** to register the marker (`[tool.pytest.ini_options] markers = ["network: requires a lab data server"]` — there is currently no `[tool.pytest.ini_options]` section at all) and mark the optional live-server tests `@pytest.mark.network`; add `-m "not network"` to the pytest invocations at `.github/workflows/main.yml:100-101`.
12. **Create `docs/machine_data.rst`** and add it to the toctree in `docs/index.rst`, documenting per-machine prerequisites, the network/VPN requirement, and the COCOS caveat (route fetched g-files through `standardise_geqdsk.x` before `efit_to_boozer`).

No Fortran, CMake or sibling-repo changes are required. Nothing here touches the downstream gate set in `ci/downstreams`.

## Acceptance criteria

- [ ] `python -c "import libneo"` succeeds in an environment with none of MDSplus/aug_sfutils/pyuda installed.
- [ ] `python -m pytest python/tests -vv -m "not network"` passes and opens no socket.
- [ ] `python -m pytest python/tests/test_machine_data.py -vv` covers all three machines from recorded fixtures.
- [ ] Round-trip `fetch → write_eqdsk → read_eqdsk` agrees to `rtol=1e-6` on every float array.
- [ ] Every returned dict passes `_check_eqdsk_dict` against the exact key set of `eqdsk_base.read_eqdsk`.
- [ ] On a lab-connected host, `libneo-fetch-equilibrium --machine AUG --shot 30835 --time 2.5 --out g30835.2500` produces a file that `./build/standardise_geqdsk.x` accepts without error stop, and the resulting g-file drives `python/libneo/eqdsk_to_boozer_chartmap.py` to completion.
- [ ] Existing Python suite unchanged: `python -m pytest test/python -q` and `python -m pytest python/tests -vv` still pass.
- [ ] Total added fixture bytes under 500 kB.

## References

- Stillerman, Fredian, Klare, Manduchi, *MDSplus data acquisition system*, Rev. Sci. Instrum. **68**, 939 (1997) — the MDSplus tree/node model the TCV backend targets.
- Lao, St. John, Stambaugh, Kellman, Pfeiffer, *Reconstruction of current profile parameters and plasma shapes in tokamaks*, Nucl. Fusion **25**, 1611 (1985) — EFIT and the GEQDSK content model that `eqdsk_base.py` implements.
- Sauter & Medvedev, *Tokamak coordinate conventions: COCOS*, Comput. Phys. Commun. **184**, 293 (2013) — why fetched equilibria must be classified and standardised; already implemented in `src/magfie/geqdsk_tools.f90`.
- Meneghini et al., *Integrated modeling applications for tokamak experiments with OMFIT*, Nucl. Fusion **55**, 083008 (2015) — OMFIT solves exactly this problem with per-machine data-access modules behind one interface; the backend-per-machine structure above mirrors it.
- Imbeaux et al., *Design and first applications of the ITER integrated modelling & analysis suite*, Nucl. Fusion **55**, 123006 (2015) — IMAS/IDS `equilibrium` is the long-term machine-agnostic alternative; worth keeping the dict schema close enough that an IMAS backend can be added as a fourth transport later.

## Scope and risk

One PR is feasible but the three backends are independently testable and independently blocked on machine access, so **split it**: a first PR with `machine_data/{__init__,base,cli}.py`, the dict-schema validator, the round-trip test and the pytest marker/CI wiring (no lab access needed, fully CI-verifiable); then one small PR per machine, each adding its backend, its fixture and its docs entry. The only regression risk to existing code is the eager import chain in `python/libneo/__init__.py` and the wheel packaging change in `pyproject.toml`; both are covered by the first acceptance criterion. Long-term maintenance risk is real and worth stating in the docs: signal names and equilibrium diagnostics on all three machines change without notice, and CI cannot detect it — the recorded fixtures pin the *parsing*, not the *node map*.

Related open issues that would consume this: `itpplasma/rmp_torque#5`, `itpplasma/rmp_torque#4`, `itpplasma/NEO-2#81`, `itpplasma/GORILLA_APPLETS#40`.
